Repository fylein/fyle-mobile-app, pull requests merged in 2023-10, with the labels that each got.

#2442 feat: Category optimization in getNewExpenseObservable
  src/app/core/mock-data/org-category.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#2468 test: Mileage/ Per Diem expenses to depend on category
  src/app/core/mock-data/action-sheet-options.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/services/categories.service.spec.ts
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
Labels: size/M

#2470 test: Code Coverage: Notifications Page #2
  src/app/core/models/notification-events.model.ts
  src/app/fyle/notifications/notifications.page.spec.ts
  src/app/fyle/notifications/notifications.page.ts
Labels: size/M

#2448 test: Code Coverage: Notifications Page #1
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/models/notification-events.model.ts
  src/app/fyle/notifications/notifications.page.spec.ts
  src/app/fyle/notifications/notifications.page.ts
Labels: size/L

#2441 fix: Notifications Page Linting
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/models/notification-events.model.ts
  src/app/fyle/notifications/notifications.page.spec.ts
  src/app/fyle/notifications/notifications.page.ts
Labels: size/L

#2449 test: Code Coverage: FormButtonValidation Directive
  src/app/shared/directive/form-button-validation.directive.spec.ts
Labels: size/M

#2463 feat: Integration for /check_mandatory_fields API to check receipt mandatory status and block expense save
  src/app/core/mock-data/missing-mandatory-fields.data.ts
  src/app/core/models/platform/platform-missing-mandatory-fields-response.model.ts
  src/app/core/models/platform/platform-missing-mandatory-fields.model.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#2478 fix: Google auth upgrade ios
  android/app/capacitor.build.gradle
  android/app/src/main/assets/capacitor.config.json
  android/app/src/main/assets/capacitor.plugins.json
  android/capacitor.settings.gradle
  ios/App/App/capacitor.config.json
  ios/App/App/config.xml
  ios/App/Podfile
  ios/App/Podfile.lock
Labels: size/XL

#2474 test: Fixing add card component flaky tests
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.spec.ts
Labels: size/S

#2464 feat: Show error in the expense form if receipt is mandatory and missing
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/shared/components/fy-alert-info/fy-alert-info.component.html
  src/app/shared/components/fy-alert-info/fy-alert-info.component.ts
Labels: size/S

#2461 feat: Mileage/ Per Diem expenses to depend on category
  src/app/core/mock-data/action-sheet-options.data.ts
  src/app/core/mock-data/allowed-expense-types.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/services/categories.service.spec.ts
  src/app/core/services/categories.service.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.scss
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/L

#2459 fix: updated condition for category autofill
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#2473 feat: Remove unified card enrollment flow LD flag
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/M

#2482 test: 98.45% coverage of add-edit-adv-request page
  src/app/core/mock-data/advance-requests-custom-fields.data.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-1.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
Labels: size/M

#2481 test: 87% coverage of add-edit-adv-request page
  src/app/core/mock-data/advance-requests-custom-fields.data.ts
  src/app/core/mock-data/advance-requests.data.ts
  src/app/core/mock-data/unflattened-advance-request.data.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-1.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.setup.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
Labels: size/L

#2479 test: 70% coverage of add-edit-adv-req page
  src/app/core/mock-data/advance-requests-custom-fields.data.ts
  src/app/core/mock-data/advance-requests.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/unflattened-advance-request.data.ts
  src/app/core/models/advance-request-delete-params.model.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-1.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.setup.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
Labels: size/L

#2476 test: 58% coverage add-edit-adv-request page
  src/app/core/mock-data/add-edit-advance-request-form-value.data.ts
  src/app/core/mock-data/advance-request-custom-field-values.data.ts
  src/app/core/mock-data/advance-requests-custom-fields.data.ts
  src/app/core/mock-data/advance-requests.data.ts
  src/app/core/mock-data/file-object.data.ts
  src/app/core/mock-data/file.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/unflattened-advance-request.data.ts
  src/app/core/models/advance-request-delete-params.model.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-1.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.setup.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
Labels: size/XL

#2467 test: 40% coverage of add-edit-adv-request pagee
  src/app/core/mock-data/add-edit-advance-request-form-value.data.ts
  src/app/core/mock-data/advance-request-custom-field-values.data.ts
  src/app/core/mock-data/advance-requests-custom-fields.data.ts
  src/app/core/mock-data/advance-requests.data.ts
  src/app/core/mock-data/file-object.data.ts
  src/app/core/mock-data/file.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/unflattened-advance-request.data.ts
  src/app/core/models/advance-request-delete-params.model.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-1.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.setup.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
Labels: size/XL

#2485 test: remaining method in add-edit-exp
  src/app/core/mock-data/corporate-card-expense-unflattened.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
Labels: size/S

#2487 fix: Notifications Page Fixing Tests
  src/app/core/mock-data/notification-events.data.ts
  src/app/core/services/org-user-settings.service.spec.ts
  src/app/fyle/notifications/notifications.page.spec.ts
Labels: size/L

#2491 feat: Updating readme
  README.md
Labels: size/XS

#2497 fix: Add card CTA usability issue
  src/app/shared/components/add-card/add-card.component.html
  src/app/shared/components/add-card/add-card.component.spec.ts
  src/app/shared/components/spent-cards/spent-cards.component.html
Labels: size/XS

#2465 feat: Skip mandatory receipt check for capture receipt flow
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#2499 feat: remove thumbnails across mobile app
  src/app/core/mock-data/file-object.data.ts
  src/app/core/services/file.service.spec.ts
  src/app/core/services/file.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.html
  src/app/shared/components/expense-card-lite/expense-card-lite.component.scss
  src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.html
  src/app/shared/components/expenses-card/expenses-card.component.scss
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
  src/assets/images/pdf-receipt-placeholder.png
Labels: size/L

#2490 test: 100% coverage of my-expenses service
  src/app/core/mock-data/filter-options.data.ts
  src/app/core/mock-data/selected-filters.data.ts
  src/app/fyle/my-expenses/my-expenses.service.spec.ts
Labels: size/L

#2486 test: 38% coverage of my-expenses service
  src/app/core/mock-data/expense-filters.data.ts
  src/app/core/mock-data/filter-options.data.ts
  src/app/core/mock-data/filter-pills.data.ts
  src/app/core/mock-data/selected-filters.data.ts
  src/app/fyle/my-expenses/my-expenses.service.spec.ts
  src/app/fyle/my-expenses/my-expenses.service.ts
Labels: size/XL

#2494 test: 100% coverage of view-team-adv-request page
  src/app/core/mock-data/modal-controller.data.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
Labels: size/M

#2493 test: 66% coverage of view-team-adv-request page
  src/app/core/mock-data/file-object.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/popup.data.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
Labels: size/L

#2492 test: 35% coverage of view-team-advance-request page
  src/app/core/mock-data/file-object.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/popup.data.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
Labels: size/L

#2495 test: 40% coverage of my-view-advance-request page
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.spec.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
Labels: size/L

#2498 test: 100% coverage of my view advances page
  src/app/fyle/my-view-advance/my-view-advance.page.spec.ts
  src/app/fyle/my-view-advance/my-view-advance.page.ts
Labels: size/M

#2475 feat: Removing Push Notifications in Settings
  src/app/fyle/notifications/notifications.page.html
Labels: size/XS

#2471 feat: Changed content of alert message for incomplete expenses
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
Labels: size/XS

#2472 test: Tests for receipt mandatory settings changes
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/M

#2510 fix: showing last_synced_at for amex feed cards in dashboard
  src/app/core/enums/data-feed-source.enum.ts
  src/app/core/mock-data/platform-corporate-card.data.ts
  src/app/shared/components/corporate-card/corporate-card.component.html
  src/app/shared/components/corporate-card/corporate-card.component.scss
  src/app/shared/components/corporate-card/corporate-card.component.spec.ts
  src/assets/images/amex-logo.png
Labels: size/M

#2500 test: 100% coverage of virtual-select component
  src/app/core/mock-data/modal-controller.data.ts
  src/app/shared/components/virtual-select/virtual-select.component.spec.ts
Labels: size/L

#2484 test: scrollInputIntoView method coverage in all pages
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/L

#2506 test: removing unnecessary optionals and increasing branch cov - 4
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
Labels: size/M

#2505 test: removing unnecessary optionals and increasing branch cov - 3
  src/app/core/mock-data/expense-fields-map.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#2504 test: removing unnecessary optionals and increasing branch cov - 2
  src/app/core/mock-data/expense-fields-map.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/L

#2503 test: removing unnecessary optionals and increasing branch cov - 1
  src/app/core/mock-data/expense-fields-map.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/L

#2507 test: some branches in transaction-outbox service
  src/app/core/mock-data/parsed-receipt.data.ts
  src/app/core/services/transactions-outbox.service.spec.ts
Labels: size/M

#2508 test: some branches in app-version service
  src/app/core/services/app-version.service.spec.ts
Labels: size/S

#2509 test: some branches in freshchat service
  src/app/core/services/fresh-chat.service.spec.ts
  src/app/core/services/fresh-chat.service.ts
Labels: size/M

#2518 test: capture-receipt component leftover branches
  src/app/core/mock-data/modal-controller.data.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
Labels: size/M

#2517 test: fy-currency component inside add-edit-adv-request page
  src/app/fyle/add-edit-advance-request/fy-currency/fy-currency.component.spec.ts
Labels: size/M

#2519 test: fy-currency-choose-currency in add edit advance request page
  src/app/core/mock-data/currency.data.ts
  src/app/fyle/add-edit-advance-request/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.spec.ts
  src/app/fyle/add-edit-advance-request/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.ts
Labels: size/M

#2520 test: ignore fyle-routing.module.ts file as it is not testable
  angular.json
Labels: size/XS

#2521 test: some branches in add-edit-mileage page
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/M

#2524 test: some branches in view per diem page
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/M

#2523 test: some branches in route selector component
  src/app/shared/components/route-selector/route-selector.component.spec.ts
  src/app/shared/components/route-selector/route-selector.component.ts
Labels: size/M

#2502 feat: fail test workflow if coverage falls below 95%
  .github/workflows/unit-tests.yml
Labels: size/XS

#2529 fix: removed upload_completed API call
  src/app/core/services/file.service.spec.ts
  src/app/core/services/file.service.ts
  src/app/core/services/transactions-outbox.service.ts
Labels: size/S
