Repository fylein/fyle-mobile-app, pull requests merged in 2023-06, with the labels that each got.

#2069 fix: Added types in popup service
  src/app/core/services/popup.service.ts
Labels: size/XS

#2068 feat: Add PR template
  .github/pull_request_template.md
Labels: size/XS

#2057 test: 100% Coverage of AppVersionPage
  src/app/auth/app-version/app-version.page.spec.ts
  src/app/auth/app-version/app-version.page.ts
  src/app/core/mock-data/extended-device-info.data.ts
  src/app/core/services/platform-handler.service.spec.ts
  src/app/core/services/platform-handler.service.ts
Labels: size/M

#2052 test: Code Coverage: My View Report Component #2
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/model-properties.data.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/L

#2076 fix: added types for refinerService
  src/app/core/models/refiner_properties.model.ts
  src/app/core/services/refiner.service.ts
Labels: size/M

#2074 fix: Added types for recentlyUsed service
  src/app/core/models/v1/cost-center.model.ts
  src/app/core/services/recently-used-items.service.ts
Labels: size/S

#2075 fix: Added types : Mileage rates services
  src/app/core/services/mileage-rates.service.ts
Labels: size/XS

#2078 fix: Added types : Mileage services
  src/app/core/services/mileage.service.ts
Labels: size/XS

#2071 fix: Config Service
  src/app/core/services/config.service.ts
  src/app/core/services/token.service.ts
Labels: size/XS

#2067 fix: Back Button Service
  src/app/core/models/overlay-response.modal.ts
  src/app/core/services/back-button.service.ts
Labels: size/XS

#2065 fix: Stats Response Model
  src/app/core/mock-data/stats-response.data.ts
  src/app/core/models/v2/stats-response.model.ts
Labels: size/M

#2061 fix: Advance Request Policy Service
  src/app/core/services/advance-request-policy.service.ts
Labels: size/XS

#2077 fix: Custom Inputs Service
  src/app/core/models/txn-custom-properties.model.ts
  src/app/core/services/custom-fields.service.ts
Labels: size/S

#2080 fix: Added types for secureStorage service
  src/app/core/services/secure-storage.service.ts
  src/app/core/services/token.service.ts
Labels: size/XS

#2053 test: 100% Coverage of SelectCurrency page inside setup account
  src/app/core/mock-data/currency.data.ts
  src/app/post-verification/setup-account/select-currency/select-currency.component.spec.ts
  src/app/post-verification/setup-account/select-currency/select-currency.component.ts
Labels: size/M

#2081 fix: Added types in tracking service
  src/app/core/models/tracking-properties.model.ts
  src/app/core/services/tracking.service.ts
Labels: size/L

#2086 fix: types added for setSnackbarProperties in model.ts
  src/app/core/models/snackbar-properties.model.ts
  src/app/core/services/snackbar-properties.service.ts
Labels: size/XS

#2090 fix: Http Interceptor
  src/app/core/interceptors/httpInterceptor.ts
Labels: size/XS

#2089 fix: Api Service
  src/app/core/mock-data/pdf-export.data.ts
  src/app/core/models/pdf-exports.model.ts
  src/app/core/services/api.service.ts
  src/app/core/services/auth.service.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/core/services/currency.service.ts
  src/app/core/services/file.service.ts
  src/app/core/services/org-user.service.ts
  src/app/core/services/org.service.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/report.service.ts
  src/app/core/services/status.service.spec.ts
  src/app/core/services/status.service.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/core/services/user.service.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/create-new-report/create-new-report.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
Labels: size/L

#2088 fix: Data Transform Service
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/models/advance-requests.model.ts
  src/app/core/models/unflattened-advance-request.model.ts
  src/app/core/services/accounts.service.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/data-transform.service.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/report.service.ts
  src/app/core/services/split-expense.service.ts
  src/app/core/services/transaction.service.ts
Labels: size/M

#2073 fix: Added Types in RecentLocalStorageItem Service
  src/app/core/mock-data/recent-local-storage-items.data.ts
  src/app/core/models/login-info.model.ts
  src/app/core/services/login-info.service.ts
  src/app/core/services/recent-local-storage-items.service.ts
  src/app/core/services/report.service.ts
  src/app/core/services/storage.service.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/M

#2063 fix: Api Service V2
  src/app/core/models/corporate-card-expense-unflattened.model.ts
  src/app/core/models/matchedCCCTransaction.model.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/advance.service.ts
  src/app/core/services/api-v2.service.spec.ts
  src/app/core/services/api-v2.service.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/core/services/org-user.service.ts
  src/app/core/services/personal-cards.service.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/tasks.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
Labels: size/M

#2091 fix: Advance Request Policy Service
  src/app/core/mock-data/advance-requests.data.ts
  src/app/core/services/advance-request-policy.service.spec.ts
  src/app/core/services/advance-request-policy.service.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.spec.ts
Labels: size/M

#2093 fix: Currency Service
  src/app/core/services/currency.service.ts
Labels: size/XS

#2095 fix: Advance Request Service
  src/app/core/services/advance-request.service.ts
Labels: size/XS

#2094 fix: Auth Service
  src/app/core/services/auth.service.ts
Labels: size/XS

#2024 test: Code Coverage: Switch Org Component
  src/app/auth/switch-org/switch-org.page.html
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/mock-data/org.data.ts
Labels: size/XL

#2096 fix: Advance Service
  src/app/core/models/text-search-params.model.ts
  src/app/core/models/text-search-query.model.ts
  src/app/core/services/advance.service.ts
Labels: size/XS

#2099 fix: Corporate Credit Card Service Types
  src/app/core/services/corporate-credit-card-expense.service.ts
Labels: size/S

#2106 fix: Dependent Fields Service
  src/app/core/services/dependent-fields.service.ts
Labels: size/S

#2108 feat: Add eslint rules
  .eslintrc.json
Labels: size/XS

#2082 feat: Optimized debounce in fy-location modal
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
Labels: size/XS

#2084 feat: Implemented caching in location and gmaps service
  src/app/app.component.ts
  src/app/core/services/gmaps.service.ts
  src/app/core/services/location.service.ts
  src/main.ts
Labels: size/S

#2072 test: Code coverage View Mileage
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
Labels: size/L

#2110 fix: User Service and Storage Service
  src/app/core/services/storage.service.ts
  src/app/core/services/user.service.ts
Labels: size/XS

#2109 fix: added types Google Auth Service
  src/app/core/services/google-auth.service.ts
Labels: size/XS

#2097 fix: App Version Service
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/core/services/app-version.service.ts
Labels: size/S

#2098 fix: Account Service Types
  src/app/core/models/flattened-account.model.ts
  src/app/core/services/accounts.service.ts
Labels: size/S

#2104 fix: User Event Service
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/user-event.service.ts
Labels: size/XS

#2103 fix: Tasks Service
  src/app/core/services/tasks.service.ts
  src/app/core/services/transaction.service.ts
  src/app/shared/components/fy-filters/selected-filters.interface.ts
Labels: size/S

#2105 fix: Split Expense Service
  src/app/core/models/expense.model.ts
  src/app/core/models/file-obj.model.ts
  src/app/core/services/split-expense.service.ts
Labels: size/S

#2087 test: Unit tests for route visualizer component
  src/app/core/mock-data/directions-results.data.ts
  src/app/core/mock-data/mileage-location.data.ts
  src/app/core/mock-data/static-map-properties.data.ts
  src/app/core/services/static-map-properties.service.spec.ts
  src/app/shared/components/route-visualizer/route-visualizer.component.spec.ts
Labels: size/L

#2085 feat: Implement static maps in add/edit mileage
  src/app/core/mock-data/directions-results.data.ts
  src/app/core/mock-data/mileage-location.data.ts
  src/app/core/mock-data/static-map-properties.data.ts
  src/app/core/models/mileage-marker-params.interface.ts
  src/app/core/models/static-map-properties.interface.ts
  src/app/core/services/gmaps.service.ts
  src/app/core/services/location.service.ts
  src/app/core/services/static-map-properties.service.spec.ts
  src/app/core/services/static-map-properties.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/shared/components/route-visualizer/mileage-locations.interface.ts
  src/app/shared/components/route-visualizer/mileage-route.interface.ts
  src/app/shared/components/route-visualizer/route-visualizer.component.html
  src/app/shared/components/route-visualizer/route-visualizer.component.scss
  src/app/shared/components/route-visualizer/route-visualizer.component.spec.ts
  src/app/shared/components/route-visualizer/route-visualizer.component.ts
Labels: size/L

#2119 feat: Use mileage map attachment in the view mileage page
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.scss
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.html
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.ts
  src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.html
  src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts
Labels: size/M

#2116 fix: added types for Location service
  src/app/core/mock-data/location.data.ts
  src/app/core/models/location.model.ts
  src/app/core/services/location.service.spec.ts
  src/app/core/services/location.service.ts
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.spec.ts
Labels: size/L

#2117 fix: Org Service
  src/app/core/services/org.service.ts
Labels: size/XS

#2114 fix: Timezone Service Types
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/services/timezone.service.spec.ts
  src/app/core/services/timezone.service.ts
  src/app/core/services/utility.service.ts
Labels: size/M

#2101 fix: Bank Account Cards Component
  src/app/shared/components/bank-account-cards/bank-account-cards.component.spec.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.ts
Labels: size/XS

#2124 test: code coverage Split Expense Page #1
  src/app/core/mock-data/expense-field-obj.data.ts
  src/app/core/mock-data/public-policy-expense.data.ts
  src/app/core/mock-data/split-expense-data.ts
  src/app/core/models/split-expense.model.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
Labels: size/L

#2125 fix: added types Filters Helper Service
  src/app/core/services/filters-helper.service.spec.ts
  src/app/core/services/filters-helper.service.ts
Labels: size/M

#2129 fix: Mock data was getting manipulated in setup-account-preference
  src/app/post-verification/setup-account-preferences/setup-account-preferences.page.spec.ts
Labels: size/XS

#2118 feat: Loading google maps api in javascript to avoid exposing the key
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/core/services/gmaps.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/index.html
Labels: size/M

#2132 fix: Check if projects is enabled before auto filling
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#2128 fix: File Size Limit BR
  src/app/core/constants.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.ts
Labels: size/S

#2134 fix: Zero state overlap with input in ios
  src/app/fyle/my-create-report/my-create-report.page.html
Labels: size/XS

#2131 feat: Show project mapped categories in split expense page using LD flag
  src/app/core/test-data/projects.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/L

#2123 test: Code Coverage: Add-Edit Expense Page #1
  src/app/core/mock-data/cost-centers.data.ts
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XL

#2139 fix: Show tax amount as 0 when user selects 0% tax group
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#2120 test: 100% Coverage of My Reports Page
  src/app/core/mock-data/my-reports-filterpills.data.ts
  src/app/core/mock-data/my-reports-filters.data.ts
  src/app/core/mock-data/my-reports-load-data.data.ts
  src/app/core/mock-data/my-reports.data.ts
  src/app/core/mock-data/selected-filters.data.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
Labels: size/XL

#2092 test: 42% coverage of my-reports page
  src/app/core/mock-data/card-aggregate-stat.data.ts
  src/app/core/mock-data/my-reports-filterpills.data.ts
  src/app/core/mock-data/my-reports-filters.data.ts
  src/app/core/mock-data/my-reports-load-data.data.ts
  src/app/core/mock-data/my-reports.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/selected-filters.data.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/my-expenses/my-expenses-filters.model.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
Labels: size/XL

#2141 fix: Add File Size Check in Expense Card Component
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/S

#2138 fix: Consistency of redirectionText
  src/app/core/models/snackbar-properties.model.ts
  src/app/core/services/snackbar-properties.service.spec.ts
  src/app/core/services/snackbar-properties.service.ts
Labels: size/XS

#2135 feat: Add trackers for #sms_to_submit_receipt
  src/app/core/services/tracking.service.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/XS

#2149 test: 100% coverage of Split expense service
  src/app/core/mock-data/transaction.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
Labels: size/L

#2126 test: Code Coverage: Add Edit Expense Page #2
  src/app/core/mock-data/action-sheet-options.data.ts
  src/app/core/mock-data/modal-properties.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/popover-params.data.ts
  src/app/core/mock-data/undo-merge.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XL

#2150 fix: typo in destroy method
  src/app/app.component.ts
  src/app/core/models/fresh-chat-widget.model.ts
  src/app/core/services/fresh-chat.service.ts
Labels: size/M

#2130 test: code coverage 30% Split Expense Page #2
  src/app/core/mock-data/file-object.data.ts
  src/app/core/mock-data/file-txn.data.ts
  src/app/core/mock-data/org-category-list-item.data.ts
  src/app/core/mock-data/recently-used.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/models/file-txn.model.ts
  src/app/core/services/recently-used-items.service.spec.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/XL

#2146 fix: Draft State Header in Report View Page
  src/app/fyle/my-view-report/my-view-report.page.html
Labels: size/XS

#2154 Revert "test: Code Coverage: Add Edit Expense Page #2"
  src/app/core/mock-data/action-sheet-options.data.ts
  src/app/core/mock-data/modal-properties.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/popover-params.data.ts
  src/app/core/mock-data/undo-merge.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XL

#2121 test: 49% coverage of my-expense page
  src/app/core/dom-helpers.ts
  src/app/core/mock-data/action-sheet-options.data.ts
  src/app/core/mock-data/card-aggregate-stats.data.ts
  src/app/core/mock-data/card-details.data.ts
  src/app/core/mock-data/expense-filters.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/filter-pills.data.ts
  src/app/core/mock-data/unformatted-transaction.data.ts
  src/app/core/models/card-aggregate-stats.model.ts
  src/app/core/models/card-details.model.ts
  src/app/core/models/ccc-expense-details.model.ts
  src/app/core/models/unformatted-transaction.model.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/core/services/platform-handler.service.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/dashboard/dashboard.service.ts
  src/app/fyle/dashboard/stats/stats.component.ts
  src/app/fyle/my-expenses/expense-filters.model.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-expenses/my-expenses.service.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
Labels: size/XL

#2143 test: 87% code coverage of My expense
  src/app/core/mock-data/critical-policy-violation-popover.data.ts
  src/app/core/mock-data/filter-pills.data.ts
  src/app/core/mock-data/get-expenses-query-params-with-filters.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/snackbar-properties.data.ts
  src/app/core/models/get-expenses-query-params-with-filters.model.ts
  src/app/core/models/get-expenses-query-params.model.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XL

#2144 test: 100% coverage of My expense
  src/app/core/mock-data/snackbar-properties.data.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/L

#2153 fix: strandhogg - FLAG_ACTIVITY_NEW_TASK
  hooks/prebuild.js
Labels: size/XS

#2152 test: 40% Tasks component coverage
  src/app/core/mock-data/dashboard-task.data.ts
  src/app/core/mock-data/filter-pills.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/selected-filters.data.ts
  src/app/core/mock-data/task-cta.data.ts
  src/app/core/mock-data/task-filters.data.ts
  src/app/core/models/dashboard-task.model.ts
  src/app/core/models/task-dictionary.model.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks-1.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
Labels: size/XL

#2156 Fix add edit exp 2
  src/app/core/mock-data/action-sheet-options.data.ts
  src/app/core/mock-data/modal-properties.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/popover-params.data.ts
  src/app/core/mock-data/undo-merge.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XL

#2161 test: Code Coverage: Add Edit Expense #3 2nd Spec File
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XL

#2160 test: Code Coverage: Add Edit Expense #3 1st Spec File
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XL

#2159 test: Code Coverage: Add Edit Expense #3 Base
  src/app/core/mock-data/parsed-receipt.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XL

#2148 test: code coverage 70% Split Expense Page
  src/app/core/mock-data/file-object.data.ts
  src/app/core/mock-data/file-txn.data.ts
  src/app/core/mock-data/split-expense-data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
Labels: size/XL

#2157 test: 40% coverage of team reports page
  src/app/core/mock-data/api-params.data.ts
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/get-tasks-query-params.data.ts
  src/app/core/models/get-tasks-query-params-with-filters.model.ts
  src/app/core/models/get-tasks.query-params.model.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports-2.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
Labels: size/XL

#2140 test: code coverage 50% split expense page
  src/app/core/mock-data/data-transform.data.ts
  src/app/core/mock-data/file-object.data.ts
  src/app/core/mock-data/file-txn.data.ts
  src/app/core/mock-data/split-expense-data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/models/extended-account.model.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
Labels: size/XL
