Repository fylein/fyle-mobile-app, pull requests merged in 2023-09, with the labels that each got.

#2341 fix: Error in mat-chip in angular material
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.html
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.scss
  src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.html
  src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.scss
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.html
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.scss
  src/assets/styles/_fy_select.scss
  src/global.scss
Labels: size/M

#2349 test: 30% coverage of view-per-diem page
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
Labels: size/M

#2348 test: 20% coverage of view-per-diem page
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
Labels: size/L

#2336 test: remaining branches coverage in per-diem page
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/L

#2332 test: 93% coverage of per-diem page
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.ts
Labels: size/XL

#2338 test: Android negative fix test
  src/app/shared/components/fy-number/fy-number.component.spec.ts
  src/app/shared/components/fy-number/fy-number.component.ts
Labels: size/S

#2324 fix: Android user (Samsung) not able to enter negative expense
  src/app/core/services/launch-darkly.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/shared/components/fy-number/fy-number.component.html
  src/app/shared/components/fy-number/fy-number.component.spec.ts
  src/app/shared/components/fy-number/fy-number.component.ts
  src/app/shared/components/route-selector/route-selector.component.html
Labels: size/M

#2334 test: Code Coverage: Add Edit Mileage: #8 Part 2
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/L

#2333 test: Code Coverage: Add Edit Mileage: #8 Part 1
  src/app/core/mock-data/cost-centers.data.ts
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
Labels: size/XL

#2353 fix: Fixed category custom fields not loading up on incomplete expenses
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#2331 test: Code Coverage: Add Edit Mileage: #7 Part 3
  src/app/core/mock-data/cost-centers.data.ts
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
Labels: size/XL

#2330 test: Code Coverage: Add Edit Mileage: #7 Part 2
  src/app/core/mock-data/cost-centers.data.ts
  src/app/core/mock-data/expense-field-obj.data.ts
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
Labels: size/XL

#2329 test: Code Coverage: Add Edit Mileage: #7 Part 1
  src/app/core/mock-data/cost-centers.data.ts
  src/app/core/mock-data/custom-property.data.ts
  src/app/core/mock-data/expense-field-obj.data.ts
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/txn-custom-properties.model.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
Labels: size/XL

#2328 test: Code Coverage: Add Edit Mileage: #6 Part 2
  src/app/core/mock-data/cost-centers.data.ts
  src/app/core/mock-data/custom-property.data.ts
  src/app/core/mock-data/expense-field-obj.data.ts
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/txn-custom-properties.model.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
Labels: size/XL

#2317 test: Code Coverage: Add Edit Mileage: #6 Part 1
  capacitor.config.ts
  package-lock.json
  src/app/core/mock-data/cost-centers.data.ts
  src/app/core/mock-data/custom-property.data.ts
  src/app/core/mock-data/expense-field-obj.data.ts
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/txn-custom-properties.model.ts
  src/app/core/services/launch-darkly.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
Labels: size/XL

#2356 fix: extra space in distance field below input
  src/app/shared/components/route-selector/route-selector.component.html
  src/app/shared/components/route-selector/route-selector.component.scss
Labels: size/XS

#2359 fix: Revert "test: Code Coverage: Add Edit Mileage: #6 Part 1 "
  capacitor.config.ts
  package-lock.json
  src/app/core/mock-data/cost-centers.data.ts
  src/app/core/mock-data/custom-property.data.ts
  src/app/core/mock-data/expense-field-obj.data.ts
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/txn-custom-properties.model.ts
  src/app/core/services/launch-darkly.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
Labels: size/XL

#2362 fix: Re-applying reverted add-edit-mileage
  package-lock.json
  src/app/core/mock-data/cost-centers.data.ts
  src/app/core/mock-data/custom-property.data.ts
  src/app/core/mock-data/expense-field-obj.data.ts
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/txn-custom-properties.model.ts
  src/app/core/services/launch-darkly.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
Labels: size/XL

#2368 fix: mat-form-field clear icon size
  src/assets/styles/_fy_select.scss
Labels: size/XS

#2370 fix: The cross button should be right aligned inside the input box
  src/app/fyle/my-expenses/my-expenses.page.scss
  src/app/fyle/my-reports/my-reports.page.scss
  src/app/fyle/personal-cards/personal-cards.page.scss
  src/app/fyle/team-reports/team-reports.page.scss
Labels: size/XS

#2371 test: 70% coverage of task component
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
Labels: size/M

#2369 test: 54% coverage of task component
  src/app/core/mock-data/task-cta.data.ts
  src/app/core/mock-data/task-filters.data.ts
  src/app/fyle/dashboard/tasks/tasks-1.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
Labels: size/L

#2366 test: 99.2% coverage of view-per-diem page
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/M

#2360 test: ionViewWillEnter Part 2 coverage
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/L

#2367 fix: eslint fix in task component
  src/app/core/mock-data/task-cta.data.ts
  src/app/core/mock-data/task-filters.data.ts
  src/app/fyle/dashboard/tasks/tasks-1.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
Labels: size/L

#2355 test: ionViewWillEnter Part 1 coverage
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/L

#2352 test: Code Coverage: My Create Report: #3
  src/app/core/mock-data/expense.data.ts
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
Labels: size/L

#2350 test: Code Coverage: My Create Report #2
  src/app/core/mock-data/expense.data.ts
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
Labels: size/L

#2347 test: Code Coverage: My Create Report #1
  src/app/core/mock-data/expense.data.ts
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
Labels: size/L

#2374 test: 88% coverage of task component
  src/app/core/mock-data/etxn-params.data.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
Labels: size/M

#2376 test: 80% coverage of task component
  src/app/core/mock-data/etxn-params.data.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
Labels: size/L

#2281 test: Added tests for manage corporate cards page
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
Labels: size/L

#2344 test: Added tests for card stats component
  src/app/core/mock-data/ccc-expense.details.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/platform-corporate-card-detail-data.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
Labels: size/L

#2345 fix: Unified card enrollment ios bug fixes
  src/app/fyle/dashboard/card-stats/card-stats.component.scss
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/tasks/tasks.component.scss
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.html
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.scss
  src/app/fyle/manage-corporate-cards/card-added/card-added.component.scss
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/app/shared/components/add-card/add-card.component.scss
Labels: size/M

#2372 fix: Unified card enrollment QA fixes
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/dashboard/dashboard.module.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.html
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.scss
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.module.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/add-card/add-card.component.scss
  src/app/shared/components/corporate-card/corporate-card.component.html
  src/assets/images/mastercard-logo.png
  src/assets/images/visa-logo.png
  src/assets/svg/arrow-down-primary.svg
  src/assets/svg/arrow-up-primary.svg
  src/assets/svg/mastercard-logo.svg
  src/assets/svg/visa-logo.svg
Labels: size/L

#2383 test: Code Coverage: My Profile Page #3
  src/app/fyle/my-profile/my-profile.page.spec.ts
Labels: size/M

#2382 test: Code Coverage: My Profile Page #2 Adding New Tests
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/models/copy-card-details.model.ts
  src/app/core/models/event-data.model.ts
  src/app/core/models/preference-setting.model.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/L

#2381 test: Code Coverage: My Profile Page #1 Fixing Existing Tests
  src/app/core/mock-data/extended-org-user.data.ts
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/models/copy-card-details.model.ts
  src/app/core/models/event-data.model.ts
  src/app/core/models/preference-setting.model.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/L

#2379 fix: My Profile Page Lint
  src/app/core/mock-data/extended-org-user.data.ts
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/models/copy-card-details.model.ts
  src/app/core/models/event-data.model.ts
  src/app/core/models/preference-setting.model.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/L

#2398 test: Unified card enrollment flow remaining branches code coverage
  src/app/core/mock-data/ccc-expense.details.data.ts
  src/app/core/mock-data/platform-corporate-card-detail-data.ts
  src/app/core/mock-data/platform-corporate-card.data.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/real-time-feed.service.spec.ts
  src/app/core/services/real-time-feed.service.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
Labels: size/M

#2342 test: Code Coverage: Add Edit Mileage: #9: Part 1
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/extended-account.data.ts
  src/app/core/mock-data/mileage-rate.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/mock-data/platform-mileage-rate.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/mileage-rates-options.data.ts
  src/app/core/services/mileage-rates.service.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/L

#2339 test: Code Coverage: Add Edit Mileage: #8 Part 3
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/extended-account.data.ts
  src/app/core/mock-data/mileage-rate.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/mock-data/platform-mileage-rate.data.ts
  src/app/core/mock-data/recently-used.data.ts
  src/app/core/mock-data/report-options.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/mileage-rates-options.data.ts
  src/app/core/services/mileage-rates.service.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/XL

#2396 test: 100% coverage of dashboard page
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
Labels: size/M

#2395 test: 77% coverage of dashboard page
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
Labels: size/S

#2394 test: 66% coverage of dashboard page
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
Labels: size/M

#2393 test: 31% coverage of dashboard page
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
Labels: size/L

#2385 fix: Dashboard page lint
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
Labels: size/L

#2407 test: 30% coverage of my advances page
  src/app/fyle/my-advances/my-advances.page.html
  src/app/fyle/my-advances/my-advances.page.spec.ts
  src/app/fyle/my-advances/my-advances.page.ts
Labels: size/M

#2412 test: remaining coverage of fy-input-popover comp
  src/app/shared/components/fy-input-popover/fy-input-popover.component.spec.ts
Labels: size/M

#2417 test: Http Interceptor #2
  src/app/core/interceptors/httpInterceptor.spec.ts
  src/app/core/interceptors/httpInterceptor.ts
  src/app/core/mock-data/extended-device-info.data.ts
Labels: size/M

#2408 test: Code Coverage : HTTP Interceptor #1
  src/app/core/interceptors/httpInterceptor.spec.ts
  src/app/core/interceptors/httpInterceptor.ts
  src/app/core/mock-data/extended-device-info.data.ts
Labels: size/M, size/L

#2405 fix: HttpInterceptor Linting
  src/app/core/interceptors/httpInterceptor.spec.ts
  src/app/core/interceptors/httpInterceptor.ts
  src/app/core/mock-data/extended-device-info.data.ts
Labels: size/L

#2404 test: Code Coverage: Personal Cards Page #5
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/L

#2403 test: Code Coverage: Personal Cards Page #4
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/L

#2402 test: Code Coverage: Personal Cards Page #3
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/L

#2400 test: Code Coverage: Personal Cards Page #2
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/mock-data/snackbar-properties.data.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/XL

#2392 test: Code Coverage: Personal Cards #1
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/mock-data/snackbar-properties.data.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/XL

#2364 fix: Personal Card Page Linting
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/mock-data/snackbar-properties.data.ts
  src/app/core/models/personal_card_txn.model.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/XL

#2411 test: 100% coverage of my-advances page
  src/app/core/mock-data/filter-options.data.ts
  src/app/fyle/my-advances/my-advances.page.spec.ts
Labels: size/M

#2410 test: 80% coverage of my advances page
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/mock-data/filter-options.data.ts
  src/app/core/models/extended_advance.model.ts
  src/app/fyle/my-advances/my-advances.page.spec.ts
  src/app/fyle/my-advances/my-advances.page.ts
Labels: size/L

#2409 test: 68% coverage of my advances page
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/mock-data/filter-options.data.ts
  src/app/core/mock-data/my-advances-filters.data.ts
  src/app/core/models/extended_advance.model.ts
  src/app/core/models/my-advances-filters.model.ts
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/my-advances/my-advances.page.spec.ts
  src/app/fyle/my-advances/my-advances.page.ts
Labels: size/L

#2415 test: 100% coverage of add-to-report component
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/report-options.data.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.spec.ts
Labels: size/M

#2416 test: 30% coverage of fy-add-to-report comp
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/report-options.data.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.spec.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
Labels: size/L

#2421 fix: Personal Cards Error
  src/app/fyle/personal-cards/personal-cards.page.html
Labels: size/XS

#2420 fix: minor test bug fix which was modifying the actual data
  src/app/fyle/my-profile/my-profile.page.spec.ts
Labels: size/XS

#2419 test: 100% coverage of camera-overlay page
  src/app/fyle/camera-overlay/camera-overlay.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
Labels: size/M

#2423 test: 100% coverage of format-date directive
  src/app/shared/directive/format-date.directive.spec.ts
Labels: size/M

#2399 feat: Added trackers for unified card enrollment flow
  src/app/core/mock-data/corporate-card-trackers.data.ts
  src/app/core/models/tracking-properties.model.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.spec.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
Labels: size/L

#2418 fix: Unified card enrollment QA (Part 3)
  src/app/core/services/launch-darkly.service.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.html
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/app/shared/components/spent-cards/spent-cards.component.html
  src/global.scss
Labels: size/M

#2435 fix: Image picker
  android/variables.gradle
  package-lock.json
  package.json
Labels: size/XS

#2424 test: Code Coverage: Camera Options Popup Component #1
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.html
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.spec.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.ts
Labels: size/M

#2422 fix: Add-Edit-Expense / Camera-Options-Popup Component Linting
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.html
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.spec.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.ts
Labels: size/M

#2428 test: removed fy-preview-attachments component as it is unused
  src/app/shared/components/fy-preview-attachments/fy-preview-attachments.component.html
  src/app/shared/components/fy-preview-attachments/fy-preview-attachments.component.scss
  src/app/shared/components/fy-preview-attachments/fy-preview-attachments.component.spec.ts
  src/app/shared/components/fy-preview-attachments/fy-preview-attachments.component.ts
  src/app/shared/shared.module.ts
Labels: size/L

#2430 test: 100% coverage of verified org auth guard
  src/app/core/guards/verified-org-auth.guard.spec.ts
  src/app/core/mock-data/extended-org-user.data.ts
  src/app/core/mock-data/router-state-snapshot.data.ts
Labels: size/M

#2440 test: 100% coverage of virtual-select-modal
  src/app/core/mock-data/virtual-select-option.data.ts
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.spec.ts
Labels: size/M

#2436 test: 70% coverage of Virtual select modal
  src/app/core/mock-data/virtual-select-option.data.ts
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.spec.ts
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.ts
Labels: size/L

#2443 test: Code Coverage: Potenital Duplicates
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/core/mock-data/snackbar-properties.data.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.html
  src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.ts
Labels: size/L

#2427 test: Code Coverage: My-Profile/ Select Currency #1
  src/app/core/mock-data/currency.data.ts
  src/app/fyle/my-profile/select-currency/select-currency.component.spec.ts
  src/app/fyle/my-profile/select-currency/select-currency.component.ts
Labels: size/M

#2426 fix: Select Currency Linting
  src/app/core/mock-data/currency.data.ts
  src/app/fyle/my-profile/select-currency/select-currency.component.spec.ts
  src/app/fyle/my-profile/select-currency/select-currency.component.ts
Labels: size/M

#2425 fix: Removing Unused Component
  src/app/fyle/add-edit-mileage/add-edit-mileage.module.ts
  src/app/fyle/add-edit-mileage/fy-select-vehicle/fy-select-vehicle.component.html
  src/app/fyle/add-edit-mileage/fy-select-vehicle/fy-select-vehicle.component.scss
  src/app/fyle/add-edit-mileage/fy-select-vehicle/fy-select-vehicle.component.spec.ts
  src/app/fyle/add-edit-mileage/fy-select-vehicle/fy-select-vehicle.component.ts
Labels: size/M

#2439 fix: Potential Duplicates Linting
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/core/mock-data/snackbar-properties.data.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.html
  src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.ts
Labels: size/L

#2445 test: Code Coverage: Auth Guard
  src/app/core/guards/auth.guard.spec.ts
Labels: size/M

#2434 test: Code Coverage: Delegated Accounts Page
  src/app/fyle/delegated-accounts/delegated-accounts.page.spec.ts
Labels: size/M

#2429 fix: Delegated Accounts Linting
  src/app/fyle/delegated-accounts/delegated-accounts.page.spec.ts
  src/app/fyle/delegated-accounts/delegated-accounts.page.ts
Labels: size/M

#2454 fix: ios upgrade
  ios/App/Podfile
  ios/App/Podfile.lock
Labels: size/L

#2447 test: 100% coverage of stats component
  src/app/fyle/dashboard/stats/stats.component.spec.ts
Labels: size/M

#2446 test: 80% coverage of stats component
  src/app/fyle/dashboard/stats/stats.component.spec.ts
Labels: size/M

#2444 test: 48% coverage of stats component
  src/app/core/mock-data/report-stats-data.data.ts
  src/app/core/models/report-stats-data.model.ts
  src/app/fyle/dashboard/stats/stats.component.spec.ts
  src/app/fyle/dashboard/stats/stats.component.ts
Labels: size/L

#2462 test: Code Coverage: Team Advances
  src/app/core/mock-data/expense-field.data.ts
  src/app/fyle/team-advance/team-advance.page.spec.ts
  src/app/fyle/team-advance/team-advance.page.ts
Labels: size/L

#2452 fix: Team Advances Lint
  src/app/core/mock-data/expense-field.data.ts
  src/app/fyle/team-advance/team-advance.page.spec.ts
  src/app/fyle/team-advance/team-advance.page.ts
Labels: size/L

#2455 test: 100% coverage of generic-fields-form
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.spec.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
Labels: size/M

#2460 test: 12% coverage of add-edit-advance-request page
  src/app/core/mock-data/add-edit-advance-request-form-value.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-1.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.setup.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
Labels: size/L

#2453 test: 100% coverage of custom-inputs-fields-form
  src/app/core/mock-data/custom-inputs-field.data.ts
  src/app/core/models/custom-inputs-field.model.ts
  src/app/fyle/merge-expense/custom-inputs-fields-form/custom-inputs-fields-form.component.spec.ts
  src/app/fyle/merge-expense/custom-inputs-fields-form/custom-inputs-fields-form.component.ts
Labels: size/M

#2450 test: 100% coverage of category-dependent-field-form
  src/app/fyle/merge-expense/category-dependent-fields-form/category-dependent-fields-form.component.spec.ts
  src/app/fyle/merge-expense/category-dependent-fields-form/category-dependent-fields-form.component.ts
Labels: size/M

#2456 feat: Show alert in the expense form if category is mandatory and no category is allowed
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/L
