Repository fylein/fyle-mobile-app, pull requests merged in 2023-08, with the labels that each got.

#2215 fix: bug fix for recently accessed category getting repeated
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.ts
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-option.interface.ts
Labels: size/M

#2216 feat: Added manage corporate cards cta in my profile page
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/M

#2218 fix: eslint issues in report, transaction and other services, continued from base branch
  src/app/core/mock-data/my-reports.data.ts
  src/app/core/mock-data/outbox-queue.data.ts
  src/app/core/mock-data/stats-response.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/delete-popover-params.model.ts
  src/app/core/models/expense-delete-popover-params.model.ts
  src/app/core/models/expense.model.ts
  src/app/core/models/filter-query-params.model.ts
  src/app/core/models/get-expenses-query-params-with-filters.model.ts
  src/app/core/models/get-expenses-query-params.model.ts
  src/app/core/models/outbox-queue.model.ts
  src/app/core/models/parsed_response.model.ts
  src/app/core/models/report-permission.model.ts
  src/app/core/models/report-state-map.model.ts
  src/app/core/models/report-stats-response.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/models/v2/stats-response.model.ts
  src/app/core/services/report.service.ts
  src/app/core/services/tasks.service.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.spec.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/shared/components/create-new-report/create-new-report.component.spec.ts
Labels: size/XL

#2214 fix: bug fixes in merge-expense
  src/app/core/models/category-dependent-fields-form-values.model.ts
  src/app/core/models/category-dependent-fields-options.model.ts
  src/app/core/models/custom-fields-form-values.model.ts
  src/app/core/models/generic-fields-form-values.model.ts
  src/app/core/models/generic-fields-options.model.ts
  src/app/fyle/merge-expense/merge-expense-3.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/L

#2233 fix: passed empty params to onViewCommentsClick
  src/app/fyle/my-reports/my-reports.page.html
Labels: size/XS

#2234 fix: transaction stats api call overriding other properties on select…
  src/app/core/models/filter-query-params.model.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XS

#2217 fix: Negative expense for ios users
  src/app/core/services/launch-darkly.service.spec.ts
  src/app/core/services/launch-darkly.service.ts
  src/app/shared/components/fy-currency/fy-currency.component.html
  src/app/shared/components/fy-number/fy-number.component.html
  src/app/shared/components/fy-number/fy-number.component.spec.ts
  src/app/shared/components/fy-number/fy-number.component.ts
Labels: size/M

#2235 test: 78% coverage of split-expense
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
Labels: size/M

#2246 fix: Split expense lint fix
  src/app/core/enums/toast-type.enum.ts
  src/app/core/mock-data/currency-obj.data.ts
  src/app/core/mock-data/split-expense-data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/models/file-txn.model.ts
  src/app/core/models/split-expense-form.model.ts
  src/app/core/models/split-expense.model.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/L

#2242 test: 100% coverage of split expense page
  src/app/core/enums/toast-type.enum.ts
  src/app/core/mock-data/currency-obj.data.ts
  src/app/core/mock-data/split-expense-data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/models/file-txn.model.ts
  src/app/core/models/split-expense-form.model.ts
  src/app/core/models/split-expense.model.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/L

#2241 test: 96% coverage of split expense
  src/app/core/enums/toast-type.enum.ts
  src/app/core/mock-data/corporate-card-expense-unflattened.data.ts
  src/app/core/mock-data/currency-obj.data.ts
  src/app/core/mock-data/matchedCCCTransaction.data.ts
  src/app/core/mock-data/split-expense-data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/models/corporate-card-expense-unflattened.model.ts
  src/app/core/models/file-txn.model.ts
  src/app/core/models/matchedCCCTransaction.model.ts
  src/app/core/models/split-expense-form.model.ts
  src/app/core/models/split-expense.model.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/merge-expense/card-transaction-preview/card-transaction-preview.component.spec.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/L

#2213 test: Code Coverage: Add Edit Expense #11
  src/app/core/mock-data/corporate-card-expense-unflattened.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/parsed-receipt.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/corporate-card-expense-unflattened.model.ts
  src/app/core/models/org-user.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XL

#2211 test: Code Coverage: Add Edit Expense #10
  src/app/core/mock-data/corporate-card-expense-unflattened.data.ts
  src/app/core/mock-data/expense-policy.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/parsed-receipt.data.ts
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/corporate-card-expense-unflattened.model.ts
  src/app/core/models/insta-fyle-data.model.ts
  src/app/core/models/org-user.model.ts
  src/app/core/models/parsed_receipt.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XL

#2201 test: Code Coverage: Add Edit Expense #9
  src/app/core/mock-data/corporate-card-expense-unflattened.data.ts
  src/app/core/mock-data/custom-input.data.ts
  src/app/core/mock-data/default-txn-field-values.data.ts
  src/app/core/mock-data/expense-field-obj.data.ts
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/expense-fields-map.data.ts
  src/app/core/mock-data/expense-policy.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/parsed-receipt.data.ts
  src/app/core/mock-data/report-options.data.ts
  src/app/core/mock-data/report-unflattened.data.ts
  src/app/core/mock-data/tax-group.data.ts
  src/app/core/mock-data/tax-settings.data.ts
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/corporate-card-expense-unflattened.model.ts
  src/app/core/models/file-obj.model.ts
  src/app/core/models/insta-fyle-data.model.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/org-user.model.ts
  src/app/core/models/parsed_receipt.model.ts
  src/app/core/models/report-options.model.ts
  src/app/core/models/unflattened-transaction.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/test-data/custom-inputs.spec.data.ts
  src/app/core/test-data/dependent-fields.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XL

#2236 test: 82% coverage of split expense
  src/app/core/enums/toast-type.enum.ts
  src/app/core/mock-data/corporate-card-expense-unflattened.data.ts
  src/app/core/mock-data/currency-obj.data.ts
  src/app/core/mock-data/matchedCCCTransaction.data.ts
  src/app/core/mock-data/split-expense-data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/models/corporate-card-expense-unflattened.model.ts
  src/app/core/models/currency-obj.model.ts
  src/app/core/models/file-txn.model.ts
  src/app/core/models/matchedCCCTransaction.model.ts
  src/app/core/models/split-expense-form.model.ts
  src/app/core/models/split-expense.model.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/merge-expense/card-transaction-preview/card-transaction-preview.component.spec.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/XL

#2222 feat: Added manage corporate cards page and corporate card component
  src/app/core/enums/data-feed-source.enum.ts
  src/app/core/mock-data/platform-corporate-card.data.ts
  src/app/core/models/platform/platform-corporate-card.model.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/fyle-routing.module.ts
  src/app/fyle/manage-corporate-cards/corporate-card/corporate-card.component.html
  src/app/fyle/manage-corporate-cards/corporate-card/corporate-card.component.scss
  src/app/fyle/manage-corporate-cards/corporate-card/corporate-card.component.spec.ts
  src/app/fyle/manage-corporate-cards/corporate-card/corporate-card.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards-routing.module.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.module.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/shared/components/card-number/card-number.component.html
  src/app/shared/components/card-number/card-number.component.scss
  src/app/shared/components/card-number/card-number.component.spec.ts
  src/app/shared/components/card-number/card-number.component.ts
  src/app/shared/shared.module.ts
  src/assets/images/corporate-card-bg.png
  src/assets/svg/mastercard-logo.svg
  src/assets/svg/more.svg
  src/assets/svg/visa-logo.svg
Labels: size/L

#2229 test: Added tests for corporate card component changes
  src/app/core/mock-data/bank-feed-sources.data.ts
  src/app/core/mock-data/platform-corporate-card.data.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/fyle/manage-corporate-cards/corporate-card/corporate-card.component.html
  src/app/fyle/manage-corporate-cards/corporate-card/corporate-card.component.spec.ts
  src/app/shared/components/card-number/card-number.component.html
  src/app/shared/components/card-number/card-number.component.spec.ts
Labels: size/L

#2197 test: Code Coverage: Add Edit Expense #8
  src/app/core/mock-data/corporate-card-expense-unflattened.data.ts
  src/app/core/mock-data/cost-centers.data.ts
  src/app/core/mock-data/custom-input.data.ts
  src/app/core/mock-data/default-txn-field-values.data.ts
  src/app/core/mock-data/expense-field-obj.data.ts
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/expense-fields-map.data.ts
  src/app/core/mock-data/expense-policy.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/mock-data/parsed-receipt.data.ts
  src/app/core/mock-data/report-options.data.ts
  src/app/core/mock-data/tax-group.data.ts
  src/app/core/mock-data/tax-settings.data.ts
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/corporate-card-expense-unflattened.model.ts
  src/app/core/models/file-obj.model.ts
  src/app/core/models/insta-fyle-data.model.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/org-user.model.ts
  src/app/core/models/parsed_receipt.model.ts
  src/app/core/models/report-options.model.ts
  src/app/core/models/unflattened-transaction.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/test-data/custom-inputs.spec.data.ts
  src/app/core/test-data/dependent-fields.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XL

#2252 test: test setup and 10% coverage of add-edit-per-diem page
  src/app/core/mock-data/modal-controller.data.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.spec.ts
Labels: size/XL

#2244 feat: Edit report name - Spender changes
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/mock-data/report.data.ts
  src/app/core/models/platform/platform-report.model.ts
  src/app/core/models/platform/report-approvals.model.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/M

#2254 test: 20% coverage of add-edit-per-diem
  src/app/core/mock-data/default-txn-field-values.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/models/v1/default-txn-field-values.model.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
Labels: size/M

#2243 test: Code Coverage: Add Edit Mileage Refactor
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/XL

#2230 test: Code Coverage: Add Edit Mileage Lint #2
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/services/accounts.service.ts
  src/app/core/services/per-diem.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/XL

#2248 feat: Implemented add card flow designs
  package-lock.json
  package.json
  src/app/core/enums/card-network-type.ts
  src/app/core/services/real-time-feed.service.spec.ts
  src/app/core/services/real-time-feed.service.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.html
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.scss
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.spec.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.ts
  src/app/fyle/manage-corporate-cards/corporate-card/corporate-card.component.html
  src/app/fyle/manage-corporate-cards/corporate-card/corporate-card.component.scss
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.module.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.scss
  src/app/fyle/my-view-advance/my-view-advance.page.scss
  src/app/shared/pipes/array-to-comma-list.pipe.spec.ts
  src/app/shared/pipes/array-to-comma-list.pipe.ts
  src/app/shared/shared.module.ts
  src/assets/svg/arrow-down-primary.svg
  src/assets/svg/mastercard-logo.svg
  src/assets/svg/open-in-new-tab.svg
  src/assets/svg/visa-logo.svg
  src/theme/colors.scss
Labels: size/L

#2250 feat: Add corporate card validation
  src/app/core/models/platform/enroll-card-payload.model.ts
  src/app/core/models/platform/enroll-card-response.model.ts
  src/app/core/models/platform/platform-api-error.model.ts
  src/app/core/models/platform/platform-api-payload.model.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/core/services/real-time-feed.service.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.html
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.scss
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
Labels: size/L

#2251 test: Add corporate card component tests
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.html
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.spec.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.ts
Labels: size/L

#2258 test: Real time feed service and array to comma list pipe tests
  src/app/core/services/real-time-feed.service.spec.ts
  src/app/shared/pipes/array-to-comma-list.pipe.spec.ts
  src/app/shared/pipes/array-to-comma-list.pipe.ts
Labels: size/M

#2228 test: Code Coverage: Add Edit Mileage Lint #1
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/models/cost-center-options.model.ts
  src/app/core/services/accounts.service.ts
  src/app/core/services/mileage-rates.service.ts
  src/app/core/services/per-diem.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/XL

#2256 feat: Add corporate card success dialog
  src/app/fyle/manage-corporate-cards/card-added/card-added.component.html
  src/app/fyle/manage-corporate-cards/card-added/card-added.component.scss
  src/app/fyle/manage-corporate-cards/card-added/card-added.component.spec.ts
  src/app/fyle/manage-corporate-cards/card-added/card-added.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.module.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.spec.ts
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.ts
  src/app/shared/icon/icon.module.ts
  src/assets/svg/tick-circle-outline-white.svg
  src/assets/svg/tick-circle-outline.svg
Labels: size/M

#2262 test: Code Coverage: Add Edit Mileage #1
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
Labels: size/M

#2260 test: Code Coverage: Add Edit Mileage Setup
  src/app/core/services/per-diem.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.spec.ts
Labels: size/L

#2273 feat: Edit report name - History section changes with code coverage
  src/app/core/services/status.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
Labels: size/M

#2264 test: Code Coverage: Add Edit Mileage #2 Part 1
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/M

#2263 test: 23.7% coverage of add-edit-per-diem page
  src/app/core/mock-data/per-diem-custom-inputs.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/models/expense-source.enum.ts
  src/app/core/models/expense-state.enum.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
Labels: size/L

#2245 fix: Default Comment on Policy Violation
  src/app/core/services/per-diem.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
Labels: size/S

#2257 feat: Manage cards empty state shimmers + three dot interactions
  src/app/core/models/platform/unenroll-card-payload.model.ts
  src/app/core/services/real-time-feed.service.spec.ts
  src/app/core/services/real-time-feed.service.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.spec.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/shared/components/add-card/add-card.component.html
  src/app/shared/components/add-card/add-card.component.scss
  src/assets/images/cards.svg
  src/global.scss
Labels: size/L

#2276 feat: Edit report name - Maximum character limit reached changes for Spender+Approver with code coverage
  src/app/fyle/my-view-report/edit-report-name-popover/edit-report-name-popover.component.html
Labels: size/XS

#2271 fix: Per diem lint fix
  src/app/core/mock-data/per-diem-custom-inputs.data.ts
  src/app/core/mock-data/platform-policy-expense.data.ts
  src/app/core/mock-data/public-policy-expense.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/models/per-diem-custom-inputs.model.ts
  src/app/core/models/per-diem-form-values.model.ts
  src/app/core/models/platform/platform-policy-expense.model.ts
  src/app/core/models/public-policy-expense.model.ts
  src/app/core/models/unformatted-transaction.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/policy.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/L

#2268 test: ionViewWillEnter method in add-edit-per-diem method - Part 1
  src/app/core/mock-data/expense-field-obj.data.ts
  src/app/core/mock-data/per-diem-custom-inputs.data.ts
  src/app/core/mock-data/platform-policy-expense.data.ts
  src/app/core/mock-data/public-policy-expense.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/models/per-diem-custom-inputs.model.ts
  src/app/core/models/per-diem-form-values.model.ts
  src/app/core/models/platform/platform-policy-expense.model.ts
  src/app/core/models/public-policy-expense.model.ts
  src/app/core/models/unformatted-transaction.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/policy.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/XL

#2270 test: Code Coverage: Add Edit Mileage #3 Part 2
  src/app/core/mock-data/org-category.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
Labels: size/M

#2255 feat: Edit report name - Approver changes-1
  src/app/core/services/approver-platform-api.service.spec.ts
  src/app/core/services/approver-platform-api.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/spender-platform-v1-api.service.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/L

#2269 test: Code Coverage: Add Edit Mileage #3 Part 1
  src/app/core/mock-data/org-category.data.ts
  src/app/core/services/status.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.ts
Labels: size/L

#2266 test: Code Coverage: Add Edit Mileage #2 Part 2
  src/app/core/mock-data/org-category.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/XL

#2286 test: ionViewWillEnter method in add-per-diem Part 2
  src/app/core/mock-data/allowed-per-diem-rate-options.data.ts
  src/app/core/models/allowed-per-diem-rate-options.model.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/M

#2278 feat: feat: Edit report name - Added mixpanel trackers + Success toast message with code coverage for Approver persona
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/S

#2288 test: ionViewWillEnter method in add-per-diem Part 3
  src/app/core/mock-data/cost-centers.data.ts
  src/app/core/mock-data/currency-obj.data.ts
  src/app/core/mock-data/per-diem-rates.data.ts
  src/app/core/mock-data/per-diem-reports.data.ts
  src/app/core/models/per-diem-reports.model.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/L

#2283 fix: Redirect to disabled page for disabled users while sign in
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/app/core/mock-data/auth-reponse.data.ts
  src/app/core/models/email-exists-response.model.ts
  src/app/core/models/saml-response.model.ts
Labels: size/M

#2274 fix: Default Comment on Policy Violation #2
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/XS

#2292 fix: SDK Version Update
  android/variables.gradle
Labels: size/XS

#2295 test: 60% coverage of add-per-diem page
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/M

#2294 test: ionViewWillEnter method in add-edit-per-diem part 4
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/report-unflattened.data.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/models/transaction-state.enum.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/L

#2296 fix: Dependent Fields And Linting
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.html
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.spec.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.ts
Labels: size/M

#2300 fix: Cost Centers Dependent Fields Not Visible
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.ts
Labels: size/XS

#2287 test: Code Coverage: Add Edit Mileage #3 Part 3
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
Labels: size/M

#2291 test: Code Coverage: Add Edit Mileage Part 4 #1
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/M

#2304 test: Code Coverage: Add Edit Mileage #4 Part 2
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/M

#2299 feat: Refactored card stats section in dashboard
  src/app/fyle/dashboard/card-stats/card-stats.component.html
  src/app/fyle/dashboard/card-stats/card-stats.component.scss
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/dashboard/dashboard.module.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.scss
  src/app/fyle/dashboard/stats/stats.component.ts
Labels: size/L

#2301 feat: Redesigned corporate card swiper in dashboard to latest designs
  src/app/core/mock-data/card-detail-data.ts
  src/app/core/mock-data/card-details.data.ts
  src/app/core/mock-data/platform-corporate-card-detail-data.ts
  src/app/core/models/card-detail.model.ts
  src/app/core/models/card-details.model.ts
  src/app/core/models/platform-corporate-card-detail.model.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.html
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/dashboard/dashboard.service.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.module.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/add-card/add-card.component.html
  src/app/shared/components/corporate-card/corporate-card.component.html
  src/app/shared/components/corporate-card/corporate-card.component.scss
  src/app/shared/components/corporate-card/corporate-card.component.spec.ts
  src/app/shared/components/corporate-card/corporate-card.component.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
  src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
  src/app/shared/components/spent-cards/spent-cards.component.html
  src/app/shared/components/spent-cards/spent-cards.component.scss
  src/app/shared/components/spent-cards/spent-cards.component.spec.ts
  src/app/shared/components/spent-cards/spent-cards.component.ts
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/L

#2302 feat: Add card flow and success dialog in dashboard flow
  src/app/fyle/dashboard/card-stats/card-stats.component.html
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/dashboard/dashboard.module.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.module.ts
  src/app/shared/components/spent-cards/spent-cards.component.html
  src/app/shared/components/spent-cards/spent-cards.component.ts
Labels: size/M

#2305 test: 73% coverage of add-edit-per-diem page
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
Labels: size/L

#2303 test: 70% coverage of add-per-diem
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
Labels: size/L

#2298 test: 64% coverage of per-diem-page
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
Labels: size/XL

#2309 test: Code Coverage: Add Edit Mileage #5 Part 2
  src/app/core/mock-data/default-txn-field-values.data.ts
  src/app/core/mock-data/org-category-list-item.data.ts
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/platform/platform-policy-expense.model.ts
  src/app/core/models/public-policy-expense.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/policy.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
Labels: size/M

#2308 test: Code Coverage: Add Edit Mileage #5 Part 1
  src/app/core/mock-data/default-txn-field-values.data.ts
  src/app/core/mock-data/org-category-list-item.data.ts
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/platform/platform-policy-expense.model.ts
  src/app/core/models/public-policy-expense.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/policy.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/L

#2318 fix: CC Dependent Fields on Initial Load
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#2307 test: 80% coverage of add-edit-per-diem test page - Part 2
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
Labels: size/M

#2306 test: 80% coverage of add-per-diem page - Part 1
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/L

#2310 fix: Unified card enrollment QA (Part 1)
  src/app/fyle/dashboard/card-stats/card-stats.component.html
  src/app/fyle/dashboard/card-stats/card-stats.component.scss
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.scss
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.html
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
  src/app/shared/components/spent-cards/spent-cards.component.html
  src/app/shared/components/spent-cards/spent-cards.component.scss
  src/app/shared/components/spent-cards/spent-cards.component.spec.ts
  src/app/shared/components/spent-cards/spent-cards.component.ts
  src/app/shared/directive/autofocus.directive.spec.ts
  src/app/shared/directive/autofocus.directive.ts
  src/app/shared/shared.module.ts
  src/assets/images/dashboard-bg.png
  src/assets/images/new-background.png
  src/global.scss
Labels: size/L

#2327 test: 90% coverage of per-diem page
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
Labels: size/M

#2326 test: 87% coverage of Per diem page
  src/app/core/models/per-diem-redirected-from.enum.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/L

#2325 test: 85% coverage of per-diem page
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/models/per-diem-redirected-from.enum.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/L

#2219 fix: Compare eslint diff from base branch of PR instead of master
  package.json
Labels: size/XS
