Repository fylein/fyle-mobile-app, pull requests merged in 2023-07, with the labels that each got.

#2162 test: 60% code coverage of team reports page
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/popup.data.ts
  src/app/fyle/team-reports/team-reports-2.page.spec.ts
  src/app/fyle/team-reports/team-reports-3.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.html
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
Labels: size/L

#2167 feat: QA changes for sms to submit receipts
  src/app/core/mock-data/extended-org-user.data.ts
  src/app/core/models/org-user.model.ts
  src/app/core/services/mobile-number-verification.service.ts
  src/app/core/services/snackbar-properties.service.ts
  src/app/core/services/tasks.service.ts
  src/app/core/test-data/tasks.service.spec.data.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.html
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.scss
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
Labels: size/M

#2165 test: Code Coverage: Add Edit Expense Page #5 Part 1
  src/app/core/mock-data/custom-field.data.ts
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XL

#2164 test: Code Coverage: Add Edit Expense Page #4 New
  src/app/core/mock-data/custom-field.data.ts
  src/app/core/mock-data/custom-property.data.ts
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/core/mock-data/file-object.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/mock-data/parsed-receipt.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XL

#2176 fix: Fix button loader
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.scss
  src/app/shared/directive/form-button-validation.directive.ts
Labels: size/XS

#2171 test: 100% coverage of team reports page
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/team-reports-filters.data.ts
  src/app/fyle/team-reports/team-reports-4.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
Labels: size/L

#2170 test: 80% coverage of team reports page
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/selected-filters.data.ts
  src/app/core/mock-data/team-reports-filters.data.ts
  src/app/core/models/team-reports-filters.model.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/team-reports/team-reports-3.page.spec.ts
  src/app/fyle/team-reports/team-reports-4.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
Labels: size/XL

#2175 test: Code Coverage: Add Edit Expense #6 Part 2
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/L

#2181 fix: remove unused icons (.svg) --mobile --part2
  src/assets/svg/fy-team-reports.svg
  src/assets/svg/fy-team-wallet.svg
  src/assets/svg/fy-trash-o.svg
  src/assets/svg/fy-trash.svg
  src/assets/svg/fy-trips-new.svg
  src/assets/svg/fy-user.svg
  src/assets/svg/fy-warning.svg
  src/assets/svg/pdfnew.svg
Labels: size/S

#2180 fix: remove unused icons (.svg) --mobile --part1
  src/assets/svg/expand-arrow.svg
  src/assets/svg/fy-add-receipt.svg
  src/assets/svg/fy-dashboard.svg
  src/assets/svg/fy-dot-small.svg
  src/assets/svg/fy-dropdown.svg
  src/assets/svg/fy-edit.svg
  src/assets/svg/fy-error.svg
  src/assets/svg/fy-flag.svg
  src/assets/svg/fy-plus-gradient.svg
  src/assets/svg/fy-rotate.svg
  src/assets/svg/fy-swap.svg
  src/assets/svg/fy-team-reports.svg
  src/assets/svg/fy-team-wallet.svg
  src/assets/svg/fy-trash-o.svg
  src/assets/svg/fy-trash.svg
  src/assets/svg/fy-trips-new.svg
  src/assets/svg/fy-user.svg
  src/assets/svg/fy-warning.svg
  src/assets/svg/pdfnew.svg
Labels: size/M

#2179 fix: remove unused icons (.svg) --mobile --part0
  src/assets/images/profile/gmail.svg
  src/assets/images/profile/outlook.svg
  src/assets/images/profile/smartphone.svg
  src/assets/images/profile/web.svg
  src/assets/images/zero-states/coffee.svg
  src/assets/images/zero-states/expenses.svg
  src/assets/images/zero-states/reports.svg
  src/assets/svg/arrow-back.svg
  src/assets/svg/auto-extracting.svg
  src/assets/svg/check-circle.svg
  src/assets/svg/dots.svg
  src/assets/svg/expand-arrow.svg
  src/assets/svg/fy-add-receipt.svg
  src/assets/svg/fy-dashboard.svg
  src/assets/svg/fy-dot-small.svg
  src/assets/svg/fy-dropdown.svg
  src/assets/svg/fy-edit.svg
  src/assets/svg/fy-error.svg
  src/assets/svg/fy-flag.svg
  src/assets/svg/fy-plus-gradient.svg
  src/assets/svg/fy-rotate.svg
  src/assets/svg/fy-swap.svg
  src/assets/svg/fy-team-reports.svg
  src/assets/svg/fy-team-wallet.svg
  src/assets/svg/fy-trash-o.svg
  src/assets/svg/fy-trash.svg
  src/assets/svg/fy-trips-new.svg
  src/assets/svg/fy-user.svg
  src/assets/svg/fy-warning.svg
  src/assets/svg/pdfnew.svg
Labels: size/M

#2184 feat:session inactivity fix
  src/app/core/services/auth.service.spec.ts
  src/app/core/services/auth.service.ts
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/router-auth.service.ts
Labels: size/XS

#2172 test: Code Coverage: Add Edit Expense #6 Part 1
  src/app/core/mock-data/account-option.data.ts
  src/app/core/mock-data/public-policy-expense.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XL

#2185 feat: Added eslint rules for whole codebase
  .eslintrc.json
Labels: size/S

#2190 fix: Fixing disabled tests
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
Labels: size/M

#2188 feat: Show mobile number card only for verified users and add trackers
  src/app/core/mock-data/info-card-data.data.ts
  src/app/core/models/info-card-data.model.ts
  src/app/core/services/deep-link.service.spec.ts
  src/app/core/services/deep-link.service.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/M

#2178 fix: Fix cost center and cost center code not visible to some users
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
Labels: size/XS

#2182 test: Fix unit tests for #sms_to_submit_receipt initiative
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/core/services/deep-link.service.spec.ts
  src/app/core/services/deep-link.service.ts
  src/app/core/test-data/deep-link.service.spec.data.ts
  src/app/deep-link-redirection/deep-link-redirection.page.spec.ts
  src/app/deep-link-redirection/deep-link-redirection.page.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
Labels: size/L

#2194 test: Code Coverage : Add Edit Expense #7 Part 2
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/L

#2200 fix: updated pr check image tag
  .github/workflows/pr-checks.yml
Labels: size/XS

#2192 feat: Added linting on the diff
  .eslintrc.json
  .github/workflows/lint.yml
  package.json
Labels: size/S

#2202 fix: Added changes to skip checking specific files
  .eslintrc.json
Labels: size/XS

#2196 test: 100% coverage of merge-expense page
  src/app/core/mock-data/combined-options.data.ts
  src/app/fyle/merge-expense/merge-expense-3.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/L

#2195 test: 86% code coverage of merge-expense page
  src/app/core/mock-data/combined-options.data.ts
  src/app/core/mock-data/custom-field.data.ts
  src/app/core/mock-data/merge-expenses-options-data.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/merge-expense/merge-expense-3.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/L

#2187 test: 50% coverage of Merge expense page
  src/app/core/mock-data/combined-options.data.ts
  src/app/core/mock-data/cost-center-dependent-fields-mapping.data.ts
  src/app/core/mock-data/custom-field.data.ts
  src/app/core/mock-data/generated-form-properties.data.ts
  src/app/core/mock-data/merge-expense-form-data.data.ts
  src/app/core/mock-data/merge-expenses-options-data.data.ts
  src/app/core/mock-data/project-dependent-fields-mapping.data.ts
  src/app/core/mock-data/snackbar-properties.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/models/cost-center-dependent-fields-mapping.model.ts
  src/app/core/models/generated-form-properties.model.ts
  src/app/core/models/project-dependent-fields-mapping.model.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/merge-expense/merge-expense-1.page.spec.ts
  src/app/fyle/merge-expense/merge-expense-2.page.spec.ts
  src/app/fyle/merge-expense/merge-expense-3.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.setup.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XL

#2205 fix: Added updates for page depth in linting rules
  .github/workflows/lint.yml
Labels: size/XS

#2203 fix: Added fixes for tracking service
  .github/workflows/lint.yml
  src/app/core/services/org.service.spec.ts
  src/app/core/services/tracking.service.ts
Labels: size/L

#2199 feat: Added directions API
  src/app/app.module.ts
  src/app/core/mock-data/directions-results.data.ts
  src/app/core/services/gmaps.service.ts
  src/app/core/services/location.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/shared/components/route-visualizer/mileage-route.interface.ts
  src/app/shared/components/route-visualizer/route-visualizer.component.html
  src/app/shared/components/route-visualizer/route-visualizer.component.spec.ts
  src/app/shared/components/route-visualizer/route-visualizer.component.ts
  src/app/shared/shared.module.ts
Labels: size/L
