Repository fylein/fyle-mobile-app, pull requests merged in 2023-12, with the labels that each got.

#2627 feat: added the routing guard for beta pages
  src/app/core/guards/beta-page-feature-flag.guard.spec.ts
  src/app/core/guards/beta-page-feature-flag.guard.ts
  src/app/core/services/org-settings.service.ts
Labels: size/M

#2630 feat: Standardize icons - Milestone-7
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/sidemenu.data.ts
  src/app/core/mock-data/snackbar-properties.data.ts
  src/app/core/services/snackbar-properties.service.spec.ts
  src/app/core/services/snackbar-properties.service.ts
  src/app/core/services/status.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.scss
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
  src/app/fyle/my-view-report/my-view-report-v2.page.html
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
  src/app/fyle/view-team-report/view-team-report-v2.page.html
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.scss
  src/app/shared/components/comments-history/audit-history/audit-history.component.html
  src/app/shared/components/fy-approver/fy-approver.component.html
  src/app/shared/components/fy-approver/fy-approver.component.scss
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/app/shared/icon/icon.module.ts
  src/assets/svg/comments-zero-state.svg
  src/assets/svg/crop.svg
  src/assets/svg/curve.svg
  src/assets/svg/delegate-switch.svg
  src/assets/svg/dot-menu.svg
  src/assets/svg/duplicate.svg
  src/assets/svg/edit.svg
  src/assets/svg/flag-fill.svg
  src/assets/svg/flag-outline.svg
  src/assets/svg/flag.svg
  src/assets/svg/fy-delegate-switch.svg
  src/assets/svg/fy-edit-2.svg
  src/assets/svg/fy-edit-gradient.svg
  src/assets/svg/fy-flag-2.svg
  src/assets/svg/vertical-dots-menu.svg
  src/assets/svg/warning-fill.svg
Labels: size/M

#2631 feat: Standardize icons - Milestone-8
  src/app/core/mock-data/sidemenu-item.data.ts
  src/app/core/mock-data/sidemenu.data.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/my-advances/my-advances.page.html
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/team-advance/team-advance.page.html
  src/app/fyle/team-reports/team-reports.page.html
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
  src/app/shared/components/footer/footer.component.html
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.html
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/app/shared/icon/icon.module.ts
  src/assets/svg/chat.svg
  src/assets/svg/dashboard.svg
  src/assets/svg/filter-applied.svg
  src/assets/svg/filter.svg
  src/assets/svg/fy-add-new-expense.svg
  src/assets/svg/fy-advances-new.svg
  src/assets/svg/fy-applied-filter.svg
  src/assets/svg/fy-bot.svg
  src/assets/svg/fy-bus.svg
  src/assets/svg/fy-car-mini.svg
  src/assets/svg/fy-car.svg
  src/assets/svg/fy-chat-2.svg
  src/assets/svg/fy-chat.svg
  src/assets/svg/fy-dashboard-new.svg
  src/assets/svg/fy-expenses-new.svg
  src/assets/svg/fy-filter.svg
  src/assets/svg/fy-iphone.svg
  src/assets/svg/house-fill.svg
  src/assets/svg/house-outline.svg
Labels: size/M

#2636 fix: typo in policy violation default comment
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/XS

#2641 feat: Migrating Potential Duplicates and Suggested Duplicates Page
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.html
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.spec.ts
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.html
  src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.ts
Labels: size/L

#2643 fix: Fixed Bug in Moving Suggested Duplicates Page
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.spec.ts
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.ts
Labels: size/XS

#2639 fix: Fix for edit report name test case failing randomly
  src/app/fyle/view-team-report/view-team-report-v2.page.spec.ts
Labels: size/XS

#2640 feat: Standardize icons - Milestone-9
  src/app/auth/sign-in/sign-in.page.html
  src/app/core/mock-data/sidemenu-item.data.ts
  src/app/core/mock-data/sidemenu.data.ts
  src/app/fyle/add-edit-advance-request/camera-options-popup/camera-options-popup.component.html
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.html
  src/app/fyle/my-view-advance/my-view-advance.page.html
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.spec.ts
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.ts
  src/app/shared/components/corporate-card/corporate-card.component.html
  src/app/shared/components/corporate-card/corporate-card.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/expenses-card/expenses-card.component.html
  src/app/shared/components/expenses-card/expenses-card.component.scss
  src/app/shared/components/fy-approver/fy-approver.component.html
  src/app/shared/components/fy-approver/fy-approver.component.scss
  src/app/shared/components/fy-policy-violation/fy-policy-violation.component.html
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.html
  src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.html
  src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.scss
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/app/shared/icon/icon.module.ts
  src/assets/svg/fy-gallery.svg
  src/assets/svg/fy-help-new.svg
  src/assets/svg/fy-settings.svg
  src/assets/svg/gallery.svg
  src/assets/svg/gear.svg
  src/assets/svg/help.svg
  src/assets/svg/house-filled-arrow-clockwise.svg
  src/assets/svg/image.svg
  src/assets/svg/ionic-log-out-outline.svg
  src/assets/svg/logo-google.svg
  src/assets/svg/more.svg
  src/assets/svg/open-in-new-tab.svg
  src/assets/svg/power.svg
  src/assets/svg/professional-service.svg
  src/assets/svg/profile-outline.svg
  src/assets/svg/profile.svg
  src/assets/svg/question-square-outline.svg
  src/assets/svg/return-home.svg
  src/assets/svg/settings.svg
  src/assets/svg/single.svg
  src/assets/svg/split-expense.svg
  src/assets/svg/split-new.svg
  src/assets/svg/split.svg
  src/assets/svg/swap.svg
  src/assets/svg/tag.svg
  src/assets/svg/user-one.svg
  src/assets/svg/user-three.svg
  src/assets/svg/user-two.svg
Labels: size/L

#2644 fix: Fix for danger and filter icon
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.html
  src/app/shared/components/fy-alert-info/fy-alert-info.component.html
  src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.html
Labels: size/XS

#2645 fix: Fixing Redirection In Card Details Component
  src/app/core/guards/my-expenses-guard.guard.spec.ts
  src/app/core/guards/my-expenses-guard.guard.ts
  src/app/fyle/fyle-routing.module.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
Labels: size/M

#2626 feat: Generate staging build on push of release branches
  .github/workflows/appflow-release-branch.yml
Labels: size/M

#2646 fix: Minor fix in appflow release branch action
  .github/workflows/appflow-release-branch.yml
Labels: size/XS

#2647 fix: Fixing Merge Expenses from Potential/Suggested Duplicates
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XS

#2650 fix: Redirection on Expense Stats Card to My Expenses
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/fyle/dashboard/stats/stats.component.spec.ts
  src/app/fyle/dashboard/stats/stats.component.ts
Labels: size/M

#2652 fix: Fixing Redirection in Potential Duplicates Cards
  src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.ts
Labels: size/XS

#2655 feat: Track suggested duplicates usage in edit expense page
  src/app/core/services/tracking.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XS

#2653 feat: Standardize icons - Milestone-12
  src/app/auth/disabled/disabled.page.html
  src/app/auth/new-password/new-password.page.html
  src/app/auth/request-invitation/request-invitation.page.html
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/switch-org/switch-org.page.html
  src/app/auth/verify/verify.page.html
  src/app/core/mock-data/sidemenu.data.ts
  src/app/core/services/status.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/manage-corporate-cards/card-added/card-added.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/expenses-card/expenses-card.component.scss
  src/app/shared/components/fy-alert-info/fy-alert-info.component.html
  src/app/shared/components/reports-card/reports-card.component.html
  src/app/shared/components/reports-card/reports-card.component.scss
  src/app/shared/components/send-email/send-email.component.html
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/app/shared/icon/icon.module.ts
  src/assets/svg/expense-rule.svg
  src/assets/svg/expense.svg
  src/assets/svg/file-lightning-indicator.svg
  src/assets/svg/fy-receipt.svg
  src/assets/svg/fy-scan.svg
  src/assets/svg/fyle-logo-black.svg
  src/assets/svg/fyle-logo-dark.svg
  src/assets/svg/fyle-logo-light.svg
  src/assets/svg/info-circle-fill.svg
  src/assets/svg/logo-icon-white.svg
  src/assets/svg/logo-white.svg
  src/assets/svg/scan.svg
Labels: size/M

#2660 feat: Standardize icons - Milestone-13
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.scss
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/preference-setting/preference-setting.component.html
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
  src/app/fyle/my-view-advance/my-view-advance.page.html
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.html
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-team-report/view-team-report-v2.page.html
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.html
  src/app/shared/components/expense-card-lite/expense-card-lite.component.html
  src/app/shared/components/expense-card-lite/expense-card-lite.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.html
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.html
  src/app/shared/components/fy-approver/add-approvers-popover/add-approvers-popover.component.html
  src/app/shared/components/fy-filters/fy-filters.component.html
  src/app/shared/components/fy-header/fy-header.component.html
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.html
  src/app/shared/components/fy-location/fy-location.component.html
  src/app/shared/components/fy-multiselect/fy-multiselect.component.html
  src/app/shared/components/fy-select-disabled/fy-select-disabled.component.html
  src/app/shared/components/fy-select-project/fy-select-project.component.html
  src/app/shared/components/fy-select-vendor/fy-select-vendor.component.html
  src/app/shared/components/fy-select/fy-select.component.html
  src/app/shared/components/fy-userlist/fy-userlist.component.html
  src/app/shared/components/navigation-footer/fy-nav-footer/fy-nav-footer.component.html
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.html
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.scss
  src/app/shared/components/route-selector/route-selector.component.html
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/virtual-select/virtual-select.component.html
  src/app/shared/icon/icon.module.ts
  src/assets/images/fy-pdf.svg
  src/assets/svg/arrow-down.svg
  src/assets/svg/arrow-left.svg
  src/assets/svg/arrow-next.svg
  src/assets/svg/arrow-prev.svg
  src/assets/svg/arrow-right.svg
  src/assets/svg/arrow-tail-left.svg
  src/assets/svg/arrow.svg
  src/assets/svg/chevron-right.svg
  src/assets/svg/file-pdf.svg
  src/assets/svg/fy-arrow-down.svg
  src/assets/svg/fy-chevron-left.svg
  src/assets/svg/left-arrow-nav.svg
  src/assets/svg/navigate-left.svg
  src/assets/svg/navigate-right.svg
  src/assets/svg/pdf.svg
  src/assets/svg/right-arrow.svg
Labels: size/M
