Repository fylein/fyle-mobile-app, pull requests merged in 2023-05, with the labels that each got.

#1972 test: Code Coverage: Approver Dialog Component
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.html
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.spec.ts
Labels: size/L

#1987 fix: Improved complete expenses task header
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.scss
Labels: size/XS

#1958 test: Code Coverage Fy-userlist-modal component
  src/app/core/mock-data/employee.data.ts
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.spec.ts
Labels: size/L

#1982 fix: Return category name only if it is enabled
  src/app/core/services/categories.service.ts
Labels: size/XS

#1980 fix: Re-revert cost center changes with fix for category dependent cost center
  src/app/core/mock-data/dependent-field-expenses.data.ts
  src/app/core/mock-data/dependent-field-mapping.data.ts
  src/app/core/mock-data/dependent-field.data.ts
  src/app/core/models/custom-input.model.ts
  src/app/core/services/dependent-fields.service.spec.ts
  src/app/core/services/dependent-fields.service.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/test-data/dependent-fields.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
  src/app/fyle/merge-expense/merge-expense.page.html
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.html
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.scss
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.spec.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#1974 fix: Fy-Select Vendor Component
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/shared/components/fy-select-vendor/fy-select-vendor.component.ts
Labels: size/S

#1984 test: 98% Coverage of fy-location-modal
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.spec.ts
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
Labels: size/L

#1979 test: Code Coverage: Fy-Multi-Select Component
  src/app/shared/components/fy-multiselect/fy-multiselect.component.html
  src/app/shared/components/fy-multiselect/fy-multiselect.component.spec.ts
  src/app/shared/components/fy-multiselect/fy-multiselect.component.ts
Labels: size/M

#1989 fix: Fy-MultiSelect Component
  src/app/shared/components/fy-multiselect/fy-multiselect.component.spec.ts
Labels: size/XS

#1992 fix: Pass empty array when custom properties is null in txn object
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
Labels: size/XS

#1970 test: 100% coverage of fy-filters
  src/app/core/mock-data/filter.data.ts
  src/app/core/mock-data/selected-filters.data.ts
  src/app/shared/components/fy-filters/fy-filters.component.spec.ts
  src/app/shared/components/fy-filters/fy-filters.component.ts
Labels: size/XL

#1988 test: 100% Coverage of Fy currency choose currency test
  src/app/shared/components/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.spec.ts
  src/app/shared/components/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.ts
Labels: size/M

#1981 test: Code Coverage: Fy-Select-Vendor Component
  src/app/shared/components/fy-select-vendor/fy-select-vendor.component.html
  src/app/shared/components/fy-select-vendor/fy-select-vendor.component.spec.ts
  src/app/shared/components/fy-select-vendor/fy-select-vendor.component.ts
Labels: size/M

#1990 test: Code Coverage: Fy-Select-Vendor-Modal Component
  src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.html
  src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.spec.ts
Labels: size/L

#1985 feat: Added split expense indicator icon in expenses card
  src/app/shared/components/expenses-card/expenses-card.component.html
  src/app/shared/components/expenses-card/expenses-card.component.scss
  src/app/shared/icon/icon.module.ts
  src/assets/svg/split-new.svg
Labels: size/S

#1986 feat: Added split expense visibility info alerts in view and edit expense pages
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.scss
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.scss
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/shared/components/fy-alert-info/fy-alert-info.component.scss
Labels: size/S

#1996 feat: Added split evenly in split expense
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.scss
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/icon/icon.module.ts
  src/assets/svg/split-evenly.svg
Labels: size/M

#1999 feat: Added split expense filters in my expenses page
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-expenses/my-expenses-filters.model.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-expenses/my-expenses.service.ts
Labels: size/M

#1991 feat: Camera Service
  src/app/core/services/camera.service.spec.ts
  src/app/core/services/camera.service.ts
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
Labels: size/S

#2003 test: 100% test coverage of pending-verification page
  src/app/auth/pending-verification/pending-verification.page.spec.ts
Labels: size/M

#1955 test: Code Coverage: Capture Receipt Component #3
  src/app/core/services/transactions-outbox.service.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
Labels: size/M

#1961 test: Code Coverage: Camera Preview Component
  src/app/core/enums/camera-state.enum.ts
  src/app/core/services/camera-preview.service.ts
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.spec.ts
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
Labels: size/M

#2008 fix: Remove f-describe
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.spec.ts
Labels: size/XS

#2001 test: 100% Coverage of fySelect component
  src/app/shared/components/fy-select/fy-select.component.spec.ts
  src/app/shared/components/fy-select/fy-select.component.ts
  src/app/shared/components/fy-select/fy-select.interface.ts
Labels: size/L

#1997 test: removing ngControl
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/merge-expense/category-dependent-fields-form/category-dependent-fields-form.component.html
  src/app/fyle/merge-expense/custom-inputs-fields-form/custom-inputs-fields-form.component.html
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/merge-expense/merge-expense.page.html
  src/app/fyle/split-expense/split-expense.page.html
  src/app/shared/components/fy-select/fy-select.component.spec.ts
  src/app/shared/components/fy-select/fy-select.component.ts
  src/app/shared/components/fy-select/fy-select.interface.ts
Labels: size/L

#2007 fix: Fixed potential duplicates task spacing
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
Labels: size/XS

#1977 test: Code Coverage 100% FyNumber Component
  src/app/shared/components/fy-number/fy-number.component.spec.ts
  src/app/shared/components/fy-number/fy-number.component.ts
Labels: size/M

#1998 test: Code Coverage: Fy-Select-Project Component
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/split-expense/split-expense.page.html
  src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.ts
Labels: size/M

#2000 test: 100% coverage of fy-select-modal component
  src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
  src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
  src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.interface.ts
Labels: size/L

#2004 test: Code Coverage: Fy-Select-Project Modal Component
  src/app/core/mock-data/extended-projects.data.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/projects.spec.data.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
Labels: size/L

#2018 feat: Add cards to copy mobile number and email
  src/app/fyle/my-profile/info-card/info-card.component.html
  src/app/fyle/my-profile/info-card/info-card.component.scss
  src/app/fyle/my-profile/info-card/info-card.component.spec.ts
  src/app/fyle/my-profile/info-card/info-card.component.ts
  src/app/fyle/my-profile/my-profile.module.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.scss
  src/app/fyle/my-profile/my-profile.page.ts
  src/assets/svg/duplicate.svg
Labels: size/M

#2015 feat: Add verification successful popup and validations
  package-lock.json
  package.json
  src/app/core/services/clipboard.service.spec.ts
  src/app/core/services/clipboard.service.ts
  src/app/fyle/my-profile/info-card/info-card.component.html
  src/app/fyle/my-profile/info-card/info-card.component.scss
  src/app/fyle/my-profile/info-card/info-card.component.spec.ts
  src/app/fyle/my-profile/info-card/info-card.component.ts
  src/app/fyle/my-profile/my-profile.module.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.scss
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.scss
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
  src/app/shared/components/fy-input-popover/fy-input-popover.component.html
  src/app/shared/components/fy-input-popover/fy-input-popover.component.scss
  src/app/shared/components/fy-input-popover/fy-input-popover.component.ts
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.html
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.scss
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.spec.ts
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.ts
  src/app/shared/shared.module.ts
  src/assets/svg/duplicate.svg
  src/assets/svg/message.svg
Labels: size/L

#2009 fix: Fy-MultiSelect Component
  src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.spec.ts
Labels: size/XS

#2021 fix: Team Adv Card component - added fix for incorrect date
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.spec.ts
Labels: size/S

#2014 fix: Fixed split_group_id incorrectly set for the first split in creation flow #3806
  src/app/core/mock-data/transaction.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
Labels: size/L

#2025 feat: More UI changes/fixes for #sms_to_submit_receipts
  src/app/core/services/snackbar-properties.service.spec.ts
  src/app/core/services/snackbar-properties.service.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.html
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.ts
  src/app/fyle/my-profile/info-card/info-card.component.ts
  src/app/fyle/my-profile/my-profile.module.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.html
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.scss
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.spec.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.ts
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.html
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.ts
  src/app/shared/icon/icon.module.ts
  src/assets/svg/fy-done.svg
  src/assets/svg/tick-circle-outline.svg
Labels: size/L

#2022 feat: Add task for adding/verifying mobile number
  src/app/core/mock-data/platform-corporate-card.data.ts
  src/app/core/mock-data/task.data.ts
  src/app/core/models/platform/platform-corporate-card.model.ts
  src/app/core/models/task-event.enum.ts
  src/app/core/models/task-icon.enum.ts
  src/app/core/models/task.model.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/core/services/snackbar-properties.service.spec.ts
  src/app/core/services/snackbar-properties.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.scss
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.html
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.ts
  src/app/fyle/my-profile/info-card/info-card.component.ts
  src/app/fyle/my-profile/my-profile.module.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.html
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.scss
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.spec.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.ts
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.html
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.ts
  src/app/shared/icon/icon.module.ts
  src/assets/svg/call.svg
  src/assets/svg/fy-done.svg
  src/assets/svg/tick-circle-outline.svg
Labels: size/XL

#2027 test: Code Coverage: View Team Report #1
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
Labels: size/L

#1978 test: Code coverage 100% ExpensesCard Component
  src/app/shared/components/expenses-card/expenses-card.component.html
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/XL

#2012 test: Code coverage setupAccountPage
  src/app/post-verification/setup-account/setup-account.page.spec.ts
Labels: size/L

#2017 feat: Adding receiptlimit tracker
  src/app/core/services/tracking.service.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
Labels: size/XS

#2023 test: code coverage 100% RequestInvitationPage
  src/app/auth/request-invitation/request-invitation.page.spec.ts
  src/app/auth/request-invitation/request-invitation.page.ts
Labels: size/M

#2029 test: Code coverage 100% InvitedUserPage
  src/app/post-verification/invited-user/invited-user.page.spec.ts
  src/app/post-verification/invited-user/invited-user.page.ts
Labels: size/L

#2016 test: Code Coverage: Sign In Component
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/app/core/mock-data/auth-reponse.data.ts
  src/app/core/services/in-app-browser.service.spec.ts
  src/app/core/services/in-app-browser.service.ts
Labels: size/L

#2042 fix: janus vulnerability-changed minsdk version to 24
  android/variables.gradle
Labels: size/XS

#2036 test: Code Coverage 50% View Expense Page
  src/app/core/mock-data/individual-expense-policy-state.data.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
Labels: size/L

#2034 fix: remove unused permissions
  android/app/src/main/AndroidManifest.xml
Labels: size/XS

#2040 fix: Report Submission Date Mismatch
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.html
Labels: size/XS

#2033 fix: strandhogg vulnerability - launchMode and taskAffinity
  android/app/src/main/AndroidManifest.xml
Labels: size/XS

#1983 test: Tests for dependent fields component
  src/app/core/mock-data/custom-property.data.ts
  src/app/core/mock-data/dependent-field-value.data.ts
  src/app/core/mock-data/expense-field.data.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.spec.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.ts
Labels: size/L

#1843 fix: Sign In Page Google Button Loader
  src/app/auth/sign-in/sign-in.page.scss
Labels: size/XS

#2047 fix: Fixing missing headers (Status service)
  src/app/core/services/status.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
Labels: size/M

#2041 feat: Add timer and error messages in ui with unit tests
  src/app/core/mock-data/error-mapping-for-verify-number-popover.data.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.scss
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.spec.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.ts
  src/app/fyle/my-profile/verify-number-popover/error-type.model.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.scss
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
  src/app/shared/directive/form-button-validation.directive.ts
Labels: size/L

#2038 test: Add tests for update mobile number popover and my-profile page
  src/app/core/mock-data/error-mapping-for-verify-number-popover.data.ts
  src/app/core/mock-data/info-card-data.data.ts
  src/app/core/mock-data/value-error-mapping-for-update-mobile-number-popover.data.ts
  src/app/core/models/info-card-data.model.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.scss
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.spec.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.ts
  src/app/fyle/my-profile/verify-number-popover/error-type.model.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.scss
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
  src/app/shared/directive/form-button-validation.directive.ts
Labels: size/L

#2037 test: Add tests for verify mobile number popover
  src/app/core/mock-data/error-mapping-for-verify-number-popover.data.ts
  src/app/core/mock-data/info-card-data.data.ts
  src/app/core/mock-data/value-error-mapping-for-update-mobile-number-popover.data.ts
  src/app/core/models/info-card-data.model.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.scss
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.spec.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.ts
  src/app/fyle/my-profile/verify-number-popover/error-type.model.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.scss
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
  src/app/shared/directive/form-button-validation.directive.ts
Labels: size/M

#2028 test: Add unit tests for newly added components in sms to submit receipt
  src/app/core/mock-data/error-mapping-for-verify-number-popover.data.ts
  src/app/core/mock-data/info-card-data.data.ts
  src/app/core/mock-data/value-error-mapping-for-update-mobile-number-popover.data.ts
  src/app/core/models/info-card-data.model.ts
  src/app/core/services/mobile-number-verification.service.spec.ts
  src/app/fyle/my-profile/info-card/info-card.component.spec.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.scss
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.spec.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.ts
  src/app/fyle/my-profile/verify-number-popover/error-type.model.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.scss
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.html
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.spec.ts
  src/app/shared/components/popup-with-bullets/popup-with-bullets.component.ts
  src/app/shared/directive/form-button-validation.directive.ts
Labels: size/XL

#2044 test: Code Coverage: My-View Report Page
  src/app/core/enums/report-page-segment.enum.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/L

#2046 test: Code Coverage: Add Expenses To Report Component
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.spec.ts
Labels: size/M

#2050 test: 100% Coverage of Verify Page
  src/app/auth/verify/verify.enum.ts
  src/app/auth/verify/verify.page.spec.ts
  src/app/auth/verify/verify.page.ts
Labels: size/M

#2049 test: code coverage 100% HelpPage
  src/app/core/services/browser-handler.service.spec.ts
  src/app/core/services/browser-handler.service.ts
  src/app/fyle/help/help.page.spec.ts
  src/app/fyle/help/help.page.ts
Labels: size/M

#2051 feat: Fix comments on mobile app implementation
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.html
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.scss
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
Labels: size/M

#2043 test: Code Coverage: View-Team Reports Component #2
  src/app/core/mock-data/approver.data.ts
  src/app/core/models/extended_status.model.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/XL

#2048 test: 100% Coverage of NewPassword Page
  src/app/auth/new-password/new-password.page.html
  src/app/auth/new-password/new-password.page.scss
  src/app/auth/new-password/new-password.page.spec.ts
Labels: size/L

#2045 test: code coverage View Expense Page
  src/app/core/mock-data/expense-fields-map.data.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
Labels: size/L

#2054 test: code coverage 100% Support Dialog
  src/app/fyle/help/support-dialog/support-dialog.page.spec.ts
  src/app/fyle/help/support-dialog/support-dialog.page.ts
Labels: size/M

#2059 feat: Added linting rules for type issues inside shared folder
  .eslintrc.json
Labels: size/XS

#2060 test: code coverage 50% View Mileage Page
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.scss
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
Labels: size/L

#2064 fix: Added types in policy service
  src/app/core/services/policy.service.ts
Labels: size/XS
