Repository fylein/fyle-mobile-app, pull requests merged in 2023-04, with the labels that each got.

#1871 test: Code Coverage: Add Txn To Report Dialog Component
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.spec.ts
Labels: size/M

#1873 test: Code Coverage: Fy-Delete Dialog Component
  src/app/shared/components/fy-delete-dialog/fy-delete-dialog.component.spec.ts
Labels: size/M

#1876 test: Code coverage: FyPopover Component
  src/app/shared/components/fy-popover/fy-popover.component.spec.ts
Labels: size/S

#1877 test: Code Coverage: Fy-Popup Component
  src/app/shared/components/fy-popup/fy-popup.component.spec.ts
Labels: size/M

#1875 test: Code Coverage: Personal Cards Matched Expenses Page Component
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.spec.ts
Labels: size/M

#1869 feat: Optimizations for checkPolicyViolation
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/platform-api-category.data.ts
  src/app/core/services/categories.service.spec.ts
  src/app/core/services/categories.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#1878 test: Code coverage: FyFilterPills Component
  src/app/shared/components/fy-filter-pills/fy-filter-pills.component.spec.ts
Labels: size/S

#1880 test: Code coverage commentsHistory component
  src/app/shared/components/comments-history/comments-history.component.spec.ts
Labels: size/M

#1881 feat: Show card transaction description, if present, in add edit expense page
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/view-expense/view-expense.page.html
Labels: size/XS

#1884 test: Removed unused reports components
  src/app/fyle/my-reports/my-reports-search-filter/my-reports-search-filter.component.html
  src/app/fyle/my-reports/my-reports-search-filter/my-reports-search-filter.component.scss
  src/app/fyle/my-reports/my-reports-search-filter/my-reports-search-filter.component.spec.ts
  src/app/fyle/my-reports/my-reports-search-filter/my-reports-search-filter.component.ts
  src/app/fyle/my-reports/my-reports.module.ts
  src/app/fyle/team-reports/team-reports-search-filter/team-reports-search-filter.component.html
  src/app/fyle/team-reports/team-reports-search-filter/team-reports-search-filter.component.scss
  src/app/fyle/team-reports/team-reports-search-filter/team-reports-search-filter.component.spec.ts
  src/app/fyle/team-reports/team-reports-search-filter/team-reports-search-filter.component.ts
  src/app/fyle/team-reports/team-reports.module.ts
Labels: size/L

#1885 fix: Code Coverage: MyReportsSortFilter and TeamReportsSortFilter
  src/app/fyle/my-reports/my-reports-sort-filter/my-reports-sort-filter.component.html
  src/app/fyle/my-reports/my-reports-sort-filter/my-reports-sort-filter.component.scss
  src/app/fyle/my-reports/my-reports-sort-filter/my-reports-sort-filter.component.spec.ts
  src/app/fyle/my-reports/my-reports-sort-filter/my-reports-sort-filter.component.ts
  src/app/fyle/my-reports/my-reports.module.ts
  src/app/fyle/team-reports/team-reports-sort-filter/team-reports-sort-filter.component.html
  src/app/fyle/team-reports/team-reports-sort-filter/team-reports-sort-filter.component.scss
  src/app/fyle/team-reports/team-reports-sort-filter/team-reports-sort-filter.component.spec.ts
  src/app/fyle/team-reports/team-reports-sort-filter/team-reports-sort-filter.component.ts
  src/app/fyle/team-reports/team-reports.module.ts
Labels: size/L

#1887 test: code coverage TaskCard Component 91%
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.spec.ts
Labels: size/M

#1890 fix: Code Coverage: Reports Card Component #2
  src/app/fyle/my-reports/my-reports.module.ts
  src/app/fyle/team-reports/team-reports.module.ts
Labels: size/XS

#1891 fix: Reports Cards Component
  src/app/fyle/team-reports/team-reports.page.html
Labels: size/XS

#1872 test: Code coverage dateRangeModal component
  src/app/fyle/personal-cards/date-range-modal/date-range-modal.component.spec.ts
Labels: size/M

#1879 feat: Optimizations in getEditExpenseObservable
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#1882 feat: Optimization in getCategoryOnEdit
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#1886 feat: Optimization in getCategoryOnAdd
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#1883 feat: Optimization in setCategoryFromVendor
  src/app/core/services/tracking.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#1896 fix: Fixing a test on master
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.spec.ts
Labels: size/XS

#1897 test: Code Coverage: Bank Account Card Component
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.spec.ts
Labels: size/M

#1895 test: Code coverage PreferenceSetting Component
  src/app/fyle/my-profile/preference-setting/preference-setting.component.spec.ts
Labels: size/M

#1892 test: Code Coverage: Delegated Account Message Component
  src/app/shared/components/delegated-acc-message/delegated-acc-message.component.spec.ts
Labels: size/S

#1893 test: Code Coverage: Setup Account Preferences Page Component
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/services/payment-modes.service.spec.ts
  src/app/core/services/permissions.service.spec.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/sidemenu.service.spec.ts
  src/app/post-verification/setup-account-preferences/setup-account-preferences.page.spec.ts
Labels: size/M

#1900 fix: Revert dependent fields refactoring
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/dependent-field/dependent-field-modal/dependent-field-modal.component.html
  src/app/shared/components/dependent-field/dependent-field-modal/dependent-field-modal.component.scss
  src/app/shared/components/dependent-field/dependent-field-modal/dependent-field-modal.component.spec.ts
  src/app/shared/components/dependent-field/dependent-field-modal/dependent-field-modal.component.ts
  src/app/shared/components/dependent-field/dependent-field.component.html
  src/app/shared/components/dependent-field/dependent-field.component.scss
  src/app/shared/components/dependent-field/dependent-field.component.spec.ts
  src/app/shared/components/dependent-field/dependent-field.component.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.html
  src/app/shared/components/dependent-fields/dependent-fields.component.scss
  src/app/shared/components/dependent-fields/dependent-fields.component.spec.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#1907 fix: Slack message for release branch github action
  .github/workflows/create-release-branch.yml
Labels: size/XS

#1902 test: Code Coverage: Employee Details Card Component
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.html
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
Labels: size/M

#1905 test: Code coverage 100% SidemenuContent Component
  src/app/core/mock-data/sidemenu-item.data.ts
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.spec.ts
Labels: size/M

#1910 test: 100 Coverage on split-expense-policy-violation
  src/app/core/mock-data/formatted-policy-violation.data.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/M

#1901 test: Code coverage SuggestedDuplicates Component
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.spec.ts
Labels: size/M

#1894 test: Code coverage : ExpenseCardLite Component
  src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
Labels: size/M

#1911 test: Code Coverage: Audit History Component
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/models/extended_status.model.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/shared/components/comments-history/audit-history/audit-history.component.spec.ts
  src/app/shared/components/comments-history/audit-history/audit-history.component.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.html
Labels: size/L

#1915 fix: Using cloneDeep to stop manipulating the actual mock data
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/XS

#1909 test: Code coverage 100% AddApproversPopover Component
  src/app/shared/components/fy-approver/add-approvers-popover/add-approvers-popover.component.spec.ts
Labels: size/M

#1918 feat: Add cost center dependent field changes to merge expense page
  src/app/core/services/dependent-fields.service.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
  src/app/fyle/merge-expense/merge-expense.page.html
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/M

#1916 feat: Add CC dependent fields to view mileage/per-diem page
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/L

#1914 feat: Split expense with cost center dependent fields
  src/app/core/mock-data/dependent-field.data.ts
  src/app/core/models/custom-input.model.ts
  src/app/core/services/dependent-fields.service.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
  src/app/fyle/merge-expense/merge-expense.page.html
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/L

#1913 feat: Show cost center dependent fields in view expense page
  src/app/core/mock-data/dependent-field.data.ts
  src/app/core/models/custom-input.model.ts
  src/app/core/services/dependent-fields.service.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
  src/app/fyle/merge-expense/merge-expense.page.html
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.html
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.ts
Labels: size/XL

#1908 feat: Create shared presentational component for view expense
  src/app/core/mock-data/dependent-field.data.ts
  src/app/core/models/custom-input.model.ts
  src/app/core/services/dependent-fields.service.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
  src/app/fyle/merge-expense/merge-expense.page.html
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.html
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.scss
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.spec.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#1904 fix: Dependent fields not shown in edit expense when tax group is present
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#1903 fix: Re-revert dependent field refactoring changes
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.html
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.scss
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.spec.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.html
  src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.scss
  src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.spec.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.html
  src/app/shared/components/dependent-fields/dependent-fields.component.scss
  src/app/shared/components/dependent-fields/dependent-fields.component.spec.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#1920 fix: Added fix for expense aggregation
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/router-auth.service.ts
Labels: size/XS

#1921 test: Code Coverage: Navigation Footer Component
  src/app/shared/components/navigation-footer/navigation-footer.component.spec.ts
Labels: size/M

#1919 test: code coverage 100% Spent Card Components
  src/app/core/mock-data/card-detail-data.ts
  src/app/shared/components/spent-cards/spent-cards.component.spec.ts
Labels: size/M

#1923 test: code coverage ExpensePreview Component
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
Labels: size/M

#1922 test: Code Coverage: Route Visualizer Component
  src/app/core/mock-data/mileage-location.data.ts
  src/app/shared/components/route-visualizer/route-visualizer.component.spec.ts
Labels: size/M

#1929 feat: Add unit tests for cost center dependent fields
  src/app/core/mock-data/dependent-field-expenses.data.ts
  src/app/core/mock-data/dependent-field-mapping.data.ts
  src/app/core/mock-data/dependent-field.data.ts
  src/app/core/services/dependent-fields.service.spec.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/test-data/dependent-fields.service.spec.data.ts
Labels: size/L

#1906 feat: Add dependent fields for cost center
  src/app/core/mock-data/dependent-field-expenses.data.ts
  src/app/core/mock-data/dependent-field-mapping.data.ts
  src/app/core/mock-data/dependent-field.data.ts
  src/app/core/models/custom-input.model.ts
  src/app/core/services/dependent-fields.service.spec.ts
  src/app/core/services/dependent-fields.service.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/test-data/dependent-fields.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
  src/app/fyle/merge-expense/merge-expense.page.html
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.html
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.scss
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.spec.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#1898 fix: Use keydown event to update value of input in ios
  package-lock.json
  package.json
  src/app/shared/components/fy-number/fy-number.component.html
  src/app/shared/components/fy-number/fy-number.component.ts
Labels: size/M

#1928 fix: Route Selector Component
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/shared/components/route-selector/route-selector.component.ts
Labels: size/XS

#1927 fix: Currency Service
  src/app/core/services/currency.service.spec.ts
Labels: size/XS

#1912 feat: Renamed unreported to complete
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-expenses/my-expenses.service.ts
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/shared/components/summary-tile/summary-tile.component.scss
  src/app/shared/pipes/expense-state.pipe.spec.ts
  src/app/shared/pipes/expense-state.pipe.ts
  src/app/shared/pipes/report-state.pipe.spec.ts
  src/app/shared/pipes/report-state.pipe.ts
  src/theme/colors.scss
Labels: size/M

#1931 test: Code Coverage: Route Selector Component
  src/app/core/mock-data/expense-fields-map.data.ts
  src/app/core/mock-data/mileage-location.data.ts
  src/app/shared/components/route-selector/route-selector.component.spec.ts
Labels: size/L

#1932 test: 100% Coverage for ReceiptPreviewThumbnail
  src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.spec.ts
Labels: size/M

#1935 test: 100% Coverage of FyViewAttachment component
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.spec.ts
Labels: size/L

#1939 fix: Fixed Complete expenses task card header for consistency
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
Labels: size/XS

#1940 fix: Fix cost center dep fields not shown when tax group is present
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#1941 test: 100% Coverage for fyViewReportInfo component
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.spec.ts
Labels: size/L

#1938 test: code coverage 100% PersonalCardTransaction Component
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.spec.ts
Labels: size/M

#1937 test: Code Coverage: Capture Receipt Component #1
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
Labels: size/L

#1934 test: code coverage Sidemenu component
  src/app/core/mock-data/sidemenu.data.ts
  src/app/core/services/network.service.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/L

#1942 fix: Fixed path bad naming
  src/app/shared/components/fy-alert-info/fy-alert-info.component.html
  src/app/shared/components/fy-alert-info/fy-alert-info.component.scss
  src/app/shared/components/fy-alert-info/fy-alert-info.component.spec.ts
  src/app/shared/components/fy-alert-info/fy-alert-info.component.ts
  src/app/shared/components/popup-alert/popup-alert.component.spec.ts
  src/app/shared/shared.module.ts
Labels: size/XS

#1947 fix: Fix validations for project and cost center
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#1944 test: Code coverage BankAccountCards Component
  src/app/core/mock-data/personal-cards.data.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.spec.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.ts
Labels: size/M

#1936 feat: Add max size upload limit to 5MB
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.ts
Labels: size/S

#1949 feat: Update github actions to use the latest build stack
  .github/workflows/appflow-master.yml
  .github/workflows/appflow.yml
  .github/workflows/create-release-branch.yml
  .github/workflows/internal-release.yml
  .github/workflows/live-update.yml
  .github/workflows/manual-appflow-1.yml
  .github/workflows/manual-appflow-with-inputs.yml
Labels: size/M

#1951 test: 98.8% Coverage for fyCurrency component
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/shared/components/fy-currency/fy-currency.component.spec.ts
  src/app/shared/components/fy-currency/fy-currency.component.ts
Labels: size/L

#1945 test: Code Coverage 100% ViewComment Component
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
Labels: size/L

#1943 test: Code Coverage: Capture Receipt Component #2
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
Labels: size/L

#1953 test: Code Coverage: Receipt Preview Component
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
  src/app/shared/components/fy-currency/fy-currency.component.html
  src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.spec.ts
Labels: size/L

#1956 test: Code coverage 100% CreateNewReport Component
  src/app/shared/components/create-new-report/create-new-report.component.spec.ts
Labels: size/L

#1952 test: 100% coverage of fyCurrencyExchangeRate component
  src/app/shared/components/fy-currency/fy-currency-exchange-rate/fy-currency-exchange-rate.component.spec.ts
Labels: size/M

#1975 fix: Revert cost center dependent fields
  src/app/core/mock-data/dependent-field-expenses.data.ts
  src/app/core/mock-data/dependent-field.data.ts
  src/app/core/mock-data/project-dependent-field-mapping.data.ts
  src/app/core/models/merge-expense-custom-input.model.ts
  src/app/core/services/dependent-fields.service.spec.ts
  src/app/core/services/dependent-fields.service.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/test-data/dependent-fields.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
  src/app/fyle/merge-expense/merge-expense.page.html
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.html
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.scss
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.spec.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#1976 fix: Add validators only if project is mandatory
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#1966 test: 97% coverage for fy-location component
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/shared/components/fy-location/fy-location.component.spec.ts
  src/app/shared/components/fy-location/fy-location.component.ts
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.html
  src/app/shared/components/route-selector/route-selector.component.html
Labels: size/M

#1963 Fixing Unit Tests
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
Labels: size/S

#1962 fix: Fy-MultiSelect Component
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/shared/components/fy-multiselect/fy-multiselect.component.ts
Labels: size/S

#1971 feat: Trigger unit tests and eslint action for every PR
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
Labels: size/XS

#1957 test: Code Coverage: Fy-MultiSelect Modal Component
  src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.html
  src/app/shared/components/fy-multiselect/fy-multiselect-modal/fy-multiselect-modal.component.spec.ts
Labels: size/M

#1965 test: Code coverage Fy-userlist component
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/shared/components/fy-userlist/fy-userlist.component.spec.ts
  src/app/shared/components/fy-userlist/fy-userlist.component.ts
Labels: size/M
