Repository fylein/fyle-mobile-app, pull requests merged in 2023-11, with the labels that each got.

#2511 feat: Deprecate Advance request policies
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/policy-violation-check.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/policy-violation-check.model.ts
  src/app/core/services/advance-request-policy.service.spec.ts
  src/app/core/services/advance-request-policy.service.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/router-auth.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-1.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.module.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.setup.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/add-edit-advance-request/policy-violation-dialog/policy-violation-dialog.component.html
  src/app/fyle/add-edit-advance-request/policy-violation-dialog/policy-violation-dialog.component.scss
  src/app/fyle/add-edit-advance-request/policy-violation-dialog/policy-violation-dialog.component.spec.ts
  src/app/fyle/add-edit-advance-request/policy-violation-dialog/policy-violation-dialog.component.ts
Labels: size/L

#2526 fix: Receipt Mandatory Settings QA Fixes
  src/app/core/services/policy.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/L

#2527 test: Tests for Receipt Mandatory Settings QA Fixes
  src/app/core/mock-data/org-category.data.ts
  src/app/core/services/policy.service.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/L

#2477 feat: Receipt mandatory settings combined changes
  src/app/core/mock-data/missing-mandatory-fields.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/models/platform/platform-missing-mandatory-fields-response.model.ts
  src/app/core/models/platform/platform-missing-mandatory-fields.model.ts
  src/app/core/services/policy.service.spec.ts
  src/app/core/services/policy.service.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/shared/components/fy-alert-info/fy-alert-info.component.html
  src/app/shared/components/fy-alert-info/fy-alert-info.component.ts
Labels: size/XL

#2537 test: Fix add card component flaky test
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.spec.ts
Labels: size/M

#2535 fix: Per Diem scan fix and redirection fix for view report
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/M

#2538 fix: Removed not used code for /transactions API and Expense Reversed
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.html
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
Labels: size/M

#2512 feat: Added platform expense models
  src/app/core/models/name-value-pair.model.ts
  src/app/core/models/platform/platform-mileage-rates.model.ts
  src/app/core/models/platform/platform-report.model.ts
  src/app/core/models/platform/report-approvals.model.ts
  src/app/core/models/platform/v1/account.model.ts
  src/app/core/models/platform/v1/department.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/platform/v1/file.model.ts
  src/app/core/models/platform/v1/level.model.ts
  src/app/core/models/platform/v1/project.model.ts
  src/app/core/models/platform/v1/user.model.ts
Labels: size/L

#2530 feat: Added platform expense services
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/models/app-supported-details.model.ts
  src/app/core/services/app-version.service.ts
  src/app/core/services/invitation-requests.service.ts
  src/app/core/services/platform/v1/approver/approver.service.spec.ts
  src/app/core/services/platform/v1/approver/approver.service.ts
  src/app/core/services/platform/v1/approver/expenses.service.spec.ts
  src/app/core/services/platform/v1/approver/expenses.service.ts
  src/app/core/services/platform/v1/shared/date.service.spec.ts
  src/app/core/services/platform/v1/shared/date.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/platform/v1/spender/spender.service.spec.ts
  src/app/core/services/platform/v1/spender/spender.service.ts
  src/app/core/services/router-api.service.ts
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/router-auth.service.ts
Labels: size/XL

#2539 fix: Contains fix for items getting filtered in merchant field : https://app.clickup.com/t/85ztztwg6
  src/app/shared/components/virtual-select/virtual-select.component.spec.ts
  src/app/shared/components/virtual-select/virtual-select.component.ts
  src/app/shared/components/virtual-select/virtual-select.model.ts
Labels: size/M

#2540 feat: Migrate GET of expense to platform models and services changes
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/models/app-supported-details.model.ts
  src/app/core/models/name-value-pair.model.ts
  src/app/core/models/platform/platform-mileage-rates.model.ts
  src/app/core/models/platform/platform-report.model.ts
  src/app/core/models/platform/report-approvals.model.ts
  src/app/core/models/platform/v1/account.model.ts
  src/app/core/models/platform/v1/department.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/platform/v1/file.model.ts
  src/app/core/models/platform/v1/level.model.ts
  src/app/core/models/platform/v1/project.model.ts
  src/app/core/models/platform/v1/user.model.ts
  src/app/core/services/app-version.service.ts
  src/app/core/services/invitation-requests.service.ts
  src/app/core/services/platform/v1/approver/approver.service.spec.ts
  src/app/core/services/platform/v1/approver/approver.service.ts
  src/app/core/services/platform/v1/approver/expenses.service.spec.ts
  src/app/core/services/platform/v1/approver/expenses.service.ts
  src/app/core/services/platform/v1/shared/date.service.spec.ts
  src/app/core/services/platform/v1/shared/date.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/platform/v1/spender/spender.service.spec.ts
  src/app/core/services/platform/v1/spender/spender.service.ts
  src/app/core/services/router-api.service.ts
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/router-auth.service.ts
Labels: size/XL

#2513 feat: Moved GET of /v2/expense to platform in View Mileage
  src/app/core/services/file.service.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/services/mileage-rates.service.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
Labels: size/L

#2514 feat: Moved GET of /v2/expenses to platform in View Per Diem
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/M

#2515 test: Added unit tests for /v2/expenses API migration in View Mileage
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/services/file.service.spec.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
Labels: size/L

#2516 test: Added unit tests for /v2/expenses migration in View Per Diem
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/services/file.service.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/L

#2531 fix: Split Expense Button P0 Fix
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/XS

#2541 feat: Remove holiday field from mock data
  src/app/core/mock-data/dependent-field-expenses.data.ts
  src/app/core/mock-data/expense-v2.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/expenses-info.data.ts
  src/app/core/models/expense.model.ts
Labels: size/S

#2545 test: Code coverage for expenses service spender and approver
  src/app/core/mock-data/platform/v1/expenses-query-params.data.ts
  src/app/core/mock-data/platform/v1/expenses-response.data.ts
  src/app/core/models/platform/v1/expenses-query-params.model.ts
  src/app/core/services/platform/v1/approver/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
Labels: size/M

#2543 feat: Add getReportExpenses service method to fetch all report expenses from platform
  src/app/core/mock-data/platform/v1/expenses-query-params.data.ts
  src/app/core/mock-data/platform/v1/expenses-response.data.ts
  src/app/core/models/platform/v1/expenses-query-params.model.ts
  src/app/core/models/platform/v1/query-params.model.ts
  src/app/core/services/platform/v1/approver/expenses.service.spec.ts
  src/app/core/services/platform/v1/approver/expenses.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
Labels: size/M

#2556 fix: project category mapping is not working properly
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#2558 test: Add tests to shared expense service
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/services/platform/v1/shared/expense.service.spec.ts
Labels: size/M

#2555 fix: failing tests on v2 of expenses card component
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/services/platform/v1/shared/expense.service.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
Labels: size/L

#2552 feat: Created a v2 of expenses card component
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/services/platform/v1/shared/expense.service.spec.ts
  src/app/core/services/platform/v1/shared/expense.service.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#2544 feat: Migrated GET of single expense call via /v2/expenses to platform
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/services/file.service.spec.ts
  src/app/core/services/file.service.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/services/mileage-rates.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
Labels: size/XL

#2533 feat: Moved /etxns/:id in View Expense to Platform
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
Labels: size/L

#2548 test: Added tests for /etxns/:id to platform migration in view expense page
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/services/platform/v1/shared/expense.service.spec.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
Labels: size/XL

#2549 feat: Cleaned up remaining public calls in view expense, per diem and mileage pages
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/M

#2550 test: Added tests for cleanup changes
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
Labels: size/M

#2553 fix: Renamed etxn, tx, txn terminology to expense in view expense, mileage and per diem pages
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/M

#2554 feat: Moved /etxns/:id call in navigation footer component to platform
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/shared/components/navigation-footer/fy-nav-footer/fy-nav-footer.component.html
  src/app/shared/components/navigation-footer/fy-nav-footer/fy-nav-footer.component.spec.ts
  src/app/shared/components/navigation-footer/fy-nav-footer/fy-nav-footer.component.ts
  src/app/shared/components/navigation-footer/navigation-footer.component.html
  src/app/shared/components/navigation-footer/navigation-footer.component.spec.ts
  src/app/shared/components/navigation-footer/navigation-footer.component.ts
Labels: size/M

#2574 feat: Standardize icons - Milestone-1
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.html
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.scss
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
  src/app/shared/components/fy-policy-violation/fy-policy-violation.component.html
  src/app/shared/icon/icon.module.ts
  src/assets/svg/2-users.svg
  src/assets/svg/action-menu.svg
  src/assets/svg/add-advance.svg
  src/assets/svg/add-expense.svg
  src/assets/svg/add-mileage.svg
  src/assets/svg/add-per-diem.svg
  src/assets/svg/auto_fyle.svg
  src/assets/svg/instafyle.svg
  src/assets/svg/list-plus.svg
  src/assets/svg/user-two.svg
  src/assets/svg/vertical-dots-menu.svg
Labels: size/M

#2573 feat: My view report page to use the platform API for report expenses.
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/report.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/M

#2565 feat: Remove unused code from transaction and report service
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/L

#2564 test: Copy tests for shared expenses service from transaction service
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/XL

#2560 fix: Fix failing tests of view team report page
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
Labels: size/XL

#2559 fix: Fix the failing tests on fy-view-report-info component
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.spec.ts
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
Labels: size/M

#2576 feat: Standardize icons - Milestone-3
  src/app/fyle/my-view-report/my-view-report-etxn-card/my-view-report-etxn-card.component.html
  src/app/fyle/my-view-report/my-view-report-etxn-card/my-view-report-etxn-card.component.scss
  src/app/fyle/my-view-report/my-view-report-etxn-card/my-view-report-etxn-card.component.spec.ts
  src/app/fyle/my-view-report/my-view-report-etxn-card/my-view-report-etxn-card.component.ts
  src/app/fyle/my-view-report/my-view-report.module.ts
  src/app/fyle/view-team-report/view-team-report-etxn-card/view-team-report-etxn-card.component.html
  src/app/fyle/view-team-report/view-team-report-etxn-card/view-team-report-etxn-card.component.scss
  src/app/fyle/view-team-report/view-team-report-etxn-card/view-team-report-etxn-card.component.spec.ts
  src/app/fyle/view-team-report/view-team-report-etxn-card/view-team-report-etxn-card.component.ts
  src/app/fyle/view-team-report/view-team-report.module.ts
  src/app/shared/components/fy-category-icon/fy-category-icon.component.html
  src/app/shared/components/fy-category-icon/fy-category-icon.component.scss
  src/app/shared/components/fy-category-icon/fy-category-icon.component.spec.ts
  src/app/shared/components/fy-category-icon/fy-category-icon.component.ts
  src/app/shared/icon/icon.module.ts
  src/app/shared/shared.module.ts
  src/assets/svg/bike.svg
  src/assets/svg/bus.svg
  src/assets/svg/entertainment.svg
  src/assets/svg/flight.svg
  src/assets/svg/food.svg
  src/assets/svg/fy-bike.svg
  src/assets/svg/fy-cyclist.svg
  src/assets/svg/fy-electric-car.svg
  src/assets/svg/gas.svg
  src/assets/svg/hotel.svg
  src/assets/svg/mail.svg
  src/assets/svg/mileage.svg
  src/assets/svg/office-supplies.svg
  src/assets/svg/parking.svg
  src/assets/svg/per_diem.svg
  src/assets/svg/phone.svg
  src/assets/svg/software.svg
  src/assets/svg/taxi.svg
  src/assets/svg/train.svg
  src/assets/svg/utility.svg
Labels: size/XL

#2575 feat: Standardize icons - Milestone-2
  src/app/core/mock-data/sidemenu.data.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
  src/app/fyle/my-view-advance/my-view-advance.page.html
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.html
  src/app/shared/components/expenses-card/expenses-card.component.scss
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/fy-statistic/fy-statistic.component.scss
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/app/shared/icon/icon.module.ts
  src/assets/images/add-to-list.png
  src/assets/svg/add-receipt.svg
  src/assets/svg/add-report.svg
  src/assets/svg/add-to-list.svg
  src/assets/svg/advances.svg
  src/assets/svg/attachment.svg
  src/assets/svg/wallet.svg
Labels: size/M

#2566 feat: Added transaction status info in view expense page
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.scss
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/shared/components/transaction-status-info/transaction-status-info.component.html
  src/app/shared/components/transaction-status-info/transaction-status-info.component.scss
  src/app/shared/components/transaction-status-info/transaction-status-info.component.spec.ts
  src/app/shared/components/transaction-status-info/transaction-status-info.component.ts
  src/app/shared/shared.module.ts
  src/assets/svg/info-circle-outline.svg
Labels: size/L

#2568 feat: Added transaction status in edit expense page
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.scss
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.scss
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.html
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.scss
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.spec.ts
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.ts
  src/app/shared/components/transaction-status/transaction-status.component.html
  src/app/shared/components/transaction-status/transaction-status.component.scss
  src/app/shared/components/transaction-status/transaction-status.component.spec.ts
  src/app/shared/components/transaction-status/transaction-status.component.ts
  src/app/shared/shared.module.ts
Labels: size/L

#2584 test: Transaction status changes remaining branches
  src/app/core/mock-data/org-settings.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/view-expense/view-expense.page.ts
Labels: size/M

#2585 fix: Fix package.json
  package-lock.json
  package.json
Labels: size/L

#2591 feat: Use mileage rates API in view mileage page
  src/app/core/services/mileage-rates.service.spec.ts
  src/app/core/services/mileage-rates.service.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
Labels: size/M

#2592 test: Added parallel tests support
  karma.conf.js
  package-lock.json
  package.json
Labels: size/L

#2583 feat: Standardize icons - Milestone-4
  src/app/shared/icon/icon.module.ts
  src/assets/svg/building.svg
  src/assets/svg/bulk-mode.svg
  src/assets/svg/bulk.svg
Labels: size/XS

#2561 feat: Move view expense to platform combined changes
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/services/file.service.spec.ts
  src/app/core/services/file.service.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/services/mileage-rates.service.spec.ts
  src/app/core/services/mileage-rates.service.ts
  src/app/core/services/platform/v1/shared/expense.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/navigation-footer/fy-nav-footer/fy-nav-footer.component.html
  src/app/shared/components/navigation-footer/fy-nav-footer/fy-nav-footer.component.spec.ts
  src/app/shared/components/navigation-footer/fy-nav-footer/fy-nav-footer.component.ts
  src/app/shared/components/navigation-footer/navigation-footer.component.html
  src/app/shared/components/navigation-footer/navigation-footer.component.spec.ts
  src/app/shared/components/navigation-footer/navigation-footer.component.ts
Labels: size/XL

#2582 feat: Transaction status visibility changes in expenses
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.scss
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.scss
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.html
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.scss
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.spec.ts
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.ts
  src/app/shared/components/transaction-status/transaction-status.component.html
  src/app/shared/components/transaction-status/transaction-status.component.scss
  src/app/shared/components/transaction-status/transaction-status.component.spec.ts
  src/app/shared/components/transaction-status/transaction-status.component.ts
  src/app/shared/shared.module.ts
  src/assets/svg/info-circle-outline.svg
Labels: size/L

#2612 feat: Standardize icons - Milestone-5
  src/app/core/mock-data/sidemenu.data.ts
  src/app/core/models/task-icon.enum.ts
  src/app/core/services/status.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
  src/app/fyle/merge-expense/card-transaction-preview/card-transaction-preview.component.html
  src/app/fyle/my-expenses/add-expense-popover/add-expense-popover.component.html
  src/app/fyle/my-expenses/add-expense-popover/add-expense-popover.component.scss
  src/app/fyle/my-expenses/add-expense-popover/add-expense-popover.component.ts
  src/app/fyle/my-expenses/my-expenses.module.ts
  src/app/shared/components/comments-history/audit-history/audit-history.component.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.scss
  src/app/shared/components/fy-alert/fy-alert.component.html
  src/app/shared/components/fy-alert/fy-alert.component.scss
  src/app/shared/components/fy-alert/fy-alert.component.spec.ts
  src/app/shared/components/fy-alert/fy-alert.component.ts
  src/app/shared/components/fy-policy-violation/fy-policy-violation.component.html
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/app/shared/icon/icon.module.ts
  src/app/shared/shared.module.ts
  src/assets/svg/call.svg
  src/assets/svg/camera-pointer-bottom-left.svg
  src/assets/svg/camera-pointer-bottom-right.svg
  src/assets/svg/camera-pointer-top-left.svg
  src/assets/svg/camera-pointer-top-right.svg
  src/assets/svg/capped-amount.svg
  src/assets/svg/capture.svg
  src/assets/svg/car.svg
  src/assets/svg/card-filled.svg
  src/assets/svg/card.svg
  src/assets/svg/create-expense.svg
  src/assets/svg/create-mileage.svg
  src/assets/svg/create-per-diem.svg
  src/assets/svg/fy-card.svg
  src/assets/svg/fy-cards-new.svg
  src/assets/svg/fy-corporate-card.svg
  src/assets/svg/insta-fyle.svg
  src/assets/svg/phone.svg
  src/assets/svg/plus-minus.svg
Labels: size/L

#2577 test: Move My Create To Platform: Fixing Tests
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
Labels: size/M

#2613 fix: Fixed category dependent location fields not coming up in view expense page
  src/app/fyle/view-expense/view-expense.page.html
Labels: size/XS

#2606 fix: Added fix for cost center not getting assigned upon non-manual selection
  src/app/fyle/merge-expense/merge-expense-2.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XS

#2572 feat: Move My Create Report To Platform: Moved API call of expenses to platform
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/models/platform/v1/expenses-query-params.model.ts
  src/app/core/services/platform/v1/shared/expense.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
Labels: size/L

#2617 feat: Standardize icons - Milestone-6
  src/app/core/services/status.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.html
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.scss
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.scss
  src/app/shared/icon/icon.module.ts
  src/assets/svg/arrow-up-primary.svg
  src/assets/svg/arrow-up.svg
  src/assets/svg/radio-circle-outline.svg
Labels: size/M

#2618 fix: Make the entire transaction status clickable
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/view-expense/view-expense.page.html
  src/app/shared/components/transaction-status/transaction-status.component.html
  src/app/shared/components/transaction-status/transaction-status.component.scss
  src/app/shared/components/transaction-status/transaction-status.component.spec.ts
  src/app/shared/components/transaction-status/transaction-status.component.ts
Labels: size/S

#2623 fix: Fix for the travel class icon on view expense page
  src/app/fyle/view-expense/view-expense.page.html
  src/app/shared/icon/icon.module.ts
  src/assets/svg/bus.svg
  src/assets/svg/train.svg
Labels: size/XS

#2607 feat: Move My Expenses To Platform: Added Route Guard for redirection And Updated Model
  src/app/core/guards/my-expenses-guard.guard.spec.ts
  src/app/core/guards/my-expenses-guard.guard.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/fyle/fyle-routing.module.ts
Labels: size/M

#2603 feat: Move My Expenses to Platform: Fixed Card Filter Param
  src/app/core/guards/my-expenses-guard.guard.spec.ts
  src/app/core/guards/my-expenses-guard.guard.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/services/platform/v1/shared/expense.service.ts
  src/app/fyle/fyle-routing.module.ts
Labels: size/M
