Repository fylein/fyle-mobile-app, pull requests merged in 2023-03, with the labels that each got.

#1772 feat: Add pr size label
  .github/workflows/pr-size-label.yml
Labels: size/S

#1777 feat: Persist Show More in add mileage and add perdiem
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/M

#1759 fix: Show more fix
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/M

#1779 fix: Dependent Fields: Fix issues found during testing
  src/app/core/models/platform/dependent-field-values-api-params.model.ts
  src/app/core/services/dependent-fields.service.ts
  src/app/core/test-data/dependent-fields.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/dependent-field/dependent-field-modal/dependent-field-modal.component.html
  src/app/shared/components/dependent-field/dependent-field-modal/dependent-field-modal.component.ts
  src/app/shared/components/dependent-field/dependent-field.component.scss
  src/app/shared/components/dependent-field/dependent-field.component.ts
Labels: size/M

#1763 test: Code coverage: Merge expenses service - 50%
  src/app/core/mock-data/corporate-card-expense.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/expenses-info.data.ts
  src/app/core/mock-data/file-object.data.ts
  src/app/core/mock-data/merge-expenses-custom-inputs.data.ts
  src/app/core/mock-data/merge-expenses-option.data.ts
  src/app/core/mock-data/merge-expenses-options-data.data.ts
  src/app/core/models/v1/extended-project.model.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/test-data/projects.spec.data.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XL

#1778 test: Location Service 50% coverage
  src/app/core/services/location.service.spec.ts
Labels: size/M

#1781 test: Code Coverage: Google Auth Service #1
  src/app/core/mock-data/auth-reponse.data.ts
  src/app/core/models/auth-response.model.ts
  src/app/core/services/google-auth.service.spec.ts
Labels: size/M

#1757 feat: Sign In Page Design Update size/S
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/sign-in/sign-in.page.scss
  src/assets/svg/fyle-logo-black.svg
  src/assets/svg/google-logo.svg
  src/theme/colors.scss
Labels: size/M

#1771 test: Code Coverage: Approver Platform API Service
  src/app/core/services/approver-platform-api.service.spec.ts
Labels: size/M

#1782 test: Code coverage - Token service - 100% branches
  src/app/core/services/token.service.spec.ts
Labels: size/M

#1764 test: Code Coverage: Auth Service #1
  src/app/core/mock-data/acess-token-data.data.ts
  src/app/core/mock-data/extended-org-user.data.ts
  src/app/core/models/access-token-data.model.ts
  src/app/core/models/eou-api-response.model.ts
  src/app/core/services/auth.service.spec.ts
  src/app/core/services/auth.service.ts
Labels: size/L

#1788 test: Code coverage 100% data transform service
  src/app/core/mock-data/data-transform.data.ts
  src/app/core/services/data-transform.service.spec.ts
Labels: size/M

#1789 test: Code Coverage: Permission Service
  src/app/core/services/permissions.service.spec.ts
  src/app/core/services/permissions.service.ts
Labels: size/M

#1792 test: Added test for an old issue in accounts service
  src/app/core/services/accounts.service.spec.ts
  src/app/core/test-data/accounts.service.spec.data.ts
Labels: size/M

#1793 test: Code coverage: EditReportNamePopover Component - 100%
  src/app/core/dom-helpers.ts
  src/app/fyle/my-view-report/edit-report-name-popover/edit-report-name-popover.component.html
  src/app/fyle/my-view-report/edit-report-name-popover/edit-report-name-popover.component.spec.ts
Labels: size/M

#1796 test: Code Coverage: Active Org Card Component
  src/app/auth/switch-org/active-org-card/active-org-card.component.spec.ts
Labels: size/M

#1795 test: Code Coverage: Fy-Header Component
  src/app/shared/components/fy-header/fy-header.component.spec.ts
Labels: size/M

#1786 fix: Update info.plist to avoid encryption confirmation popover when deploying ios app
  hooks/utils/ios-info.js
Labels: size/XS

#1798 fix: Dependent fields: Send projectv2_name to api when getting dependent firlds
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/XS

#1799 fix: Active Org Card Component
  src/app/auth/switch-org/active-org-card/active-org-card.component.spec.ts
Labels: size/XS

#1794 test: FyConnection Comppnent 100% coverage
  src/app/shared/components/fy-connection/fy-connection.component.spec.ts
Labels: size/M

#1801 fix: Dependent Fields: Remove project dep fields when splitting expense by project
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/M

#1806 test: Code Coverage : Config Service 100%
  src/app/core/services/config.service.spec.ts
Labels: size/M

#1809 test: Code coverage Refiner Service 67%
  src/app/core/services/refiner.service.spec.ts
Labels: size/M

#1807 test: Code Coverage: Log Info Service #1
  src/app/core/services/date.service.spec.ts
  src/app/core/services/login-info.service.spec.ts
  src/app/core/services/login-info.service.ts
Labels: size/M

#1734 fix:State name changes to report modals, view expense pages || Simplified report closure
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.html
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
  src/app/shared/pipes/expense-state.pipe.ts
Labels: size/M

#1773 fix:Dashboard stats changes for Simplified report closure
  src/app/core/mock-data/org-payment-mode-settings.data.ts
  src/app/core/mock-data/report-stats.data.ts
  src/app/core/mock-data/stats-response.data.ts
  src/app/core/models/report-stats.model.ts
  src/app/core/services/payment-modes.service.spec.ts
  src/app/core/services/payment-modes.service.ts
  src/app/fyle/dashboard/dashboard.service.ts
  src/app/fyle/dashboard/stat-badge/report-states.ts
  src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.ts
Labels: size/M

#1803 test: Code coverage: Secure storage service - Initial changes
  src/app/core/services/secure-storage.service.spec.ts
Labels: size/XS

#1802 test: Code coverage - Utility service - 64% statements
  src/app/core/mock-data/custom-field.data.ts
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
Labels: size/M

#1810 test: Code coverage add more popup component 100%
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.spec.ts
Labels: size/M

#1804 test: Code coverage: Merge expenses service - Final PR
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/merge-expenses-option.data.ts
  src/app/core/mock-data/merge-expenses-options-data.data.ts
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/tax-group.data.ts
  src/app/core/models/merge-expenses-options-data.model.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XL

#1723 feat:State name changes for Simplified Report Closure
  src/app/core/mock-data/org-payment-mode-settings.data.ts
  src/app/core/mock-data/report-stats.data.ts
  src/app/core/mock-data/stats-response.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/report-stats.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/payment-modes.service.spec.ts
  src/app/core/services/payment-modes.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/dashboard/dashboard.service.ts
  src/app/fyle/dashboard/stat-badge/report-states.ts
  src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.ts
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports-card/my-reports-card.component.html
  src/app/fyle/my-reports/my-reports-card/my-reports-card.component.ts
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/team-reports/team-report-card/team-report-card.component.html
  src/app/fyle/team-reports/team-report-card/team-report-card.component.ts
  src/app/fyle/team-reports/team-reports.page.html
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.html
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
  src/app/shared/components/fy-filter-pills/fy-filter-pills.component.html
  src/app/shared/components/fy-filters/filter-options.interface.ts
  src/app/shared/components/fy-filters/fy-filters.component.html
  src/app/shared/components/fy-filters/fy-filters.component.scss
  src/app/shared/components/fy-filters/fy-filters.component.ts
  src/app/shared/pipes/expense-state.pipe.ts
  src/app/shared/pipes/report-state.pipe.spec.ts
  src/app/shared/pipes/report-state.pipe.ts
  src/app/shared/shared.module.ts
Labels: size/L

#1811 test: Code coverage: FyAlertInfo Component - 100%
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.spec.ts
  src/app/shared/components/fy-alert-info.component.html/fy-alert-info.component.spec.ts
Labels: size/M

#1812 test: Code coverage: FyNavFooter Component - 100%
  src/app/shared/components/navigation-footer/fy-nav-footer/fy-nav-footer.component.spec.ts
Labels: size/M

#1815 test: Code Coverage: View Team Report ETXN Card Component
  src/app/fyle/view-team-report/view-team-report-etxn-card/view-team-report-etxn-card.component.spec.ts
Labels: size/M

#1813 test: Code coverage Refiner Service 77.5%
  src/app/core/services/refiner.service.spec.ts
  src/app/core/services/refiner.service.ts
Labels: size/S

#1819 test: Code Coverage Policy Violation Dialog 100%
  src/app/fyle/add-edit-advance-request/policy-violation-dialog/policy-violation-dialog.component.spec.ts
Labels: size/M

#1783 feat: Github action to trigger prod internal release
  .github/workflows/internal-release.yml
Labels: size/M

#1817 test: Code coverage: Gmaps Service - Initial test
  src/app/core/services/gmaps.service.spec.ts
Labels: size/S

#1820 test: Code Coverage: Launch Darkly Service
  src/app/core/mock-data/ld-all-flags.data.ts
  src/app/core/mock-data/ld-client-user.data.ts
  src/app/core/services/launch-darkly.service.spec.ts
Labels: size/M

#1823 test: Code coverage 100% Toast-message component
  src/app/shared/components/toast-message/toast-message.component.spec.ts
Labels: size/M

#1825 fix: Added imports to avoid warnings Policy Violation Dialog component
  src/app/fyle/add-edit-advance-request/policy-violation-dialog/policy-violation-dialog.component.spec.ts
Labels: size/XS

#1824 fix: Code Coverage: Launch Darkly Service #2
  src/app/core/services/launch-darkly.service.spec.ts
Labels: size/XS

#1821 test: Code Coverage: Network Service
  src/app/core/services/network.service.spec.ts
Labels: size/S

#1827 test: Code coverage: Smartlook Service
  src/app/core/mock-data/extended-device-info.data.ts
  src/app/core/services/smartlook.service.spec.ts
Labels: size/M

#1830 test: Code coverage 63% Timezone service
  src/app/core/services/timezone.service.spec.ts
  src/app/core/services/timezone.service.ts
Labels: size/M

#1826 fix: Fix some sentry issues
  src/app/auth/sign-in/sign-in.page.ts
  src/app/core/services/custom-inputs.service.ts
  src/app/core/services/popup.service.ts
  src/app/core/services/projects.service.ts
  src/app/fyle/add-edit-advance-request/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.html
Labels: size/M

#1832 test: Code Coverage Timezone Service 93%
  src/app/core/services/timezone.service.spec.ts
Labels: size/S

#1816 feat: Dependent Fields: Refactoring
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.html
  src/app/shared/components/dependent-fields/dependent-fields.component.ts
Labels: size/M

#1831 feat: Add trackers for sidemenu and home tab
  src/app/core/services/tracking.service.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/my-advances/my-advances.page.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/fyle/team-advance/team-advance.page.ts
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/shared/components/fy-header/fy-header.component.spec.ts
  src/app/shared/components/fy-menu-icon/fy-menu-icon.component.html
  src/app/shared/components/fy-menu-icon/fy-menu-icon.component.spec.ts
  src/app/shared/components/fy-menu-icon/fy-menu-icon.component.ts
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.ts
Labels: size/M

#1837 test: Code coverage: Transaction outbox service - PR-1
  src/app/core/services/transactions-outbox.service.spec.ts
  src/app/core/services/transactions-outbox.service.ts
Labels: size/M

#1835 test: Code Coverage: App Version Service
  src/app/core/mock-data/app-version.data.ts
  src/app/core/services/app-version.service.spec.ts
  src/app/core/services/app-version.service.ts
Labels: size/M

#1829 test: Code Coverage: Fresh Chat Service
  src/app/core/services/fresh-chat.service.spec.ts
Labels: size/M

#1841 test: Code coverage: Transaction outbox service - changes-2
  src/app/core/services/transactions-outbox.service.spec.ts
Labels: size/S

#1840 test: Code Coverage: Router Auth Service
  src/app/core/mock-data/auth-reponse.data.ts
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/router-auth.service.ts
Labels: size/L

#1838 feat: Create release branch automatically every friday at 5 PM
  .github/workflows/create-release-branch.yml
Labels: size/S

#1844 test: Code Coverage: Fy-Zero State Component
  src/app/shared/components/fy-zero-state/fy-zero-state.component.spec.ts
Labels: size/M

#1845 test: Code Coverage: Fy-Critical Violation Component
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.spec.ts
Labels: size/M

#1846 test: Code Coverage 100% team advance card component
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.spec.ts
Labels: size/M

#1847 test: Code Coverage: Fy-Input Popover Component
  src/app/shared/components/fy-input-popover/fy-input-popover.component.spec.ts
Labels: size/M

#1848 fix: Fix projects not visible in mobile app
  src/app/core/services/projects.service.ts
Labels: size/XS

#1842 test: Code Coverage 100% Footer component
  src/app/shared/components/footer/footer.component.spec.ts
Labels: size/M

#1833 feat: Optimization for setupFormInit
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/platform-api-category.data.ts
  src/app/core/services/categories.service.spec.ts
  src/app/core/services/categories.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#1849 test: Code coverage Review footer component 100%
  src/app/shared/components/review-footer/review-footer.component.spec.ts
Labels: size/M

#1850 test: Code coverage: Send email component
  src/app/shared/components/send-email/send-email.component.spec.ts
Labels: size/M

#1851 test: Code Coverage: Fy-Policy Violation Info Component
  src/app/core/mock-data/individual-expense-policy-state.data.ts
  src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.spec.ts
Labels: size/M

#1853 fix: Resolved import related error
  src/app/shared/components/review-footer/review-footer.component.spec.ts
Labels: size/XS

#1852 test: Code Coverage ShareReport Component - Team
  src/app/fyle/view-team-report/share-report/share-report.component.spec.ts
Labels: size/M

#1854 test: Code coverage: PopupAlert Component
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/services/back-button.service.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.ts
  src/app/shared/components/popup-alert-component/popup-alert-component.component.spec.ts
  src/app/shared/components/popup-alert/popup-alert.component.html
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/app/shared/components/popup-alert/popup-alert.component.spec.ts
  src/app/shared/components/popup-alert/popup-alert.component.ts
  src/app/shared/shared.module.ts
Labels: size/M

#1785 feat: Dependent Fields: Create new component for dependent fields
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.html
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.scss
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.spec.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.html
  src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.scss
  src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.spec.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.html
  src/app/shared/components/dependent-fields/dependent-fields.component.scss
  src/app/shared/components/dependent-fields/dependent-fields.component.spec.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#1858 feat: expense rule applied info in audit trails
  src/app/core/services/status.service.ts
  src/app/shared/icon/icon.module.ts
  src/assets/svg/expense-rule.svg
Labels: size/XS

#1862 test: Code Coverage: My Advances Card Component
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.spec.ts
Labels: size/M

#1856 test: Code Coverage: Fy-Approver Component
  src/app/shared/components/fy-approver/fy-approver.component.spec.ts
Labels: size/M

#1863 test: Code Coverage: Card Detail Component
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
Labels: size/M

#1855 fix: Offline state appearing twice on Home Screen
  src/app/fyle/dashboard/stats/stats.component.html
Labels: size/XS

#1864 fix: Code Coverage: My Advances Card Component
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.spec.ts
Labels: size/XS

#1861 fix: Fix issue in edit expense and add refactoring changes to mileage/per-diem
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/dependent-fields/dependent-fields.component.ts
Labels: size/M

#1857 feat: Add github action to trigger staging live update
  .github/workflows/live-update.yml
Labels: size/M

#1866 fix: Disabling a test which fails at times
  src/app/shared/components/popup-alert/popup-alert.component.spec.ts
Labels: size/XS

#1867 test: Code coverage 100% Sidemenu ContentItem Component
  src/app/core/mock-data/sidemenu-item.data.ts
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.spec.ts
Labels: size/M

#1868 test: updated status service mock data for expense rule comment
  src/app/core/test-data/status.service.spec.data.ts
Labels: size/S

#1865 test: Code Coverage: Reset Password Component
  src/app/auth/reset-password/reset-password.page.spec.ts
Labels: size/M
