Repository fylein/fyle-mobile-app, pull requests merged in 2024-11, with the labels that each got.

#3239 fix: disabled customfield hide and historical view
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/services/custom-inputs.service.spec.ts
  src/app/core/services/custom-inputs.service.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/M

#3251 test: Fix failing tests for move expenses POST to platform
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/L

#3245 fix: retain receipt when editing, remove code for advance wallet id, set unspecified category id
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/S

#3253 fix: modify the default values for select and multi select custom fields
  src/app/core/services/custom-fields.service.ts
Labels: size/XS

#3254 reword transction to expense
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XS

#3249 feat: add mobile app release version in Sentry issues
  .eslintrc.json
  hooks/prebuild.js
  src/main.ts
Labels: size/XS

#3250 feat: Removing url query params from Http exception for correct grouping of issues in Sentry
  src/main.ts
Labels: size/S

#3252 fix:the edit report-name input should remain in focus
  src/app/fyle/my-view-report/edit-report-name-popover/edit-report-name-popover.component.html
  src/app/fyle/my-view-report/edit-report-name-popover/edit-report-name-popover.component.ts
Labels: size/XS

#3256 fix:fixing the toast notification icon style
  src/assets/svg/check-circle-outline.svg
Labels: size/XS

#3255 fix:showing the expense value in the sub-title inside create new report
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
Labels: size/XS

#3257 fix: Change env variable REFINER_NPS_PROJECT_ID -> REFINER_NPS_FORM_PROJECT
  hooks/utils/prod-environment.js
  src/app/core/services/refiner.service.ts
  src/environments/environment.ts
Labels: size/XS

#3258 fix: Set default values for custom fields, location field and fix edit expense custom fields
  src/app/core/models/custom-input-options.model.ts
  src/app/core/models/custom-input.model.ts
  src/app/core/models/custom-inputs-option.model.ts
  src/app/core/models/custom_field.model.ts
  src/app/core/models/txn-custom-properties.model.ts
  src/app/core/services/custom-fields.service.ts
  src/app/core/services/custom-inputs.service.spec.ts
  src/app/core/services/custom-inputs.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#3259 fix: migrate personalCards:getLinkedAccounts to platform
  src/app/core/mock-data/personal-cards.data.ts
  src/app/core/models/personal_card.model.ts
  src/app/core/models/personal_card_platform.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/environments/environment.ts
Labels: size/L

#3261 fix: minor comment
  src/app/fyle/personal-cards/personal-cards.page.html
Labels: size/XS

#3263 fix: interceptor fixes to make new call if access_token is not present and not throw access_token errors to sentry
  src/app/core/interceptors/httpInterceptor.spec.ts
  src/app/core/interceptors/httpInterceptor.ts
Labels: size/XS

#3264 fix: LIVE_UPDATE_APP_VERSION for Sentry release instead of FYLE_MOBILE_RELEASE_VERSION
  hooks/prebuild.js
  src/main.ts
Labels: size/XS

#3266 fix: migrate delete personal card api to platform
  src/app/core/mock-data/personal-cards.data.ts
  src/app/core/models/platform/platform-api-response.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.spec.ts
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
Labels: size/M

#3265 fix: remove unmatch personal card feature
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.html
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/M

#3267 fix: adding live update version for sentry release in build script
  build_appflow.sh
Labels: size/XS

#3268 fix: throwing 401 singin related errors back from interceptor
  src/app/core/interceptors/httpInterceptor.ts
Labels: size/XS

#3269 fix: Added the regex for discarding the sentry issues
  src/main.ts
Labels: size/XS

#3262 fix: Set custom fields based on unspecified category id if no category selected
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XL

#3270 fix:replacing page title from Dashboard to Home
  src/app/core/mock-data/sidemenu-item.data.ts
  src/app/core/mock-data/sidemenu.data.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/XS

#3273 fix: Switch to macOS 2024.04 for prod internal release
  .github/workflows/appflow-release-branch.yml
Labels: size/XS

#3275 fix: Switch to mac os 2024 04 prod
  .github/workflows/appflow-master.yml
  .github/workflows/appflow-release-branch.yml
  .github/workflows/internal-release.yml
  .github/workflows/manual-appflow-1.yml
  .github/workflows/manual-appflow-with-inputs.yml
Labels: size/XS

#3272 fix: Bug in personal cards initialization
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/M

#3278 chore: ignoring plugins not implemented on web errors in Sentry
  src/main.ts
Labels: size/XS

#3277 fix:Change the header for multi-select of expense inside my-expense
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.scss
Labels: size/XS

#3242 feat: Fyle expenses post main
  README.md
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/txn-custom-properties.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/custom-input-options.model.ts
  src/app/core/models/custom-input.model.ts
  src/app/core/models/custom-inputs-option.model.ts
  src/app/core/models/custom_field.model.ts
  src/app/core/models/receipt-detail.model.ts
  src/app/core/models/txn-custom-properties.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/custom-fields.service.spec.ts
  src/app/core/services/custom-fields.service.ts
  src/app/core/services/custom-inputs.service.spec.ts
  src/app/core/services/custom-inputs.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.spec.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/XL

#3283 feat: Update README
  README.md
Labels: size/L

#3276 fix: per diem page to use the advanced_per_diem_settings
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/M

#3280 fix:updating style and position for the camera icon
  src/app/shared/components/footer/footer.component.scss
Labels: size/XS

#3279 fix: migrate list personal card transactions to platform
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/mock-data/personal-cards.data.ts
  src/app/core/models/personal_card_txn.model.ts
  src/app/core/models/platform/platform-personal-card-matched-expense.model.ts
  src/app/core/models/platform/platform-personal-card-query-params.model.ts
  src/app/core/models/platform/platform-personal-card-txn-state.enum.ts
  src/app/core/models/platform/platform-personal-card-txn.model.ts
  src/app/core/models/platform/platform-personal-card.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/XL

#3287 fix: migrate hideTransactions api to platform
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/M

#3288 fix: migrate matchExpenses to platform
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
Labels: size/M

#3284 feat: Remove error state from verify page
  src/app/auth/verify/verify.page.html
  src/app/auth/verify/verify.page.scss
  src/app/auth/verify/verify.page.spec.ts
  src/app/auth/verify/verify.page.ts
  src/assets/svg/loader.svg
Labels: size/M
