Repository fylein/fyle-mobile-app, pull requests merged in 2024-03, with the labels that each got.

#2787 test: flaky test fixes
  .github/workflows/unit-tests.yml
  src/app/core/services/org-settings.service.spec.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-view-report/share-report/share-report.component.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.spec.ts
  src/app/shared/components/route-visualizer/route-visualizer.component.spec.ts
Labels: size/M

#2796 fix:duplicate-detection-v2 settings cleanup
  src/app/core/models/org-settings.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
Labels: size/S

#2797 feat: Added filtering of pending txns in tasks if pending restriction is enabled from org settings.
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
Labels: size/M

#2805 test: fixed unit tests after cleanup for deprecated keys and methods
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
Labels: size/L

#2803 fix: cleanup of depreacted keys and methods
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/L

#2802 test: fixed unit test for the methods getEtxnc, getTransactionStats, getEtxn and getAllETxnc migrated to platform
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/platform/v1/expense-duplicate-sets.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/platform/v1/expenses-query-params.data.ts
  src/app/core/mock-data/platform/v1/expenses-stats.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/expense.model.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/merge-expense/merge-expense-1.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.setup.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
Labels: size/XL

#2764 feat: Migrated the method getTransactionStats to platform
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/platform/v1/expense-duplicate-sets.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/platform/v1/expenses-query-params.data.ts
  src/app/core/mock-data/platform/v1/expenses-stats.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/expense.model.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/merge-expense/merge-expense-1.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.setup.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
Labels: size/XL

#2762 feat: Migrated the method getAllEtxnc to platform
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/platform/v1/expense-duplicate-sets.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/platform/v1/expenses-query-params.data.ts
  src/app/core/mock-data/platform/v1/expenses-stats.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/expense.model.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/merge-expense/merge-expense-1.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.setup.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
Labels: size/XS

#2760 feat: Migrated the method getEtxn to platform
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/platform/v1/expense-duplicate-sets.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/platform/v1/expenses-query-params.data.ts
  src/app/core/mock-data/platform/v1/expenses-stats.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/expense.model.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/services/expenses-info.model.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/merge-expense/merge-expense-1.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.setup.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
Labels: size/XL

#2759 feat: Migrated the method getAllExpenses to platform
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/platform-expense.data.ts
  src/app/core/mock-data/platform/v1/expense-duplicate-sets.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/platform/v1/expenses-query-params.data.ts
  src/app/core/mock-data/platform/v1/expenses-stats.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/expense.model.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/services/expenses-info.model.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/merge-expense/merge-expense-1.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.setup.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
Labels: size/XL

#2801 feat: tasks added for showing Add Commute Details
  src/app/core/mock-data/commute-details-response.data.ts
  src/app/core/models/task-event.enum.ts
  src/app/core/models/task-icon.enum.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.ts
Labels: size/M

#2800 feat: refractoring in my-profile page
  src/app/core/mock-data/commute-details-response.data.ts
  src/app/core/models/task-event.enum.ts
  src/app/core/models/task-icon.enum.ts
  src/app/core/services/platform/v1/spender/employees.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.ts
Labels: size/M

#2799 feat: fy-select-commute-details business logic
  src/app/core/mock-data/commute-details-response.data.ts
  src/app/core/models/platform/v1/commute-details.model.ts
  src/app/core/models/task-event.enum.ts
  src/app/core/models/task-icon.enum.ts
  src/app/core/services/platform/v1/spender/employees.service.spec.ts
  src/app/core/services/platform/v1/spender/employees.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.ts
Labels: size/L

#2795 feat: fy-select-commute-details modal as shared component
  src/app/core/mock-data/commute-details-response.data.ts
  src/app/core/models/platform/v1/commute-details.model.ts
  src/app/core/models/task-event.enum.ts
  src/app/core/models/task-icon.enum.ts
  src/app/core/services/platform/v1/spender/employees.service.spec.ts
  src/app/core/services/platform/v1/spender/employees.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.html
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.scss
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.spec.ts
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.ts
  src/app/shared/shared.module.ts
Labels: size/L

#2789 feat: Added Condition for restricting pending txns
  src/app/core/mock-data/platform/v1/expenses-query-params.data.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/shared/expenses.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.html
  src/app/shared/components/create-new-report/create-new-report.component.html
Labels: size/XL

#2808 fix: added the optional chaning for recentCategoriesOriginal
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#2810 fix: removed the ccc_group_id
  src/app/core/models/generated-form-properties.model.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XS

#2809 feat: Added Trackers
  src/app/core/services/tracking.service.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
Labels: size/XS

#2812 fix: revert - removed the ccc_group_id
  src/app/core/models/generated-form-properties.model.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XS

#2819 test: unit test fix for shared/expenses
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
Labels: size/XL

#2817 feat: removed old my-expenses page (deprecation) - Part 4
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/shared/expenses.service.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
Labels: size/XS

#2816 feat: removed old my-expenses page (deprecation) - Part 3
  src/app/core/guards/my-expenses-guard.guard.spec.ts
  src/app/core/guards/my-expenses-guard.guard.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/shared/expenses.service.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
Labels: size/M

#2815 feat: removed old my-expenses page (deprecation) - Part 2
  src/app/core/guards/my-expenses-guard.guard.spec.ts
  src/app/core/guards/my-expenses-guard.guard.ts
  src/app/core/mock-data/expense-filters.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/models/platform/expense-filters.model.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/shared/expenses.service.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/dashboard/stats/stats.component.spec.ts
  src/app/fyle/dashboard/stats/stats.component.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/fyle-routing.module.ts
  src/app/fyle/my-expenses/add-expense-popover/add-expense-popover.component.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.spec.ts
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.ts
  src/app/fyle/my-expenses/my-expenses-filters.model.ts
  src/app/fyle/my-expenses/my-expenses-routing.module.ts
  src/app/fyle/my-expenses/my-expenses.module.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.scss
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-expenses/my-expenses.service.spec.ts
  src/app/fyle/my-expenses/my-expenses.service.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
Labels: size/M

#2814 feat: removed old my-expenses page (deprecation)
  .github/workflows/unit-tests.yml
  src/app/core/guards/my-expenses-guard.guard.spec.ts
  src/app/core/guards/my-expenses-guard.guard.ts
  src/app/core/mock-data/expense-filters.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/models/expense-filters.model.ts
  src/app/core/models/platform/expense-filters.model.ts
  src/app/core/models/report-filters.model.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/shared/expenses.service.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/dashboard/stats/stats.component.spec.ts
  src/app/fyle/dashboard/stats/stats.component.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/fyle-routing.module.ts
  src/app/fyle/my-expenses-v2/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses-v2/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
  src/app/fyle/my-expenses-v2/add-txn-to-report-dialog/add-txn-to-report-dialog.component.spec.ts
  src/app/fyle/my-expenses-v2/add-txn-to-report-dialog/add-txn-to-report-dialog.component.ts
  src/app/fyle/my-expenses-v2/my-expenses-routing.module.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.module.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.html
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.scss
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
  src/app/fyle/my-expenses-v2/my-expenses.service.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses.service.ts
  src/app/fyle/my-expenses/add-expense-popover/add-expense-popover.component.html
  src/app/fyle/my-expenses/my-expenses-filters.model.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-expenses/my-expenses.service.spec.ts
  src/app/fyle/my-expenses/my-expenses.service.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
Labels: size/XL

#2822 fix: Updated the key mapping for corporate_credit_card_expense_group_id
  src/app/core/services/transaction.service.ts
Labels: size/XS

#2824 fix:removed getTransactionStats()
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
Labels: size/M

#2825 fix: added the api call for getting matched_corporate_card_transactions
  src/app/core/mock-data/corporate-card-transaction-response.data.ts
  src/app/core/models/platform/v1/cc-transaction.model.ts
  src/app/core/models/platform/v1/corporate-card-transaction-res.model.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/L

#2829 feat: Remove additional shimmer
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
Labels: size/XS

#2826 fix: distance can be zero and fix for commute deduction mandatory message
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/shared/components/route-selector/route-selector.component.ts
Labels: size/XS

#2823 fix: mandatory as per txnFields
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.html
  src/app/shared/components/route-selector/route-selector.component.html
  src/app/shared/components/route-selector/route-selector.component.ts
Labels: size/M

#2820 feat: popover confirmation once commute is updated from form
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.html
  src/app/shared/components/route-selector/route-selector.component.html
  src/app/shared/components/route-selector/route-selector.component.ts
Labels: size/M

#2807 feat: add-edit-mileage changes for commute-details
  src/app/core/enums/commute-deduction.enum.ts
  src/app/core/models/commute-deduction-options.model.ts
  src/app/core/models/mileage-form-value.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/mileage.service.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/shared/components/fy-select/fy-select.component.ts
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.html
  src/app/shared/components/route-selector/route-selector.component.html
  src/app/shared/components/route-selector/route-selector.component.spec.ts
  src/app/shared/components/route-selector/route-selector.component.ts
  src/global.scss
Labels: size/L

#2828 feat: commute deduction in view mileage
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.ts
Labels: size/S

#2827 test: fixed unit tests for handle_ccc_expense method
  src/app/core/mock-data/cc-transaction.data.ts
  src/app/core/mock-data/matchedCCTransaction.data.ts
  src/app/core/mock-data/transformed-expense.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/L

#2830 fix: disable manual entry in fy-select-commute-details and show toast message if error occurs
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.html
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
  src/app/shared/components/fy-location/fy-location.component.ts
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.html
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.ts
Labels: size/M

#2831 test: test for ionViewWillEnter method in mileage page - Part 1
  src/app/core/mock-data/commute-deduction-options.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/M

#2834 test: added test for newly added methods - Part 4
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
Labels: size/M

#2833 test: fixing route-selector component tests - Part 3
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/shared/components/route-selector/route-selector.component.spec.ts
Labels: size/M

#2832 test: fixing failing tests in mileage page - Part 2
  src/app/core/mock-data/commute-details.data.ts
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/shared/components/fy-location/fy-location.component.spec.ts
  src/app/shared/components/route-selector/route-selector.component.spec.ts
Labels: size/M

#2836 feat: added trackers for commute deduction
  src/app/core/services/tracking.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.ts
Labels: size/M

#2806 feat: This is the base branch for commute details related changes
  .github/workflows/unit-tests.yml
  src/app/core/enums/commute-deduction.enum.ts
  src/app/core/mock-data/commute-deduction-options.data.ts
  src/app/core/mock-data/commute-details-response.data.ts
  src/app/core/mock-data/commute-details.data.ts
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/commute-deduction-options.model.ts
  src/app/core/models/mileage-form-value.model.ts
  src/app/core/models/platform/v1/commute-details.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/task-event.enum.ts
  src/app/core/models/task-icon.enum.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/mileage.service.ts
  src/app/core/services/platform/v1/spender/employees.service.spec.ts
  src/app/core/services/platform/v1/spender/employees.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.html
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
  src/app/shared/components/fy-location/fy-location.component.spec.ts
  src/app/shared/components/fy-location/fy-location.component.ts
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.html
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.scss
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.spec.ts
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.ts
  src/app/shared/components/fy-select/fy-select.component.ts
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.html
  src/app/shared/components/route-selector/route-selector.component.html
  src/app/shared/components/route-selector/route-selector.component.spec.ts
  src/app/shared/components/route-selector/route-selector.component.ts
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/XL

#2837 fix: some QA fixes
  .github/workflows/unit-tests.yml
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.html
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.spec.ts
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts
  src/app/shared/components/route-selector/route-selector.component.html
  src/app/shared/components/route-selector/route-selector.component.ts
Labels: size/M

#2839 fix: correctly calculate distance if roundTrip is present
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts
Labels: size/XS

#2842 feat: Added Addition headers
  src/app/core/interceptors/httpInterceptor.ts
Labels: size/XS

#2838 fix:removed unused /etxns APIs
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
Labels: size/M

#2844 feat: removed query param from x-page-url
  src/app/core/interceptors/httpInterceptor.ts
Labels: size/XS

#2845 feat: added tracker for split expenses
  src/app/core/services/tracking.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS
