Repository fylein/fyle-mobile-app, pull requests merged in 2024-08, with the labels that each got.

#3156 feat: Move share report to platform
  src/app/core/mock-data/export-payload.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/models/platform/export-payload.model.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/M

#3159 feat: fix projects search using display_name
  src/app/core/mock-data/platform/v1/platform-projects-params.data.ts
  src/app/core/models/platform/v1/platform-project-params.model.ts
  src/app/core/services/projects.service.ts
Labels: size/XS

#3158 feat: Added sourcemap collection to sentry during build
  .gitignore
  package-lock.json
  package.json
  src/main.ts
Labels: size/XL

#3163 fix: Added sentry to appflow command
  build_appflow.sh
Labels: size/XS

#3161 fix: truncate long report names
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.html
Labels: size/XS

#3160 feat: remove unused service refs for Report Service
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/deep-link-redirection/deep-link-redirection.page.spec.ts
  src/app/deep-link-redirection/deep-link-redirection.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports-2.page.spec.ts
  src/app/fyle/team-reports/team-reports-3.page.spec.ts
  src/app/fyle/team-reports/team-reports-4.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.spec.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
Labels: size/M

#3165 feat: remove segment and use mixpanel directly
  package-lock.json
  package.json
  src/app/core/services/tracking.service.ts
  src/environments/environment.ts
  src/index.html
Labels: size/L

#3166 fix: Notifications page fixes
  src/app/fyle/notifications/notifications.page.html
  src/app/fyle/notifications/notifications.page.scss
Labels: size/XS

#3168 fix: add mixpanel project token in prod-environment.js
  hooks/utils/prod-environment.js
Labels: size/XS

#3169 fix: ordering expense fields based on seq so that the filtering config based on category is correct everytime
  src/app/core/services/expense-fields.service.ts
Labels: size/XS

#3167 fix: replace cached EOU object with an API call on settings page
  src/app/core/services/app-version.service.spec.ts
  src/app/core/services/app-version.service.ts
Labels: size/XS

#3170 feat: Modified PR checks
  .github/pull_request_template.md
  .github/workflows/pr-checks-config.yml
Labels: size/XS

#3171 fix: complete method typeerror
  src/app/fyle/team-reports/team-reports.page.ts
Labels: size/XS

#3172 fix: Replace public implementation to display delegatee info with platform
  src/app/core/mock-data/extended-org-user.data.ts
  src/app/core/mock-data/platform/v1/delegator.data.ts
  src/app/core/mock-data/platform/v1/platform-employee.data.ts
  src/app/core/models/employee-params.model.ts
  src/app/core/models/platform/delegatee.model.ts
  src/app/core/models/platform/delegation-type.enum.ts
  src/app/core/models/platform/delegator.model.ts
  src/app/core/models/platform/platform-employee.model.ts
  src/app/core/services/org-user.service.spec.ts
  src/app/core/services/org-user.service.ts
  src/app/core/services/platform/v1/spender/employees.service.spec.ts
  src/app/core/services/platform/v1/spender/employees.service.ts
  src/app/fyle/delegated-accounts/delegated-accounts.page.html
  src/app/fyle/delegated-accounts/delegated-accounts.page.spec.ts
  src/app/fyle/delegated-accounts/delegated-accounts.page.ts
  src/app/fyle/notifications/notifications.page.spec.ts
  src/app/fyle/notifications/notifications.page.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/L

#3178 fix: for same user counted as multiple users on mixpanel
  src/app/core/services/tracking.service.ts
Labels: size/XS

#3157 fix: Update delegation flow to incorporate new changes
  src/app/core/services/org-user.service.spec.ts
  src/app/core/services/org-user.service.ts
  src/app/fyle/delegated-accounts/delegated-accounts.page.spec.ts
  src/app/fyle/delegated-accounts/delegated-accounts.page.ts
  src/app/fyle/notifications/notifications.page.ts
Labels: size/S

#3176 test: Added unit test cases for dismiss dialog
  src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.spec.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
Labels: size/M

#3183 feat: Dupicate icon in expense card
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
Labels: size/XS

#3185 feat: use proxy for mixpanel when present
  hooks/utils/prod-environment.js
  src/app/core/services/tracking.service.ts
  src/environments/environment.ts
Labels: size/XS

#3181 fix: mileage and per diem forms to show all projects if project-category restriction is diabled
  src/app/core/services/org-settings.service.ts
  src/app/core/services/projects.service.spec.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/recently-used-items.service.spec.ts
  src/app/core/services/recently-used-items.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.ts
Labels: size/M

#3180 test: fixing test coverage for project category restriction checks
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/projects.service.spec.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/recently-used-items.service.spec.ts
  src/app/core/services/recently-used-items.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.ts
Labels: size/L

#3179 feat: adding project category restriction checks while setting split expense values based on project - part 2
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/projects.service.spec.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/recently-used-items.service.spec.ts
  src/app/core/services/recently-used-items.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.ts
Labels: size/L

#3177 feat: adding project category restriction checks while getting allowed categories for project - part 1
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/projects.service.spec.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/recently-used-items.service.spec.ts
  src/app/core/services/recently-used-items.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.ts
Labels: size/L

#3175 feat: Dismiss Dialog for duplicate expenses
  src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.html
  src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.scss
  src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.spec.ts
  src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.ts
  src/app/fyle/my-expenses/my-expenses.module.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.ts
  src/global.scss
Labels: size/L

#3184 test: fixed test cases of potential duplicates filter
  src/app/core/mock-data/expense-filters.data.ts
  src/app/core/mock-data/filter-options.data.ts
  src/app/core/mock-data/filter-pills.data.ts
  src/app/core/mock-data/selected-filters.data.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.service.spec.ts
Labels: size/M

#3182 feat: Potential Duplicate Filter
  src/app/core/mock-data/expense-filters.data.ts
  src/app/core/mock-data/filter-options.data.ts
  src/app/core/mock-data/filter-pills.data.ts
  src/app/core/mock-data/selected-filters.data.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/shared/expenses.service.ts
  src/app/fyle/my-expenses/my-expenses-filters.model.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-expenses/my-expenses.service.spec.ts
  src/app/fyle/my-expenses/my-expenses.service.ts
Labels: size/M

#3186 fix: Added is_duplicate present key in expense modal
  src/app/core/models/platform/v1/expense.model.ts
Labels: size/XS

#3187 fix: set mixpanel track_pageview to false
  src/app/core/services/tracking.service.ts
Labels: size/XS

#3188 fix: delegatee notification display issue
  src/app/fyle/notifications/notifications.page.ts
Labels: size/XS

#3189 fix: fix for delegatee notification visibility
  src/app/fyle/notifications/notifications.page.ts
Labels: size/XS

#3190 fix: assiging isProjectCategoryRestrictionsEnabled before using it
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/S

#3191 fix: potential duplicate filter pill click
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XS
