Repository fylein/fyle-mobile-app, pull requests merged in 2024-12, with the labels that each got.

#3282 test: Add tests for the password checks tooltip
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.html
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.scss
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.spec.ts
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.ts
  src/app/shared/components/password-check-tooltip/password-checks.model.ts
  src/app/shared/components/password-check-tooltip/password-criteria.model.ts
Labels: size/M

#3292 fix: migrate personal card access token to platform
  src/app/core/mock-data/personal-cards-access-token.data.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/M

#3289 test: Test for Verify flow
  src/app/post-verification/invited-user/invited-user.module.ts
  src/app/post-verification/invited-user/invited-user.page.html
  src/app/post-verification/invited-user/invited-user.page.scss
  src/app/post-verification/invited-user/invited-user.page.spec.ts
  src/app/post-verification/invited-user/invited-user.page.ts
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.scss
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.spec.ts
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.ts
  src/app/shared/shared.module.ts
  src/assets/icons/icon-128.webp
  src/assets/icons/icon-192.webp
  src/assets/icons/icon-256.webp
  src/assets/icons/icon-48.webp
  src/assets/icons/icon-512.webp
  src/assets/icons/icon-72.webp
  src/assets/icons/icon-96.webp
  src/assets/svg/check-circle-outline.svg
  src/assets/svg/eye-slash.svg
  src/assets/svg/eye.svg
  src/assets/videos/connect_card_onboarding_step.mp4
Labels: size/L

#3296 fix: fix env reference for yodlee
  hooks/utils/prod-environment.js
  src/assets/icons/icon-128.webp
  src/assets/icons/icon-192.webp
  src/assets/icons/icon-256.webp
  src/assets/icons/icon-48.webp
  src/assets/icons/icon-512.webp
  src/assets/icons/icon-72.webp
  src/assets/icons/icon-96.webp
  src/assets/videos/connect_card_onboarding_step.mp4
Labels: size/XS

#3294 fix: migrate postAccounts personal card to platform
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/S

#3299 fix: Revert "fix: Revert "feat: Remove error state from verify page (#3284…
  src/app/auth/verify/verify.page.html
  src/app/auth/verify/verify.page.scss
  src/app/auth/verify/verify.page.spec.ts
  src/app/auth/verify/verify.page.ts
  src/assets/svg/loader.svg
Labels: size/M

#3302 fix: Fix tooltip CSS for password checks tooltip and trigger validation when event is emitted
  src/app/post-verification/invited-user/invited-user.page.html
  src/app/post-verification/invited-user/invited-user.page.ts
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.scss
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.spec.ts
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.ts
Labels: size/S

#3303 fix: add appFormButtonValidation to invite user page button
  src/app/post-verification/invited-user/invited-user.page.html
Labels: size/XS

#3297 feat: Add new pipe to display the exact amount
  src/app/core/models/currency-pipe-config.model.ts
  src/app/shared/pipes/exact-currency.pipe.spec.ts
  src/app/shared/pipes/exact-currency.pipe.ts
  src/app/shared/shared.module.ts
Labels: size/M

#3304 test: Add tests for reset password page
  src/app/auth/reset-password/reset-password.page.html
  src/app/auth/reset-password/reset-password.page.scss
  src/app/auth/reset-password/reset-password.page.spec.ts
  src/app/auth/reset-password/reset-password.page.ts
Labels: size/M

#3301 feat: Forgot Password page redesign
  src/app/auth/reset-password/reset-password.page.html
  src/app/auth/reset-password/reset-password.page.scss
  src/app/auth/reset-password/reset-password.page.spec.ts
  src/app/auth/reset-password/reset-password.page.ts
  src/theme/colors.scss
Labels: size/L

#3293 fix: migrate sync/fetch personal cards txn to platform
  src/app/core/models/platform/platform-personal-card-syn-txns.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/M

#3308 fix: Allow save expense with invalid fields after capture receipt
  src/app/core/mock-data/transaction.data.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.spec.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
Labels: size/M

#3310 test: Add tests for reset password page
  src/app/auth/new-password/new-password.page.spec.ts
  src/app/auth/new-password/new-password.page.ts
  src/app/post-verification/invited-user/invited-user.page.spec.ts
  src/app/post-verification/invited-user/invited-user.page.ts
Labels: size/M

#3307 test: Add tests for pending verification page
  src/app/auth/pending-verification/pending-verification.page.scss
  src/app/auth/pending-verification/pending-verification.page.spec.ts
  src/app/auth/pending-verification/pending-verification.page.ts
Labels: size/M

#3306 feat: Redesign for Invite Expired page
  src/app/auth/pending-verification/pending-verification.page.html
  src/app/auth/pending-verification/pending-verification.page.scss
  src/app/auth/pending-verification/pending-verification.page.spec.ts
  src/app/auth/pending-verification/pending-verification.page.ts
Labels: size/L

#3309 feat: Redesign reset password page
  src/app/auth/new-password/new-password.module.ts
  src/app/auth/new-password/new-password.page.html
  src/app/auth/new-password/new-password.page.scss
  src/app/auth/new-password/new-password.page.spec.ts
  src/app/auth/new-password/new-password.page.ts
  src/app/post-verification/invited-user/invited-user.page.spec.ts
  src/app/post-verification/invited-user/invited-user.page.ts
Labels: size/L

#3313 fix: fix spacing from top and other minor issues with UI
  src/app/auth/new-password/new-password.page.html
  src/app/auth/new-password/new-password.page.scss
  src/app/auth/pending-verification/pending-verification.page.html
  src/app/auth/pending-verification/pending-verification.page.scss
  src/app/auth/pending-verification/pending-verification.page.ts
  src/app/auth/reset-password/reset-password.page.scss
  src/app/post-verification/invited-user/invited-user.page.scss
  src/app/post-verification/invited-user/invited-user.page.ts
  src/global.scss
Labels: size/S

#3312 feat: Generalize `fy-loading-screen.component` for new list view design
  src/app/shared/components/fy-loading-screen/fy-loading-screen.component.html
  src/app/shared/components/fy-loading-screen/fy-loading-screen.component.scss
  src/app/shared/components/fy-loading-screen/fy-loading-screen.component.ts
Labels: size/S

#3314 feat: Update my Expense list view to use new shimmers
  src/app/fyle/my-expenses/my-expenses.page.html
Labels: size/XS

#3315 feat: Update create-new-report amount section
  src/app/shared/components/create-new-report-v2/create-new-report.component.html
  src/app/shared/components/create-new-report-v2/create-new-report.component.scss
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/assets/svg/notch.svg
  src/global.scss
Labels: size/M

#3317 fix: fix minor UI issues 2
  src/app/auth/new-password/new-password.page.ts
  src/app/auth/pending-verification/pending-verification.page.html
  src/app/auth/pending-verification/pending-verification.page.scss
  src/app/auth/reset-password/reset-password.page.spec.ts
  src/app/auth/reset-password/reset-password.page.ts
  src/app/post-verification/invited-user/invited-user.page.ts
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.spec.ts
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.ts
Labels: size/M

#3320 fix: Update smaller screen size design for header
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.scss
Labels: size/XS

#3322 feat: Add to expenses to report section (Use Exact Amount)
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.scss
  src/global.scss
Labels: size/M

#3316 fix: add mfa flow to sync/fetch txns personal card
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-cards.data.ts
  src/app/core/models/personal_card.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.spec.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.ts
Labels: size/L

#3326 fix: Revert Sign In flow changes part 2
  src/app/auth/disabled/disabled.page.html
  src/app/auth/disabled/disabled.page.scss
  src/app/auth/new-password/new-password.module.ts
  src/app/auth/new-password/new-password.page.html
  src/app/auth/new-password/new-password.page.scss
  src/app/auth/new-password/new-password.page.spec.ts
  src/app/auth/new-password/new-password.page.ts
  src/app/auth/pending-verification/pending-verification.page.html
  src/app/auth/pending-verification/pending-verification.page.scss
  src/app/auth/pending-verification/pending-verification.page.spec.ts
  src/app/auth/pending-verification/pending-verification.page.ts
  src/app/auth/reset-password/reset-password.page.html
  src/app/auth/reset-password/reset-password.page.scss
  src/app/auth/reset-password/reset-password.page.spec.ts
  src/app/auth/reset-password/reset-password.page.ts
  src/app/auth/verify/verify.page.html
  src/app/auth/verify/verify.page.scss
  src/app/auth/verify/verify.page.spec.ts
  src/app/auth/verify/verify.page.ts
  src/app/post-verification/invited-user/invited-user.module.ts
  src/app/post-verification/invited-user/invited-user.page.html
  src/app/post-verification/invited-user/invited-user.page.scss
  src/app/post-verification/invited-user/invited-user.page.spec.ts
  src/app/post-verification/invited-user/invited-user.page.ts
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.scss
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.spec.ts
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.ts
  src/app/shared/shared.module.ts
  src/assets/svg/arrow-left.svg
  src/assets/svg/check-circle-outline.svg
  src/assets/svg/error-outlined.svg
  src/assets/svg/eye-slash.svg
  src/assets/svg/eye.svg
  src/assets/svg/loader.svg
  src/global.scss
  src/theme/colors.scss
Labels: size/XL

#3324 fix: standardize custom fields for policy check
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/S

#3327 fix: Revert "test: Add tests for the password checks tooltip (#3282)"
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.html
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.scss
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.spec.ts
  src/app/shared/components/password-check-tooltip/password-check-tooltip.component.ts
  src/app/shared/components/password-check-tooltip/password-checks.model.ts
  src/app/shared/components/password-check-tooltip/password-criteria.model.ts
Labels: size/L

#3329 fix: Revert "fix: add mfa flow to sync/fetch txns personal card (#3316)"
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-cards.data.ts
  src/app/core/models/personal_card.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.spec.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.ts
Labels: size/L

#3330 feat: Update view report (reports--card) to display the exact amount
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
Labels: size/S

#3331 feat: Add expenses to report (display exact amount)
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.scss
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.spec.ts
Labels: size/S

#3318 fix: fix translucent screen issue with ion-content
  src/app/auth/new-password/new-password.page.html
  src/app/auth/new-password/new-password.page.scss
  src/app/auth/new-password/new-password.page.ts
  src/app/auth/pending-verification/pending-verification.page.html
  src/app/auth/pending-verification/pending-verification.page.scss
  src/app/auth/reset-password/reset-password.page.html
  src/app/auth/reset-password/reset-password.page.scss
  src/app/post-verification/invited-user/invited-user.page.html
  src/app/post-verification/invited-user/invited-user.page.scss
Labels: size/L

#3328 feat: Report card section display exact amount
  src/app/fyle/my-reports/my-reports.page.html
  src/app/shared/components/reports-card/reports-card.component.html
  src/app/shared/components/reports-card/reports-card.component.scss
  src/app/shared/components/reports-card/reports-card.component.spec.ts
Labels: size/M

#3336 fix: bug in bank-account-cards.component.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.ts
Labels: size/S

#3342 test: Fix tests for sign in page
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/sign-in/sign-in.page.scss
  src/app/auth/sign-in/sign-in.page.spec.ts
Labels: size/S

#3343 test: Add template tests to Sign In page
  src/app/auth/sign-in/sign-in.page.spec.ts
Labels: size/M

#3337 fix: QA fixes for verify screens
  src/app/auth/disabled/disabled.page.html
  src/app/auth/new-password/new-password.page.html
  src/app/auth/new-password/new-password.page.scss
  src/app/auth/pending-verification/pending-verification.page.html
  src/app/auth/pending-verification/pending-verification.page.scss
  src/app/auth/reset-password/reset-password.page.html
  src/app/auth/reset-password/reset-password.page.scss
  src/app/auth/reset-password/reset-password.page.spec.ts
  src/app/auth/reset-password/reset-password.page.ts
  src/app/auth/verify/verify.page.scss
  src/app/core/services/loader.service.spec.ts
  src/app/core/services/loader.service.ts
  src/app/post-verification/invited-user/invited-user.page.html
  src/app/post-verification/invited-user/invited-user.page.scss
  src/app/post-verification/invited-user/invited-user.page.ts
Labels: size/M

#3338 feat: Redesign Sign In page
  src/app/auth/sign-in/sign-in-page-state.enum.ts
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/sign-in/sign-in.page.scss
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/assets/videos/mobile-onboarding.mp4
Labels: size/L

#3335 fix: add back reverted mfa flow changes and fix reason for reverting in the first place
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-cards.data.ts
  src/app/core/models/personal_card.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.spec.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.ts
Labels: size/L

#3344 fix: Added the missed key for merge expense page
  src/app/core/services/transaction.service.ts
Labels: size/XS

#3334 fix: Added the fail safe for checking id before before making the api calls
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XS

#3339 feat: Update view report (reports--summary card) to display the exact amount (Approver side)
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
Labels: size/M

#3347 feat: View mileage summary card display exact amount
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.scss
Labels: size/S

#3348 feat: View per-diem summary card display exact amount
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.scss
Labels: size/S

#3340 feat: View expense summary card display exact amount
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.scss
Labels: size/S

#3349 fix: Fix splash screen foreground color
  android/app/src/main/res/drawable/ic_launcher_new_splash_foreground.xml
  capacitor.config.json
Labels: size/XS

#3351 feat: Team Advance list view display exact amount
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.html
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.scss
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.spec.ts
  src/app/fyle/team-advance/team-advance.page.html
  src/global.scss
Labels: size/M

#3346 feat: Redesign error popover for sign in page
  src/app/auth/sign-in/error/error.component.html
  src/app/auth/sign-in/error/error.component.scss
  src/app/auth/sign-in/error/error.component.spec.ts
  src/app/auth/sign-in/error/error.component.ts
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/global.scss
Labels: size/M

#3345 fix: changing content corporate cards to my cards and manage cards
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/my-profile/my-profile.page.html
Labels: size/XS

#3352 fix: Fix background for video for Sign In page and add Forgot Password CTA
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/sign-in/sign-in.page.scss
  src/app/auth/sign-in/sign-in.page.ts
Labels: size/M

#3353 feat: View advance request display exact amount (SPENDER + APPROVER)
  src/app/shared/components/summary-tile/summary-tile.component.html
  src/app/shared/components/summary-tile/summary-tile.component.scss
  src/app/shared/components/summary-tile/summary-tile.component.spec.ts
Labels: size/M

#3355 feat: My Advance list view display exact amount
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.html
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.scss
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.spec.ts
  src/app/fyle/my-advances/my-advances.page.html
Labels: size/M

#3359 Fix: fixed the zero state expense
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.scss
Labels: size/XS

#3360 feat: Update All task cards (Expense / Reports / Advance) to display exact amount
  src/app/core/mock-data/task.data.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.scss
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.spec.ts
  src/app/shared/shared.module.ts
Labels: size/L

#3368 chore: Added the sentry to trace issues
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
Labels: size/M

#3365 feat: Dashboard > Home: Expense and Report Stats display the exact amount
  src/app/fyle/dashboard/stat-badge/stat-badge.component.html
  src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
  src/app/fyle/dashboard/stat-badge/stat-badge.component.spec.ts
  src/app/fyle/dashboard/stat-badge/stat-badge.component.ts
  src/app/fyle/dashboard/stats/stats.component.scss
Labels: size/S

#3367 feat: Dashboard > Home: Card expenses section display exact amount
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
  src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
Labels: size/M

#3373 feat: Update Personal Transaction card to display exact amount
  src/app/fyle/personal-cards/transactions-shimmer/transactions-shimmer.component.html
  src/app/fyle/personal-cards/transactions-shimmer/transactions-shimmer.component.scss
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.html
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.scss
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.spec.ts
Labels: size/M

#3375 feat: Update Matching expense card to display exact amount
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.html
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.scss
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.spec.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.html
  src/app/shared/components/expense-card-lite/expense-card-lite.component.scss
  src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
Labels: size/M

#3378 feat: Add service for spender onboarding
  src/app/core/models/onboarding-state.enum.ts
  src/app/core/models/onboarding-status.model.ts
  src/app/core/models/onboarding-step-status.model.ts
  src/app/core/models/onboarding-welcome-step-status.model.ts
  src/app/core/services/spender-onboarding.service.spec.ts
  src/app/core/services/spender-onboarding.service.ts
Labels: size/M

#3358 fix: Fixes a bug and contains minor css changes
  src/app/auth/new-password/new-password.page.html
  src/app/auth/new-password/new-password.page.scss
  src/app/auth/new-password/new-password.page.ts
  src/app/auth/reset-password/reset-password.page.html
  src/app/auth/reset-password/reset-password.page.spec.ts
  src/app/auth/reset-password/reset-password.page.ts
  src/app/auth/sign-in/error/error.component.scss
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/sign-in/sign-in.page.scss
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/app/post-verification/invited-user/invited-user.page.scss
  src/global.scss
Labels: size/M

#3372 test: Added unit tests for the cc merchant info
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/shared/components/cc-expense-merchant-info-popover/cc-expense-merchant-info-popover.component.spec.ts
Labels: size/M

#3369 feat: Added the merchant name as Suggestion in expense detail card for CC expenses
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.scss
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.scss
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/shared/components/cc-expense-merchant-info-popover/cc-expense-merchant-info-popover.component.html
  src/app/shared/components/cc-expense-merchant-info-popover/cc-expense-merchant-info-popover.component.scss
  src/app/shared/components/cc-expense-merchant-info-popover/cc-expense-merchant-info-popover.component.spec.ts
  src/app/shared/components/cc-expense-merchant-info-popover/cc-expense-merchant-info-popover.component.ts
  src/app/shared/components/transaction-status/transaction-status.component.html
  src/app/shared/components/transaction-status/transaction-status.component.scss
  src/app/shared/shared.module.ts
Labels: size/L

#3370 test: Add tests for Corporate Card task
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks-1.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
Labels: size/M

#3366 fix: showing complete stats for completed expense inside expenses page
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
Labels: size/XS

#3333 feat: Milestone 2: Reports view display exact amount
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.scss
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/shared/components/reports-card/reports-card.component.html
  src/app/shared/components/reports-card/reports-card.component.scss
  src/app/shared/components/reports-card/reports-card.component.spec.ts
Labels: size/M

#3350 feat: Milestone 3: Team-Reports view display exact amount
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.scss
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.scss
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.scss
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-alert-info/fy-alert-info.component.scss
  src/app/shared/components/popup-alert/popup-alert.component.html
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/app/shared/components/popup-alert/popup-alert.component.ts
  src/app/shared/shared.module.ts
Labels: size/M

#3354 feat: Milestone 4: Team advance display exact amount
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.html
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.scss
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.spec.ts
  src/app/fyle/team-advance/team-advance.page.html
  src/app/shared/components/summary-tile/summary-tile.component.html
  src/app/shared/components/summary-tile/summary-tile.component.scss
  src/app/shared/components/summary-tile/summary-tile.component.spec.ts
  src/global.scss
Labels: size/M

#3357 feat: Milestone 5: My Advance view display exact amount
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.html
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.scss
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.spec.ts
  src/app/fyle/my-advances/my-advances.page.html
Labels: size/M

#3376 feat: Milestone 7: Dashboard > Home display exact amount
  src/app/fyle/dashboard/stat-badge/stat-badge.component.html
  src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
  src/app/fyle/dashboard/stat-badge/stat-badge.component.spec.ts
  src/app/fyle/dashboard/stat-badge/stat-badge.component.ts
  src/app/fyle/dashboard/stats/stats.component.scss
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
  src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
Labels: size/M

#3377 feat: Milestone 8: Personal Cards display exact amount
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.html
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.scss
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.spec.ts
  src/app/fyle/personal-cards/transactions-shimmer/transactions-shimmer.component.html
  src/app/fyle/personal-cards/transactions-shimmer/transactions-shimmer.component.scss
  src/app/shared/components/expense-card-lite/expense-card-lite.component.html
  src/app/shared/components/expense-card-lite/expense-card-lite.component.scss
  src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.html
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.scss
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.spec.ts
Labels: size/L

#3311 feat: Milestone 1: Expense view display exact amount
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.scss
  src/app/shared/components/create-new-report-v2/create-new-report.component.html
  src/app/shared/components/create-new-report-v2/create-new-report.component.scss
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/assets/svg/notch.svg
  src/global.scss
Labels: size/L

#3380 fix: Updated the merchant field variable name
  src/app/fyle/view-expense/view-expense.page.html
Labels: size/XS

#3382 fix: resolve undefined object error
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/XS

#3384 fix: Display exact amount test 1 fixes
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.scss
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/summary-tile/summary-tile.component.scss
Labels: size/S

#3383 feat: initial template for onboarding home page
  src/app/fyle/fyle-routing.module.ts
  src/app/fyle/spender-onboarding/spender-onboarding-routing.module.ts
  src/app/fyle/spender-onboarding/spender-onboarding.module.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/assets/svg/progress-bar.svg
Labels: size/M

#3386 feat: Fix QA issues for Sign In page
  android/app/src/main/ic_launcher_new_splash-playstore.png
  android/app/src/main/res/drawable/ic_launcher_new_splash_background.xml
  android/app/src/main/res/drawable/ic_launcher_new_splash_foreground.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_new_splash.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_new_splash_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_new_splash_round.webp
  src/app/app.component.ts
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/sign-in/sign-in.page.scss
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/assets/images/video-default-background.png
Labels: size/L

#3381 fix: add calculated values for mileage distance and amount
  src/app/core/mock-data/transaction.data.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
Labels: size/XS

#3385 fix: Adds missing tests for the component
  android/.idea/runConfigurations.xml
  src/app/core/mock-data/task-cta.data.ts
  src/app/core/models/task-event.enum.ts
  src/app/core/models/task-icon.enum.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks-1.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
Labels: size/L

#3388 feat: implementation - connect cards input UI
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
Labels: size/L

#3387 feat: controller logic and tests for onboarding home page
  src/app/core/mock-data/onboarding-status.data.ts
  src/app/core/services/spender-onboarding.service.spec.ts
  src/app/core/services/spender-onboarding.service.ts
  src/app/fyle/spender-onboarding/models/onboarding-step.enum.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.module.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
Labels: size/L
