Repository fylein/fyle-mobile-app, pull requests merged in 2024-02, with the labels that each got.

#2713 fix: fix naming for box shadow color
  src/app/core/services/virtual-cards.service.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/theme/colors.scss
Labels: size/XS

#2732 fix: floating point precision in new flow
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/S

#2731 feat: show missing receipt message in critical policy violation
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
Labels: size/S

#2730 fix: show correct header in case of split blocked
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/S

#2727 fix: dont show cost center split option if category doesn't have any
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/M

#2726 fix: fixed the incorrect model and types
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/models/filtered-split-policy-violations.model.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/M

#2725 feat: popover for edge cases in tax amount and reports for split
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/models/filtered-split-policy-violations.model.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/M, size/L

#2724 test: test fix for split expense - Part 19
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/models/filtered-split-policy-violations.model.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/M

#2723 test: test fix for split expense - Part 18
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/models/filtered-split-policy-violations.model.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/M

#2722 test: test fix for split expense - Part 17
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/L

#2721 fix: test fix for split expense - Part 16
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2720 test: test fix for split expense - Part 15
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2719 test: test fix for split expense - Part 14
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2718 test: test fix for split expense - Part 13
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2716 test: test fix for split expense - Part 12
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2715 test: test fix for split expense - Part 11
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense-policy.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/models/split-expense-missing-fields.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/M

#2714 test: test fix for split expense - Part 10
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense-policy.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/models/split-expense-missing-fields.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2709 test: test fix for split expense - Part 7
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense-policy.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/models/split-expense-missing-fields.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/S

#2707 test: test fix for split expense - Part 6
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense-policy.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/models/split-expense-missing-fields.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2706 test: test fix for split expense - Part 5
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense-policy.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/models/split-expense-missing-fields.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2702 test: test fix for split expense - Part 4
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense-policy.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/models/split-expense-missing-fields.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2701 test: test fix for split expense - Part 3
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense-policy.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/models/split-expense-missing-fields.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2700 test: test fix for split expense - Part 2
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense-policy.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/models/split-expense-missing-fields.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/M, size/XL

#2699 test: test fix for split expense - Part 1
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense-policy.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/models/split-expense-missing-fields.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2695 fix: Form value fix for spend date
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense-policy.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/models/split-expense-missing-fields.data.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2693 fix: eslint fix - part 3
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/policy-violcation-comment.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense-policy.data.ts
  src/app/core/mock-data/split-payload.data.ts
  src/app/core/mock-data/splits.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/filtered-missing-fields-violations.model.ts
  src/app/core/models/filtered-split-policy-violations.model.ts
  src/app/core/models/platform/v1/split-payload.model.ts
  src/app/core/models/policy-violation.model.ts
  src/app/core/models/split-expense-missing-fields.data.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/XL

#2736 fix: floating point precision in new flow - part 2
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/XS

#2735 fix: remove category from form if it is disabled
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#2733 fix: my view report page not refreshed after split
  src/app/core/services/platform/v1/spender/expenses.service.ts
Labels: size/S

#2740 fix: redirection from my view report page fix
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/S

#2728 feat: Remove usage of getAllEtxnc and remove unused getReportEtxnc.
  src/app/core/mock-data/platform/v1/expenses-query-params.data.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/report.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
Labels: size/L

#2717 feat: Add Virtual Card to dashboard
  src/app/core/models/card-details-combined-response.model.ts
  src/app/core/models/card-details-with-amount-response.model.ts
  src/app/core/models/platform-corporate-card-detail.model.ts
  src/app/core/models/virtual-cards-combined-request.model.ts
  src/app/core/services/virtual-cards.service.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.html
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
  src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
  src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
  src/app/shared/components/virtual-card/virtual-card.component.html
  src/app/shared/components/virtual-card/virtual-card.component.scss
Labels: size/M

#2746 fix: file not attached in split expense fix
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/XS

#2704 feat: Update org settings
  src/app/core/enums/manage-cards-page-segment.enum.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/platform/platform-corporate-card.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
  src/theme/colors.scss
Labels: size/M

#2696 feat: Add tests for Virtual Cards service
  src/app/core/enums/manage-cards-page-segment.enum.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/virtual-card-details-response.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/platform/platform-corporate-card.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/core/services/virtual-cards.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
  src/app/shared/components/virtual-card/virtual-card.component.scss
  src/theme/colors.scss
Labels: size/M

#2697 feat: Additional CSS changes for Virtual Cards
  src/app/core/enums/manage-cards-page-segment.enum.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/virtual-card-details-response.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/platform/platform-corporate-card.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/core/services/virtual-cards.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
  src/app/shared/components/virtual-card/virtual-card.component.html
  src/app/shared/components/virtual-card/virtual-card.component.scss
  src/app/shared/components/virtual-card/virtual-card.component.ts
  src/theme/colors.scss
Labels: size/M

#2698 feat: Add template for Virtual Card Component
  src/app/core/enums/card-status.enum.ts
  src/app/core/enums/manage-cards-page-segment.enum.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/virtual-card-details-response.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/platform/platform-corporate-card.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/core/services/virtual-cards.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
  src/app/shared/components/virtual-card/virtual-card.component.html
  src/app/shared/components/virtual-card/virtual-card.component.scss
  src/app/shared/components/virtual-card/virtual-card.component.spec.ts
  src/app/shared/components/virtual-card/virtual-card.component.ts
  src/app/shared/shared.module.ts
  src/assets/images/amex-virtual-card-new-logo.png
  src/assets/svg/contactless-payment.svg
  src/theme/colors.scss
Labels: size/L

#2743 feat: new split expense trackers
  src/app/core/models/tracking-properties.model.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/M

#2757 fix:removed duplicate detection v2 flags and old code
  src/app/core/mock-data/handle-duplicates.service.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/services/handle-duplicates.service.spec.ts
  src/app/core/services/handle-duplicates.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.spec.ts
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.ts
Labels: size/L

#2765 fix: split save button loader race condition
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/XS

#2763 fix: concurrency issue in mobile app where report is approved but edi…
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/M

#2767 fix: split evenly precision fix for decimals
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/XS

#2712 feat: Add method for sending API calls in serial for virtual cards
  src/app/core/models/card-details-combined-response.model.ts
  src/app/core/models/platform-corporate-card-detail.model.ts
  src/app/core/models/virtual-card.model.ts
  src/app/core/models/virtual-cards-combined-request.model.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/core/services/virtual-cards.service.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.html
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
  src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
  src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
  src/app/shared/components/virtual-card/virtual-card.component.html
  src/app/shared/components/virtual-card/virtual-card.component.scss
  src/app/shared/components/virtual-card/virtual-card.component.ts
Labels: size/L

#2741 test: Add tests for Virtual Cards changes
  src/app/core/mock-data/platform-corporate-card-detail.data.ts
  src/app/core/mock-data/platform-corporate-card.data.ts
  src/app/core/mock-data/virtual-card-combined-response.data.ts
  src/app/core/mock-data/virtual-card-response.data.ts
  src/app/core/mock-data/virtual-cards-combined-request.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/virtual-card.model.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/org-settings.service.spec.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.html
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
  src/app/shared/components/spent-cards/spent-cards.component.spec.ts
  src/app/shared/components/virtual-card/virtual-card.component.html
  src/app/shared/components/virtual-card/virtual-card.component.spec.ts
  src/app/shared/components/virtual-card/virtual-card.component.ts
Labels: size/L

#2694 feat: Add Virtual Card Changes
  src/app/core/enums/card-status.enum.ts
  src/app/core/enums/manage-cards-page-segment.enum.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/platform-corporate-card-detail.data.ts
  src/app/core/mock-data/platform-corporate-card.data.ts
  src/app/core/mock-data/virtual-card-combined-response.data.ts
  src/app/core/mock-data/virtual-card-details-response.data.ts
  src/app/core/mock-data/virtual-card-response.data.ts
  src/app/core/mock-data/virtual-cards-combined-request.data.ts
  src/app/core/models/card-details-amount-response.ts
  src/app/core/models/card-details-combined-response.model.ts
  src/app/core/models/card-details-response.model.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/platform-corporate-card-detail.model.ts
  src/app/core/models/platform/platform-corporate-card.model.ts
  src/app/core/models/virtual-card.model.ts
  src/app/core/models/virtual-cards-combined-request.model.ts
  src/app/core/models/virtual-cards-request.model.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/org-settings.service.spec.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/core/services/virtual-cards.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.html
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.scss
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
  src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
  src/app/shared/components/spent-cards/spent-cards.component.spec.ts
  src/app/shared/components/virtual-card/virtual-card.component.html
  src/app/shared/components/virtual-card/virtual-card.component.scss
  src/app/shared/components/virtual-card/virtual-card.component.spec.ts
  src/app/shared/components/virtual-card/virtual-card.component.ts
  src/app/shared/shared.module.ts
  src/assets/images/amex-virtual-card-new-logo.png
  src/assets/svg/contactless-payment.svg
  src/theme/colors.scss
Labels: size/XL

#2781 feat: removal of old split code - Part 14
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/M

#2780 feat: removal of old split code - Part 12
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/M

#2779 feat: removal of old split code - Part 11
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/M

#2778 feat: removal of old split code - Part 10
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/L

#2777 feat: removal of old split code - Part 9
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/L

#2776 feat: removal of old split code - Part 8
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/L

#2775 feat: removal of old split code - Part 7
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/L

#2774 feat: removal of old split code - Part 6
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/L

#2773 feat: removal of old split code - Part 5
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/L

#2772 feat: removal of old split code - Part 4
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/M

#2771 feat: removal of old split code - Part 3
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/XL

#2770 feat: removal of old split code - Part 2
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/XL

#2784 fix: compare absolute value rather than negative value
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#2769 feat: removal of old split code - Part 1
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
Labels: size/XL

#2785 feat: Added Add to report restriction in add edit report section
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#2786 feat: Added Split expenses restrictions in add edit expense
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#2788 feat: Added filtering for pending txns in create/ add to report dialog
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/S

#2676 feat: commute details section in my profile
  src/app/core/models/org-settings.model.ts
  src/app/core/models/platform/commute-details-response.model.ts
  src/app/core/models/platform/v1/commute-details.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.scss
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/icon/icon.module.ts
  src/assets/svg/arrow-tail-up-down.svg
  src/assets/svg/arrow-tail-up.svg
Labels: size/M

#2794 fix: set commute details default to false
  src/app/fyle/my-profile/my-profile.page.html
Labels: size/XS
