Repository fylein/fyle-mobile-app, pull requests merged in 2024-07, with the labels that each got.

#3121 fix: change the error message and remove other validator
  src/app/shared/components/fy-opt-in/fy-opt-in.component.spec.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
Labels: size/XS

#3114 feat: added update mobile number modal for non us org
  src/app/core/mock-data/value-error-mapping-for-update-mobile-number-popover.data.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.html
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.scss
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.spec.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.spec.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
  src/app/shared/components/mobile-number-card/mobile-number-card.component.html
  src/app/shared/components/mobile-number-card/mobile-number-card.component.scss
  src/app/shared/components/mobile-number-card/mobile-number-card.component.spec.ts
  src/app/shared/components/mobile-number-card/mobile-number-card.component.ts
  src/app/shared/shared.module.ts
Labels: size/L

#3113 feat: change CTA and text for non +1 number
  src/app/core/mock-data/task.data.ts
  src/app/core/mock-data/value-error-mapping-for-update-mobile-number-popover.data.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.html
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.scss
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.spec.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.spec.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
  src/app/shared/components/mobile-number-card/mobile-number-card.component.html
  src/app/shared/components/mobile-number-card/mobile-number-card.component.scss
  src/app/shared/components/mobile-number-card/mobile-number-card.component.spec.ts
  src/app/shared/components/mobile-number-card/mobile-number-card.component.ts
  src/app/shared/shared.module.ts
Labels: size/S

#3127 fix: build failed
  src/app/fyle/my-profile/my-profile.page.html
  src/app/shared/components/mobile-number-card/mobile-number-card.component.spec.ts
  src/app/shared/components/mobile-number-card/mobile-number-card.component.ts
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.spec.ts
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.ts
Labels: size/S

#3128 fix: mixpanel trackers for dashboard banner
  src/app/core/enums/dashboard-state.enum.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.spec.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.spec.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
Labels: size/M

#3129 fix: hide dashboard banner after opt in from card addition
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
Labels: size/XS

#3130 fix: tax group sentry issue
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3099 fix: round off mileage amount
  src/app/core/models/location-info.model.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/S

#3133 fix: some copy fixes in opt in CTA
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
Labels: size/XS

#3135 feat: Added changes
  src/app/core/models/payment-mode.model.ts
  src/app/core/services/launch-darkly.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
Labels: size/S

#3132 fix: fix notification sentry issue
  src/app/fyle/notifications/notifications.page.ts
Labels: size/XS

#3136 feat: added robust tracker for task
  src/app/core/services/tracking.service.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
Labels: size/XS

#3125 feat: Move send back api to platform
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/M

#3138 feat: add me as a code-owner
  .github/CODEOWNERS
Labels: size/XS

#3141 fix: smol fix for code owner
  .github/CODEOWNERS
Labels: size/XS

#3144 feat: Change terminology for resubmit date
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.html
Labels: size/XS

#3137 fix: some design fix for allow-only-us-number flow
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.scss
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.ts
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
Labels: size/S

#3145 fix: content changes for allow-us-number-only initiative
  src/app/core/mock-data/task.data.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.scss
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
Labels: size/XS

#3131 feat: add approver platform API
  src/app/core/models/employee-params.model.ts
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/shared/components/fy-approver/add-approvers-popover/add-approvers-popover.component.spec.ts
  src/app/shared/components/fy-approver/add-approvers-popover/add-approvers-popover.component.ts
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.ts
  src/app/shared/components/fy-approver/add-approvers-popover/models/approver.model.ts
Labels: size/M

#3134 feat: Add API for partial approval
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/S

#3147 fix: include sub project in projects search
  src/app/core/mock-data/platform/v1/platform-projects-params.data.ts
  src/app/core/services/projects.service.ts
Labels: size/XS

#3148 fix: crazy JS date
  src/app/core/services/date.service.ts
  src/app/core/services/platform/v1/shared/date.service.ts
Labels: size/XS

#3149 feat: fix accumulator value in add approver flow
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/shared/components/fy-approver/add-approvers-popover/add-approvers-popover.component.ts
Labels: size/XS

#3151 fix: fix empty search string returning no projects
  src/app/core/services/projects.service.ts
Labels: size/XS

#3150 fix: ProjectsService.getByParamsUnformatted query param bug
  src/app/core/services/projects.service.ts
Labels: size/XS

#3152 fix: sign in page scroll issue
  src/app/auth/sign-in/sign-in.page.html
Labels: size/XS

#3153 fix: Added changes for refiner related p0
  src/app/core/services/refiner.service.spec.ts
  src/app/core/services/refiner.service.ts
  src/index.html
Labels: size/M

#3155 feat: Add delete report API to mobile app
  src/app/core/models/my-reports-filters.model.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/reports-card/reports-card.component.spec.ts
  src/app/shared/components/reports-card/reports-card.component.ts
Labels: size/L

#3154 fix: remove weekend spend key from expenses
  src/app/core/enums/platform/v1/expense-transaction-status.enum.ts
  src/app/core/mock-data/cc-transaction.data.ts
  src/app/core/mock-data/corporate-card-transaction-response.data.ts
  src/app/core/mock-data/matchedCCTransaction.data.ts
  src/app/core/mock-data/platform/v1/expense-employee.model.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-expense.data.ts
  src/app/core/models/matchedCCCTransaction.model.ts
  src/app/core/models/platform/v1/accounting-export-summary.model.ts
  src/app/core/models/platform/v1/cc-transaction.model.ts
  src/app/core/models/platform/v1/expense-missing-mandatory-fields.model.ts
  src/app/core/models/platform/v1/expense-report.model.ts
  src/app/core/models/platform/v1/expense-rule-data.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/platform/v1/matched-corpporate-card-transaction.model.ts
  src/app/core/models/platform/v1/policy-checks.model.ts
  src/app/core/models/platform/v1/violation.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.html
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.spec.ts
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.ts
  src/app/shared/components/transaction-status/transaction-status.component.spec.ts
  src/app/shared/components/transaction-status/transaction-status.component.ts
Labels: size/L

#3146 feat: target api level 34
  android/variables.gradle
Labels: size/XS
