Repository fylein/fyle-mobile-app, pull requests merged in 2024-04, with the labels that each got.

#2846 test: Add tests for sent back stats
  src/app/core/mock-data/stats-dimension-response.data.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/test-data/tasks.service.spec.data.ts
Labels: size/M

#2848 test: unit test for updateDistanceOnLocationChange method
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
Labels: size/M

#2847 test: unit test for updateDistanceOnDeductionChange method
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
Labels: size/L

#2841 test: unit test for updateDistanceOnRoundTripChange method
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
Labels: size/L

#2849 test: unit test for tasks component
  src/app/core/mock-data/commute-details-response.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/task.data.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
Labels: size/M

#2851 test: unit test for employees service
  src/app/core/services/platform/v1/spender/employees.service.spec.ts
Labels: size/S

#2853 test: unit tests for fy-select-commute-details component - Part 2
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.spec.ts
Labels: size/M

#2852 test: unit tests for fy-select-commute-details component - Part 1
  .github/workflows/unit-tests.yml
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.spec.ts
Labels: size/M

#2843 feat: Move Advance request stats call to platform
  src/app/core/mock-data/stats-dimension-response.data.ts
  src/app/core/models/platform/v1/stats-response.model.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/core/test-data/tasks.service.spec.data.ts
Labels: size/M

#2857 fix: Revert "feat: romoved query param from x-page-url (#2844)"
  src/app/core/interceptors/httpInterceptor.ts
Labels: size/XS

#2862 feat: add Chethan sir as code owner for mobile app
  .github/CODEOWNERS
Labels: size/XS

#2859 test: test for Advances
  src/app/core/mock-data/advance-platform.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/services/advance.service.spec.ts
  src/app/core/services/advance.service.ts
  src/app/fyle/my-advances/my-advances.page.spec.ts
  src/app/fyle/my-advances/my-advances.page.ts
Labels: size/L

#2793 feat: implementing changes in add edit per diem [5]
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/per-diem-reports.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/models/per-diem-reports.model.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/M

#2790 feat: updated the add-edit mileage page and the tests [4]
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/per-diem-reports.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/models/mileage-form-value.model.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/models/per-diem-reports.model.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/M

#2755 fix: migrated add-edit-expense.page to platform [2]
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/option.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/per-diem-reports.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/report-options.data.ts
  src/app/core/models/mileage-form-value.model.ts
  src/app/core/models/option.model.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/models/per-diem-reports.model.ts
  src/app/core/models/platform/v1/create-draft-params.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/platform/v1/report.model.ts
  src/app/core/models/report-options.model.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.html
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.spec.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.spec.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
Labels: size/XL

#2860 feat: move eadvances to platform
  src/app/core/mock-data/advance-request-custom-field-values.data.ts
  src/app/core/mock-data/approval.data.ts
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/mock-data/platform/v1/advance-request-platform.data.ts
  src/app/core/models/approval-public.model.ts
  src/app/core/models/extended-advance-request-public.model.ts
  src/app/core/models/platform/advance-request-platform.model.ts
  src/app/core/models/platform/platform-approval.model.ts
  src/app/core/models/platform/platform-employee.model.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/advance.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/my-advances/my-advances.page.spec.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.spec.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
Labels: size/XL

#2856 feat: Add advances to platform
  src/app/core/mock-data/advance-platform.data.ts
  src/app/core/mock-data/advance-request-custom-field-values.data.ts
  src/app/core/mock-data/approval.data.ts
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/mock-data/platform/v1/advance-request-platform.data.ts
  src/app/core/models/approval-public.model.ts
  src/app/core/models/extended-advance-request-public.model.ts
  src/app/core/models/extended_advance.model.ts
  src/app/core/models/platform/advance-request-platform.model.ts
  src/app/core/models/platform/advances-platform.model.ts
  src/app/core/models/platform/platform-approval.model.ts
  src/app/core/models/platform/platform-employee.model.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/advance.service.spec.ts
  src/app/core/services/advance.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/my-advances/my-advances.page.spec.ts
  src/app/fyle/my-advances/my-advances.page.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.spec.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
Labels: size/XL

#2865 test: Add branching fixes and other fixes for advance request
  src/app/core/mock-data/advance-platform.data.ts
  src/app/core/mock-data/advance-request-custom-field-values.data.ts
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/mock-data/platform/v1/advance-request-platform.data.ts
  src/app/core/mock-data/unflattened-advance-request.data.ts
  src/app/core/models/extended_advance.model.ts
  src/app/core/models/platform/advances-platform.model.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/advance.service.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/my-advances/my-advances.page.spec.ts
  src/app/fyle/my-advances/my-advances.page.ts
Labels: size/L

#2854 feat: Move advance req get to platform API
  src/app/core/mock-data/advance-platform.data.ts
  src/app/core/mock-data/advance-request-custom-field-values.data.ts
  src/app/core/mock-data/approval.data.ts
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/platform/v1/advance-request-platform.data.ts
  src/app/core/mock-data/stats-dimension-response.data.ts
  src/app/core/mock-data/unflattened-advance-request.data.ts
  src/app/core/models/advance-request-state.model.ts
  src/app/core/models/approval-public.model.ts
  src/app/core/models/extended-advance-request-public.model.ts
  src/app/core/models/extended_advance.model.ts
  src/app/core/models/platform/advance-request-platform.model.ts
  src/app/core/models/platform/advances-platform.model.ts
  src/app/core/models/platform/custom-fields.model.ts
  src/app/core/models/platform/platform-approval.model.ts
  src/app/core/models/platform/platform-config.model.ts
  src/app/core/models/platform/platform-employee.model.ts
  src/app/core/models/platform/v1/department.model.ts
  src/app/core/models/platform/v1/platform-advance.model.ts
  src/app/core/models/platform/v1/project.model.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/advance.service.spec.ts
  src/app/core/services/advance.service.ts
  src/app/core/services/tasks.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-advances/my-advances.page.spec.ts
  src/app/fyle/my-advances/my-advances.page.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.spec.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
Labels: size/XL

#2866 feat: added params x-page-url
  src/app/core/interceptors/httpInterceptor.spec.ts
  src/app/core/interceptors/httpInterceptor.ts
Labels: size/M

#2871 fix: Revert "feat: Move advance req get to platform API (#2854)"
  src/app/core/mock-data/advance-platform.data.ts
  src/app/core/mock-data/advance-request-custom-field-values.data.ts
  src/app/core/mock-data/approval.data.ts
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/platform/v1/advance-request-platform.data.ts
  src/app/core/mock-data/stats-dimension-response.data.ts
  src/app/core/mock-data/unflattened-advance-request.data.ts
  src/app/core/models/advance-request-state.model.ts
  src/app/core/models/approval-public.model.ts
  src/app/core/models/extended-advance-request-public.model.ts
  src/app/core/models/extended_advance.model.ts
  src/app/core/models/platform/advance-request-platform.model.ts
  src/app/core/models/platform/advances-platform.model.ts
  src/app/core/models/platform/custom-fields.model.ts
  src/app/core/models/platform/platform-approval.model.ts
  src/app/core/models/platform/platform-config.model.ts
  src/app/core/models/platform/platform-employee.model.ts
  src/app/core/models/platform/v1/department.model.ts
  src/app/core/models/platform/v1/platform-advance.model.ts
  src/app/core/models/platform/v1/project.model.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/advance.service.spec.ts
  src/app/core/services/advance.service.ts
  src/app/core/services/tasks.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-advances/my-advances.page.spec.ts
  src/app/fyle/my-advances/my-advances.page.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.spec.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
Labels: size/XL

#2739 feat: created report service which uses platform [1]
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/option.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/per-diem-reports.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/report-options.data.ts
  src/app/core/models/mileage-form-value.model.ts
  src/app/core/models/option.model.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/models/per-diem-reports.model.ts
  src/app/core/models/platform/v1/create-draft-params.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/platform/v1/report.model.ts
  src/app/core/models/platform/v1/reports-query-params.model.ts
  src/app/core/models/report-options.model.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.html
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.spec.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.spec.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
Labels: size/XL

#2869 feat: added script to run test without sharding browsers
  karma.conf.js
  package.json
Labels: size/S

#2868 test: test fix for my expenses scanning receipt issue
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
Labels: size/XS

#2867 fix: sycing receipt showing up even after expense is created
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XS

#2864 fix: added privacy manifest files
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/PrivacyInfo.xcprivacy
Labels: size/S

#2876 feat: update readme for no-parallel command while running test
  README.md
Labels: size/XS

#2877 fix: fixing flaky tests for view-team-report
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
Labels: size/S

#2870 fix: Add notes from Advance req platform
  src/app/fyle/my-view-advance/my-view-advance.page.html
  src/app/fyle/my-view-advance/my-view-advance.page.spec.ts
  src/app/fyle/my-view-advance/my-view-advance.page.ts
Labels: size/S

#2883 fix: Added fix for custom input
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/XS

#2884 fix: bug fixes in mileage perdiem
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/XS

#2874 feat: fix Advance request edit in team advances
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.setup.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
Labels: size/M

#2873 fix: Revert "Revert "feat: Move advance req get to platform API (#2854)" (…
  src/app/core/mock-data/advance-platform.data.ts
  src/app/core/mock-data/advance-request-custom-field-values.data.ts
  src/app/core/mock-data/approval.data.ts
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/platform/v1/advance-request-platform.data.ts
  src/app/core/mock-data/stats-dimension-response.data.ts
  src/app/core/mock-data/unflattened-advance-request.data.ts
  src/app/core/models/advance-request-state.model.ts
  src/app/core/models/approval-public.model.ts
  src/app/core/models/extended-advance-request-public.model.ts
  src/app/core/models/extended_advance.model.ts
  src/app/core/models/platform/advance-request-platform.model.ts
  src/app/core/models/platform/advances-platform.model.ts
  src/app/core/models/platform/custom-fields.model.ts
  src/app/core/models/platform/platform-approval.model.ts
  src/app/core/models/platform/platform-config.model.ts
  src/app/core/models/platform/platform-employee.model.ts
  src/app/core/models/platform/v1/department.model.ts
  src/app/core/models/platform/v1/platform-advance.model.ts
  src/app/core/models/platform/v1/project.model.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/advance.service.spec.ts
  src/app/core/services/advance.service.ts
  src/app/core/services/tasks.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.setup.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-advances/my-advances.page.spec.ts
  src/app/fyle/my-advances/my-advances.page.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.spec.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
  src/app/fyle/my-view-advance/my-view-advance.page.html
  src/app/fyle/my-view-advance/my-view-advance.page.spec.ts
  src/app/fyle/my-view-advance/my-view-advance.page.ts
Labels: size/XL

#2880 fix: fixing flaky tests in split expense page
  src/app/fyle/split-expense/split-expense.page.spec.ts
Labels: size/XS

#2879 feat: tracker for add more files added
  src/app/core/services/tracking.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.spec.ts
  src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts
Labels: size/S

#2887 feat: addAttachment tracker updated for edit case
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.spec.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.ts
Labels: size/S

#2881 feat: trackers for delete file
  src/app/core/services/tracking.service.ts
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.spec.ts
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.ts
Labels: size/S

#2886 feat: tracker for file download completion
  src/app/core/services/tracking.service.ts
  src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.spec.ts
  src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts
Labels: size/XS

#2892 fix: Removed card number property from all tracking events
  src/app/core/mock-data/corporate-card-trackers.data.ts
  src/app/core/models/tracking-properties.model.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
Labels: size/S

#2891 feat: Update README for better understanding
  README.md
Labels: size/XS

#2888 fix: flaky test fix for viewComment component
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
Labels: size/XS

#2878 feat: Move add expenses to platform
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/transactions-outbox.service.spec.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/app/shared/components/create-new-report/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report/create-new-report.component.ts
Labels: size/L

#2889 test: merge expense test fix
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.spec.ts
  src/app/fyle/merge-expense/merge-expense-1.page.spec.ts
  src/app/fyle/merge-expense/merge-expense-2.page.spec.ts
Labels: size/M

#2882 fix: merge expense inconsistency in mobile app
  src/app/core/models/generic-fields-form-values.model.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.spec.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
  src/app/fyle/merge-expense/merge-expense-1.page.spec.ts
  src/app/fyle/merge-expense/merge-expense-2.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/M

#2875 feat: Add eject and add expenses from platform
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/transactions-outbox.service.spec.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/app/shared/components/create-new-report/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report/create-new-report.component.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.spec.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
Labels: size/L

#2885 feat: tracker for file upload completion
  src/app/core/services/tracking.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#2901 fix: fix for failing test related to tracking service
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XS

#2896 test: added test for trackers for mobile verification
  src/app/core/services/payment-modes.service.spec.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
Labels: size/S

#2894 feat: added trackers for mobile number verification
  src/app/core/services/payment-modes.service.spec.ts
  src/app/core/services/payment-modes.service.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/M

#2890 feat: models for platform files api request payload and response - 1
  src/app/core/models/platform/platform-file-generate-urls-response.model.ts
  src/app/core/models/platform/platform-file-post-request-payload.model.ts
  src/app/core/models/platform/platform-file.model.ts
Labels: size/S

#2897 fix: fixed datatype for the data key in platform API response
  src/app/core/mock-data/advance-platform.data.ts
  src/app/core/mock-data/commute-details-response.data.ts
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/mock-data/platform-cost-centers.data.ts
  src/app/core/mock-data/platform-mileage-rate.data.ts
  src/app/core/mock-data/platform-policy-expense.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/mock-data/platform/v1/advance-request-platform.data.ts
  src/app/core/mock-data/platform/v1/expenses-response.data.ts
  src/app/core/mock-data/virtual-card-response.data.ts
  src/app/core/models/platform/platform-api-response.model.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/advance.service.ts
  src/app/core/services/categories.service.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/core/services/cost-centers.service.ts
  src/app/core/services/custom-inputs.service.ts
  src/app/core/services/dependent-fields.service.ts
  src/app/core/services/expense-fields.service.ts
  src/app/core/services/mileage-rates.service.ts
  src/app/core/services/per-diem.service.ts
  src/app/core/services/platform/v1/approver/expenses.service.ts
  src/app/core/services/platform/v1/spender/employees.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/policy.service.ts
  src/app/core/services/tax-group.service.ts
  src/app/core/services/virtual-cards.service.ts
  src/app/core/test-data/dependent-fields.service.spec.data.ts
Labels: size/M

#2902 fix: eslint diff fix for base branch
  package.json
Labels: size/XS

#2906 fix: remove /txns from create report flow
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
Labels: size/M

#2898 feat: add methods to get reports approvers
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
Labels: size/M
