Repository fylein/fyle-mobile-app, pull requests merged in 2024-01, with the labels that each got.

#2664 feat:kill compliances 3
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/core/mock-data/platform/v1/expense-duplicate-sets.data.ts
  src/app/core/models/v2/duplicate-sets.model.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/M

#2654 feat: Kill compliances (Part 2)
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/core/mock-data/platform/v1/expense-duplicate-sets.data.ts
  src/app/core/models/v2/duplicate-sets.model.ts
  src/app/core/services/handle-duplicates.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.spec.ts
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.ts
Labels: size/L

#2665 fix: Fixed the Select All and Stats Issue on My Expenses V2 Page
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
Labels: size/S

#2657 feat: Move Stats to Platform: Dashboard Service and Tests
  src/app/core/mock-data/platform/v1/expenses-stats.data.ts
  src/app/core/mock-data/stats.data.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/dashboard/dashboard.service.ts
Labels: size/L

#2662 feat: Move Stats to Platform: My Expenses V2 Page
  .github/workflows/unit-tests.yml
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/shared/expenses.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
Labels: size/M

#2651 feat: Kill compliances (Part 1)
  src/app/core/mock-data/duplicate-sets.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/platform/v1/expense-duplicate-sets.data.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/platform/v1/expense-duplicate-sets.model.ts
  src/app/core/models/v2/duplicate-sets.model.ts
  src/app/core/services/handle-duplicates.service.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.spec.ts
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.ts
Labels: size/L

#2666 fix: Move My Expenses To Platform: Fixed Offline Delete Button
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.html
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.spec.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
Labels: size/M

#2667 fix: Move My Expenses To Platform: Fixing Delete Button
  src/app/core/services/platform/v1/shared/expenses.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.html
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
Labels: size/M

#2668 feat: Deprecate older pages for my view report and view team report pages
  .github/workflows/unit-tests.yml
  src/app/core/models/org-settings.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/fyle-routing.module.ts
  src/app/fyle/my-view-report/add-expenses-to-report-v2/add-expenses-to-report-v2.component.html
  src/app/fyle/my-view-report/add-expenses-to-report-v2/add-expenses-to-report-v2.component.scss
  src/app/fyle/my-view-report/add-expenses-to-report-v2/add-expenses-to-report-v2.component.spec.ts
  src/app/fyle/my-view-report/add-expenses-to-report-v2/add-expenses-to-report-v2.component.ts
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.spec.ts
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.ts
  src/app/fyle/my-view-report/edit-report-name-popover-v2/edit-report-name-popover.component.html
  src/app/fyle/my-view-report/edit-report-name-popover-v2/edit-report-name-popover.component.scss
  src/app/fyle/my-view-report/edit-report-name-popover-v2/edit-report-name-popover.component.spec.ts
  src/app/fyle/my-view-report/edit-report-name-popover-v2/edit-report-name-popover.component.ts
  src/app/fyle/my-view-report/my-view-report-routing.module.ts
  src/app/fyle/my-view-report/my-view-report-v2-routing.module.ts
  src/app/fyle/my-view-report/my-view-report-v2.module.ts
  src/app/fyle/my-view-report/my-view-report-v2.page.html
  src/app/fyle/my-view-report/my-view-report-v2.page.spec.ts
  src/app/fyle/my-view-report/my-view-report-v2.page.ts
  src/app/fyle/my-view-report/my-view-report.module.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/my-view-report/share-report-v2/share-report.component.html
  src/app/fyle/my-view-report/share-report-v2/share-report.component.scss
  src/app/fyle/my-view-report/share-report-v2/share-report.component.spec.ts
  src/app/fyle/my-view-report/share-report-v2/share-report.component.ts
  src/app/fyle/my-view-report/share-report/share-report.component.spec.ts
  src/app/fyle/view-team-report/share-report-v2/share-report.component.html
  src/app/fyle/view-team-report/share-report-v2/share-report.component.scss
  src/app/fyle/view-team-report/share-report-v2/share-report.component.spec.ts
  src/app/fyle/view-team-report/share-report-v2/share-report.component.ts
  src/app/fyle/view-team-report/share-report/share-report.component.spec.ts
  src/app/fyle/view-team-report/view-team-report-v2-routing.module.ts
  src/app/fyle/view-team-report/view-team-report-v2.module.ts
  src/app/fyle/view-team-report/view-team-report-v2.page.html
  src/app/fyle/view-team-report/view-team-report-v2.page.spec.ts
  src/app/fyle/view-team-report/view-team-report-v2.page.ts
  src/app/fyle/view-team-report/view-team-report.module.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-view-report-info-v2/fy-view-report-info.component.html
  src/app/shared/components/fy-view-report-info-v2/fy-view-report-info.component.scss
  src/app/shared/components/fy-view-report-info-v2/fy-view-report-info.component.spec.ts
  src/app/shared/components/fy-view-report-info-v2/fy-view-report-info.component.ts
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.spec.ts
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#2672 fix: BR fix for not updating incomplete expense incase extracted date is present
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#2673 fix: Fix for recent icons related changes
  src/app/core/mock-data/action-sheet-options.data.ts
  src/app/core/models/task-icon.enum.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
  src/app/fyle/my-expenses-v2/add-expense-popover/add-expense-popover.component.html
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/comments-history/audit-history/audit-history.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.html
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
  src/app/shared/components/fy-filters/fy-filters.component.scss
  src/app/shared/icon/icon.module.ts
  src/assets/svg/check-square-fill.svg
  src/assets/svg/expense.svg
Labels: size/S

#2674 fix: Removing Add Expenses to Popover From V2 My Expenses
  src/app/fyle/my-expenses-v2/add-expense-popover/add-expense-popover.component.scss
  src/app/fyle/my-expenses-v2/add-expense-popover/add-expense-popover.component.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.module.ts
Labels: size/M

#2675 fix: Fixing Custom Date Filter Pill in V2 My Expenses
  src/app/fyle/my-expenses-v2/my-expenses.service.ts
  src/app/fyle/my-expenses/my-expenses.service.ts
Labels: size/S

#2680 fix: Fix for history icons
  src/app/core/services/status.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.html
  src/app/fyle/my-expenses-v2/my-expenses-v2.page.scss
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.scss
  src/app/shared/components/comments-history/audit-history/audit-history.component.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.scss
  src/app/shared/icon/icon.module.ts
  src/assets/svg/merge.svg
Labels: size/S

#2679 test: test for newly added method
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/S

#2678 fix: split expense header fix
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/M

#2642 fix: Filter out the ACCOUNTANT role from the roles as it has nothing to do with the spender actions
  src/app/core/services/permissions.service.ts
Labels: size/XS
