Repository fylein/fyle-mobile-app, pull requests merged in 2024-09, with the labels that each got.

#3196 fix: Fyle project category r fix
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3195 feat: add and use ENABLE_MIXPANEL and USE_MIXPANEL_PROXY env variable
  hooks/utils/prod-environment.js
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/router-auth.service.ts
  src/app/core/services/tracking.service.ts
  src/environments/environment.ts
Labels: size/M

#3197 Fix: http interceptor behaviouralbug test
  src/app/core/interceptors/httpInterceptor.spec.ts
Labels: size/L

#3193 fix: httpInterceptor behavioural bug
  src/app/core/interceptors/httpInterceptor.spec.ts
  src/app/core/interceptors/httpInterceptor.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/L

#3199 fix: merge expenses data of expenses is undefined
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XS

#3198 chore: cleanup unused methods
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
Labels: size/M

#3201 feat: move v2/expenses from personal cards page to platform
  src/app/core/mock-data/filter.data.ts
  src/app/core/models/filter-query-params.model.ts
  src/app/core/models/personal-card-date-filter.model.ts
  src/app/core/models/personal-card-filters.model.ts
  src/app/core/models/platform/personal-cards-date-params.model.ts
  src/app/core/models/platform/v1/expenses-query-params.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.html
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/L

#3205 fix: Update artifact version
  .github/workflows/appflow-master.yml
  .github/workflows/appflow-release-branch.yml
  .github/workflows/manual-appflow-1.yml
  .github/workflows/manual-appflow-with-inputs.yml
Labels: size/XS

#3211 fix: Replace the scanning receipt loader for single mode
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3212 fix: lint fixes in fy-currency
  src/app/core/models/currency-amount-form-values.model.ts
  src/app/shared/components/fy-currency/fy-currency.component.ts
Labels: size/M

#3204 fix: Add optional chaining to check if id exists before redirection
  src/app/fyle/dashboard/tasks/tasks.component.ts
Labels: size/XS

#3209 fix: feature branch for auto-coding issues
  src/app/core/models/currency-amount-form-values.model.ts
  src/app/core/services/loader.service.spec.ts
  src/app/core/services/loader.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.scss
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.scss
  src/app/shared/components/fy-currency/fy-currency.component.html
  src/app/shared/components/fy-currency/fy-currency.component.scss
  src/app/shared/components/fy-currency/fy-currency.component.spec.ts
  src/app/shared/components/fy-currency/fy-currency.component.ts
  src/assets/images/scanning.gif
  src/assets/svg/sparkle.svg
  src/assets/svg/stars-filled.svg
  src/global.scss
Labels: size/L

#3213 fix: Reverted interceptor changes
  src/app/core/interceptors/httpInterceptor.spec.ts
  src/app/core/interceptors/httpInterceptor.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/L

#3216 fix: TypeError: Cannot read properties of undefined (reading 'currency')
  src/app/shared/components/fy-currency/fy-currency.component.ts
Labels: size/XS

#3217 fix: PR Size CI Version Update
  .github/workflows/pr-size-label.yml
Labels: size/XS

#3214 fix: Filter extracted merchant name before display
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S
