Repository fylein/fyle-mobile-app, pull requests merged in 2024-10, with the labels that each got.

#3215 fix: fix reference for system_category field to make sub categories visible in Mileage Form
  src/app/core/mock-data/org-category.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/XS

#3218 fix: If the org vendor list is empty, auto code the extracted vendor
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3221 chore: Move release branch creation to monday
  .github/workflows/create-release-branch.yml
Labels: size/XS

#3220 feat: migrate public currency and exchange rate api to platform
  src/app/core/mock-data/currency.data.ts
  src/app/core/models/exchange-rate-response.model.ts
  src/app/core/services/currency.service.spec.ts
  src/app/core/services/currency.service.ts
  src/app/core/services/platform-common-api.service.spec.ts
  src/app/core/services/platform-common-api.service.ts
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/router-auth.service.ts
Labels: size/M

#3222 chore: change the last release branch to mondays release branch
  .github/workflows/create-release-branch.yml
Labels: size/XS

#3227 Remove DE related logic from TransactionOutboxService and expenses card component
  src/app/core/services/transactions-outbox.service.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/L

#3226 feat: TransactionService changes for expenses POST to platform
  README.md
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/M

#3225 feat: ExpensesService.createFromFile()
  README.md
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/L

#3224 feat: ExpensesService.transformTo method for moving expenses POST to platform
  README.md
  src/app/core/mock-data/transaction.data.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/L

#3234 feat: adding Arjun as code owner
  .github/CODEOWNERS
Labels: size/XS

#3231 test: Add unit tests for DE polling
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/L

#3230 fix: remove dead test code, fix failing tests
  src/app/core/services/transactions-outbox.service.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
Labels: size/M

#3237 fix: remove orgUserSettingsService.getAllowedCostCenters - use cost centers service
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/M

#3240 fix: toggle and page visibility for Virtual Cards
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/M

#3238 fix: Add missing fields to the POST call of expenses
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
Labels: size/XL

#3229 feat: New polling logic for DE
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.spec.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/L

#3243 fix: fix CTA visibility for `Add Corporate Card` CTA
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
Labels: size/XS

#3241 chore:removing bulkfyle from mobile-app
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.html
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.spec.ts
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.html
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
Labels: size/M

#3236 feat: mobile app refiner integration
  hooks/utils/prod-environment.js
  src/app/core/services/refiner.service.spec.ts
  src/app/core/services/refiner.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/environments/environment.ts
  src/index.html
Labels: size/L

#3244 fix: Duplicate Users being added to User List
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
Labels: size/XS

#3247 fix: resolving the bulk reciept upload by adding the bulkfyle input
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.html
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.html
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
Labels: size/XS
