Repository fylein/fyle-mobile-app, pull requests merged in 2024-06, with the labels that each got.

#3025 fix: fixed eslint issues
  src/app/core/models/receipt-preview-data.model.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
Labels: size/M

#3036 test: Add test for simple search
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
Labels: size/M

#3043 feat: hiding Message Receipts card from profile page for IN cluster users - part 2
  src/app/core/services/tasks.service.spec.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/M

#3034 feat: hiding mobile number section for IN cluster users - part 1
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.html
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.scss
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/M

#3035 feat: opt-in dialog as shared component
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/core/enums/opt-in-flow-state.enum.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/app/shared/components/fy-opt-in/fy-opt-in.component.spec.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
  src/app/shared/icon/icon.module.ts
  src/app/shared/shared.module.ts
  src/assets/images/opt-in-success.gif
  src/assets/svg/arrow-tail-right.svg
  src/assets/svg/sparkle.svg
  src/global.scss
Labels: size/XL

#3032 feat: fix simple search issues
  src/app/core/mock-data/api-params.data.ts
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/services/api-v2.service.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
Labels: size/M

#3050 fix: fix date keys in template
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/team-reports/team-reports.page.html
Labels: size/XS

#3051 fix: fix comment ordering and add support for edge case
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/S

#3052 fix: Fy-select-project-modal is not working properly with new selected
  src/app/core/mock-data/org-category.data.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
Labels: size/M

#3003 fix: null behavior of category_ids Platform Projects Migration
  src/app/core/mock-data/org-category.data.ts
  src/app/core/mock-data/platform/v1/platform-project-args.data.ts
  src/app/core/mock-data/platform/v1/platform-project.data.ts
  src/app/core/mock-data/platform/v1/platform-projects-params.data.ts
  src/app/core/models/platform/platform-project.model.ts
  src/app/core/models/platform/v1/platform-project-args.model.ts
  src/app/core/models/platform/v1/platform-project-params.model.ts
  src/app/core/models/v2/project-v2.model.ts
  src/app/core/services/projects.service.spec.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/recently-used-items.service.spec.ts
  src/app/core/services/recently-used-items.service.ts
  src/app/core/test-data/projects.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
Labels: size/XL

#3039 feat: clean up report service
  src/app/core/mock-data/api-reports.data.ts
  src/app/core/mock-data/stats-response.data.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
Labels: size/XL

#3037 feat: remove erpt from deep link redirection page and clean up report code
  src/app/core/mock-data/api-reports.data.ts
  src/app/core/mock-data/stats-response.data.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/deep-link-redirection/deep-link-redirection.page.spec.ts
  src/app/deep-link-redirection/deep-link-redirection.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
Labels: size/XL

#3046 test: Opt in shared component tests - Part 3
  src/app/shared/components/fy-opt-in/fy-opt-in.component.spec.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
Labels: size/M

#3045 test: Opt in shared component tests - Part 2
  src/app/shared/components/fy-opt-in/fy-opt-in.component.spec.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
Labels: size/L

#3044 test: Opt in shared component tests - Part 1
  src/app/shared/components/fy-opt-in/fy-opt-in.component.spec.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
Labels: size/L

#3049 test: unit test for task changes for opt in
  src/app/core/mock-data/task-cta.data.ts
  src/app/core/mock-data/task.data.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/fyle/dashboard/tasks/tasks-1.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
Labels: size/M

#3054 test: fix my view report flaky test
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
Labels: size/XS

#3048 feat: task changes related to SMS Opt in
  src/app/core/mock-data/task-cta.data.ts
  src/app/core/mock-data/task.data.ts
  src/app/core/models/task-icon.enum.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/dashboard/tasks/tasks-1.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
  src/app/shared/icon/icon.module.ts
  src/assets/svg/stars-filled.svg
Labels: size/M

#3041 fix: updated the platform expense observable to reduce api calls
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
Labels: size/M

#3056 fix: fixed getCategoryById duplicate calls in add-edit expense page
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3055 fix: fixed duplicate calls for reports
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/S

#3064 feat: Advance Wallet per diem changes - PR4
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/L

#3061 feat: Advance Wallet mileage form changes PR3
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/mileage-form-value.model.ts
  src/app/core/models/platform/v1/advance-wallet.model.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/L

#3057 feat: Advance Wallet expense form changes PR2
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/mock-data/txn-account.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/account-option.model.ts
  src/app/core/models/extended-account.model.ts
  src/app/core/models/mileage-form-value.model.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/platform/v1/advance-wallet.model.ts
  src/app/core/services/accounts.service.spec.ts
  src/app/core/services/accounts.service.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/platform/v1/spender/advance-wallets.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/XL

#3063 feat: added opt out flow
  src/app/core/services/tracking.service.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/M

#3059 feat: added changes related to opt-in profile page changes
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.spec.ts
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.ts
  src/app/core/mock-data/info-card-data.data.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.html
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.scss
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/shared.module.ts
Labels: size/L

#3065 fix: add ldFlag to per-diem and mileage
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/M

#3068 fix: breaking testcases per-diem + mileage
  src/app/core/mock-data/org-category.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
Labels: size/M

#3066 fix: Projects field fix for per diem and mileage page
  src/app/core/mock-data/org-category.data.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/M

#3067 fix: updating the expense observable on adding or removing receipt
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3060 fix: Deep link redirection fix
  src/app/deep-link-redirection/deep-link-redirection.page.spec.ts
  src/app/deep-link-redirection/deep-link-redirection.page.ts
Labels: size/XS

#3058 feat: Advance Wallet services expense mileage and per diem forms
  src/app/core/mock-data/form-value.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/org-user-settings.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/platform/v1/advance-wallet.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-expense.data.ts
  src/app/core/mock-data/txn-account.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/account-option.model.ts
  src/app/core/models/expense.model.ts
  src/app/core/models/extended-account.model.ts
  src/app/core/models/mileage-form-value.model.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/models/platform/v1/advance-wallet.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/accounts.service.spec.ts
  src/app/core/services/accounts.service.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/platform/v1/spender/advance-wallets.service.spec.ts
  src/app/core/services/platform/v1/spender/advance-wallets.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/XL

#3073 fix: Advance Wallet changes - should not add company account to payment mode when advance wallet id is present
  src/app/core/services/accounts.service.ts
  src/app/core/services/org-settings.service.ts
Labels: size/XS

#3080 feat: Bring blackwidow env for creating builds
  .github/workflows/manual-appflow-with-inputs.yml
Labels: size/XS

#3082 feat: Update manual-appflow-with-inputs.yml to support all dev envs
  .github/workflows/manual-appflow-with-inputs.yml
Labels: size/XS

#3070 fix: fixed the additional api calls happening on my expense page
  src/app/core/services/transaction.service.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XS

#3091 fix: minor UI/UX fixes for opt in
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/global.scss
Labels: size/S

#3090 test: test coverage of dashboard optin banner
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.spec.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/global.scss
Labels: size/M

#3088 feat: added banner in dashboard
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/core/services/tracking.service.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.html
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.spec.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/L

#3085 test: covered test for utility service and feature config service
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/core/mock-data/feature-config.data.ts
  src/app/core/services/platform/v1/spender/feature-config.service.spec.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.html
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.spec.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/XL

#3079 test: covered test for dashboard page
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/core/mock-data/feature-config.data.ts
  src/app/core/services/platform/v1/spender/feature-config.service.spec.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.html
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.spec.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/XL

#3078 test: covered test for my-expenses page
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/core/mock-data/feature-config.data.ts
  src/app/core/services/platform/v1/spender/feature-config.service.spec.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.html
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.spec.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/XL

#3077 test: covered test for promote-opt-in-modal and manage card page
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/core/mock-data/feature-config.data.ts
  src/app/core/services/platform/v1/spender/feature-config.service.spec.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.html
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.spec.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.spec.ts
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.ts
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/XL

#3076 test: covered test for opt-in guard
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/core/guards/opt-in.guard.spec.ts
  src/app/core/guards/opt-in.guard.ts
  src/app/core/mock-data/feature-config.data.ts
  src/app/core/services/platform/v1/spender/feature-config.service.spec.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.html
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.spec.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.spec.ts
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.ts
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/XL

#3075 feat: added opt-in modal in dashboard and manage CC
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/core/guards/opt-in.guard.spec.ts
  src/app/core/guards/opt-in.guard.ts
  src/app/core/mock-data/feature-config.data.ts
  src/app/core/services/platform/v1/spender/feature-config.service.spec.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.html
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.spec.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.spec.ts
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.ts
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/XL

#3072 feat: added navigation condition in my expenses page
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/core/guards/opt-in.guard.spec.ts
  src/app/core/guards/opt-in.guard.ts
  src/app/core/mock-data/feature-config.data.ts
  src/app/core/models/feature-config.model.ts
  src/app/core/services/platform/v1/spender/feature-config.service.spec.ts
  src/app/core/services/platform/v1/spender/feature-config.service.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/fyle-routing.module.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.html
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.spec.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.spec.ts
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.ts
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/XL

#3071 feat: show promotional modal after 2 second - Part 1
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/core/guards/opt-in.guard.spec.ts
  src/app/core/guards/opt-in.guard.ts
  src/app/core/mock-data/feature-config.data.ts
  src/app/core/models/feature-config.model.ts
  src/app/core/services/platform/v1/spender/feature-config.service.spec.ts
  src/app/core/services/platform/v1/spender/feature-config.service.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/fyle-routing.module.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.html
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.spec.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.html
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.scss
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.spec.ts
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.ts
  src/app/shared/shared.module.ts
  src/assets/images/promote-opt-in.gif
  src/global.scss
  src/theme/colors.scss
Labels: size/XL

#3074 feat: Changing edit expense form & card design on dashboard
  src/app/core/mock-data/corporate-card-transaction-response.data.ts
  src/app/core/mock-data/matchedCCTransaction.data.ts
  src/app/core/models/platform/v1/corporate-card.model.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/view-expense/view-expense.page.html
  src/app/shared/components/card-number/card-number.component.html
  src/app/shared/components/card-number/card-number.component.scss
  src/app/shared/components/card-number/card-number.component.ts
  src/app/shared/components/corporate-card/corporate-card.component.html
  src/app/shared/components/corporate-card/corporate-card.component.scss
Labels: size/M

#3093 fix: remove manual flag feature code
  src/app/core/models/expense.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/platform/v1/report.model.ts
  src/app/core/models/public-policy-expense.model.ts
  src/app/core/models/report-unflattened.model.ts
  src/app/core/models/report-v1.model.ts
  src/app/core/models/report.model.ts
  src/app/core/models/unformatted-transaction.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/launch-darkly.service.spec.ts
  src/app/core/services/launch-darkly.service.ts
  src/app/core/services/policy.service.spec.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-1.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.html
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
  src/app/shared/components/reports-card/reports-card.component.html
  src/app/shared/components/reports-card/reports-card.component.spec.ts
  src/app/shared/components/reports-card/reports-card.component.ts
Labels: size/XL

#3092 fix: major ui fix for opt-in promotional modal;
  src/app/core/guards/opt-in.guard.spec.ts
  src/app/core/guards/opt-in.guard.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/utility.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.html
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/fy-opt-in/fy-opt-in.component.spec.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.html
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.scss
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.spec.ts
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.ts
Labels: size/L

#3102 fix: file location was incorrect of profile-opt-in-card
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.spec.ts
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.ts
  src/app/shared/shared.module.ts
Labels: size/XS

#3100 fix: SMS opt in design QA fix
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.html
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.scss
  src/app/shared/components/fy-opt-in/fy-opt-in.component.spec.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.spec.ts
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.ts
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.html
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.scss
  src/app/shared/components/promote-opt-in-modal/promote-opt-in-modal.component.ts
  src/app/shared/shared.module.ts
  src/assets/images/opt-in-success.gif
  src/assets/svg/check-circle-fill.svg
  src/global.scss
Labels: size/M

#3105 fix: remove settlement_id references
  src/app/core/mock-data/advance-platform.data.ts
  src/app/core/mock-data/api-reports.data.ts
  src/app/core/mock-data/cc-transaction.data.ts
  src/app/core/mock-data/ccc-api-response.data.ts
  src/app/core/mock-data/corporate-card-expense-flattened.data.ts
  src/app/core/mock-data/corporate-card-expense-unflattened.data.ts
  src/app/core/mock-data/corporate-card-transaction-response.data.ts
  src/app/core/mock-data/data-transform.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/mock-data/matchedCCCTransaction.data.ts
  src/app/core/mock-data/matchedCCTransaction.data.ts
  src/app/core/mock-data/option.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/report-options.data.ts
  src/app/core/mock-data/report-unflattened.data.ts
  src/app/core/mock-data/report-v1.data.ts
  src/app/core/mock-data/report.data.ts
  src/app/core/models/corporate-card-expense-flattened.model.ts
  src/app/core/models/corporate-card-expense-unflattened.model.ts
  src/app/core/models/extended_advance.model.ts
  src/app/core/models/matchedCCCTransaction.model.ts
  src/app/core/models/platform/advances-platform.model.ts
  src/app/core/models/platform/v1/cc-transaction.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/platform/v1/report.model.ts
  src/app/core/models/report-unflattened.model.ts
  src/app/core/models/report-v1.model.ts
  src/app/core/models/report.model.ts
  src/app/core/models/v2/corporate-card-expense.model.ts
  src/app/core/services/advance.service.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/core/test-data/tasks.service.spec.data.ts
Labels: size/M

#3107 fix: remove console log
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XS

#3095 feat: show mobile number and delete CTA if user not opted in
  src/app/core/services/tracking.service.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.scss
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.ts
Labels: size/M

#3115 fix: task is not refreshed when opted in from dashboard
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
Labels: size/XS

#3109 feat: add eslint rule for noconsole
  .eslintrc.json
Labels: size/XS

#3103 feat: Move suggest purpose to platform
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.spec.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
Labels: size/M

#3116 feat: move submit POST call to platform
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
Labels: size/M

#3117 feat: Move resubmit to platform
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
Labels: size/S

#3120 fix: when redirected to reports page, it is coming up twice
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XS

#3119 test: tests for newly added extra api call
  src/app/core/mock-data/corporate-card-transaction-response.data.ts
  src/app/core/mock-data/platform/v1/expenses-query-params.data.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
Labels: size/L

#3118 fix: make extra call for getting ccc status
  src/app/core/mock-data/corporate-card-transaction-response.data.ts
  src/app/core/mock-data/platform/v1/expenses-query-params.data.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/L

#3122 fix: Do not show pending transactions to add to report
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XS

#3084 feat: new eslint rule for restricting more than 1 interface
  .eslintrc.json
  eslint-custom-rules/index.js
  eslint-custom-rules/rules/eslint-plugin-one-interface-per-file.js
Labels: size/M

#3124 feat: add eslint rule for proper extesion name
  .eslintrc.json
  eslint-custom-rules/index.js
  eslint-custom-rules/rules/eslint-plugin-prefer-semantic-extension-name.js
Labels: size/S

#3123 feat: add eslint rule for allowing only one enum per file
  .eslintrc.json
  eslint-custom-rules/index.js
  eslint-custom-rules/rules/eslint-plugin-one-enum-per-file.js
  eslint-custom-rules/rules/eslint-plugin-prefer-semantic-extension-name.js
Labels: size/M

#3126 fix: dont use DE if not needed
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS
