Repository fylein/fyle-mobile-app, pull requests merged in 2024-05, with the labels that each got.

#2936 fix: Linting errors from fy-select-project.component
  src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.ts
Labels: size/S

#2931 fix: linting errors from fy-select-project-modal.component
  src/app/core/mock-data/extended-projects.data.ts
  src/app/core/models/project-options.model.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
Labels: size/M

#2938 fix: Typescript Types | Fix failing test cases
  src/app/shared/components/fy-select-project/fy-select-project.component.ts
Labels: size/XS

#2923 feat: Replace ExtendedProject -> ProjectV2
  src/app/core/mock-data/recently-used.data.ts
  src/app/core/models/add-edit-advance-request-form-value.model.ts
  src/app/core/models/mileage-form-value.model.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/models/project-options.model.ts
  src/app/core/models/split-expense.model.ts
  src/app/core/models/v2/project-v2.model.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/recently-used-items.service.ts
  src/app/core/test-data/projects.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.ts
Labels: size/M

#2942 feat: Add transformToV1Response & transformToV2Response for PlatformProject
  src/app/core/models/platform/platform-project.model.ts
  src/app/core/models/v2/project-v2.model.ts
  src/app/core/services/projects.service.ts
Labels: size/M

#2944 fix: Make projectService name consistent
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/services/projects.service.spec.ts
  src/app/core/services/recently-used-items.service.spec.ts
  src/app/core/services/recently-used-items.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
Labels: size/M

#2945 test: fixing tests - part 5
  src/app/core/services/location.service.spec.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/post-verification/setup-account/setup-account.page.spec.ts
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.spec.ts
Labels: size/M

#2943 test: fixing tests - part 4
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance.service.spec.ts
  src/app/core/services/date.service.spec.ts
  src/app/core/services/location.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/post-verification/setup-account/setup-account.page.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.spec.ts
Labels: size/L

#2941 test: fixing tests - part 3
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance.service.spec.ts
  src/app/core/services/custom-fields.service.spec.ts
  src/app/core/services/date.service.spec.ts
  src/app/core/services/expense-fields.service.spec.ts
  src/app/core/services/location.service.spec.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/org-settings.service.spec.ts
  src/app/core/services/recent-local-storage-items.service.spec.ts
  src/app/core/services/status.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/notifications/notifications.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/post-verification/setup-account/setup-account.page.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
  src/app/shared/components/route-selector/route-selector.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.spec.ts
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.spec.ts
Labels: size/L

#2940 test: fixing tests - part 2
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance.service.spec.ts
  src/app/core/services/custom-fields.service.spec.ts
  src/app/core/services/date.service.spec.ts
  src/app/core/services/expense-fields.service.spec.ts
  src/app/core/services/location.service.spec.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/org-settings.service.spec.ts
  src/app/core/services/recent-local-storage-items.service.spec.ts
  src/app/core/services/status.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/notifications/notifications.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/post-verification/setup-account/setup-account.page.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
  src/app/shared/components/route-selector/route-selector.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.spec.ts
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.spec.ts
Labels: size/XL

#2939 test: fixing tests - part 1
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance.service.spec.ts
  src/app/core/services/categories.service.spec.ts
  src/app/core/services/custom-fields.service.spec.ts
  src/app/core/services/date.service.spec.ts
  src/app/core/services/dependent-fields.service.spec.ts
  src/app/core/services/expense-fields.service.spec.ts
  src/app/core/services/file.service.spec.ts
  src/app/core/services/location.service.spec.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/org-settings.service.spec.ts
  src/app/core/services/org.service.spec.ts
  src/app/core/services/recent-local-storage-items.service.spec.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/status.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/merge-expense/merge-expense-3.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/notifications/notifications.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/post-verification/setup-account/setup-account.page.spec.ts
  src/app/shared/components/comments-history/audit-history/audit-history.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.spec.ts
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.spec.ts
  src/app/shared/components/route-selector/route-selector.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.spec.ts
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.spec.ts
Labels: size/XL

#2934 feat: added deepFreeze to not pollute global mock data - Part 15
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance.service.spec.ts
  src/app/core/services/categories.service.spec.ts
  src/app/core/services/custom-fields.service.spec.ts
  src/app/core/services/date.service.spec.ts
  src/app/core/services/dependent-fields.service.spec.ts
  src/app/core/services/expense-fields.service.spec.ts
  src/app/core/services/file.service.spec.ts
  src/app/core/services/location.service.spec.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/org-settings.service.spec.ts
  src/app/core/services/org.service.spec.ts
  src/app/core/services/recent-local-storage-items.service.spec.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/status.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/utility.service.spec.ts
  src/app/core/services/virtual-cards.service.spec.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/custom-inputs.spec.data.ts
  src/app/core/test-data/deep-link.service.spec.data.ts
  src/app/core/test-data/dependent-fields.service.spec.data.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/core/test-data/org-user.service.spec.data.ts
  src/app/core/test-data/per-diem.service.spec.data.ts
  src/app/core/test-data/projects.spec.data.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/core/test-data/tasks.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/merge-expense/merge-expense-3.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/notifications/notifications.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/post-verification/setup-account/setup-account.page.spec.ts
  src/app/shared/components/comments-history/audit-history/audit-history.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.spec.ts
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.spec.ts
  src/app/shared/components/route-selector/route-selector.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.spec.ts
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.spec.ts
Labels: size/XL

#2949 fix: Add cache buster
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
Labels: size/M

#2950 fix: fix platform spender reports test coverage
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
Labels: size/S

#2948 fix: Adds back eject expense and add expense changes
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/transactions-outbox.service.spec.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/app/shared/components/create-new-report/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report/create-new-report.component.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.spec.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
Labels: size/XL

#2895 feat: add methods to get reports - spender
  src/app/core/models/platform/v1/platform-stats-request-param.model.ts
  src/app/core/models/platform/v1/reports-query-params.model.ts
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
Labels: size/L

#2946 feat: Migrate getbyId -> spenderPlatformV1ApiService
  src/app/core/mock-data/platform/v1/platform-project.data.ts
  src/app/core/services/projects.service.spec.ts
  src/app/core/services/projects.service.ts
  src/app/core/test-data/projects.spec.data.ts
Labels: size/M

#2907 feat: Move report stats call to platform in dashboard
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/mock-data/report-stats.data.ts
  src/app/core/models/platform/v1/report-stats-response.model.ts
  src/app/core/models/report-stats.model.ts
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/dashboard/dashboard.service.ts
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.ts
Labels: size/L

#2935 fix: Remove Push Notification feature
  android/app/src/main/assets/capacitor.plugins.json
  android/capacitor.settings.gradle
  android/variables.gradle
  hooks/utils/google-credentials-android.js
  hooks/utils/google-credentials-ios.js
  ios/App/App/AppDelegate.swift
  ios/App/Podfile
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/app/core/services/push-notification.service.spec.ts
  src/app/core/services/push-notification.service.ts
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/router-auth.service.ts
Labels: size/L

#2958 fix: Fix for tap jacking issue | Fyle vapt 2024
  android/app/src/main/java/com/ionicframework/fyle595781/MainActivity.java
Labels: size/XS

#2959 fix: fix root detection vapt: Close the app if the device is rooted
  android/app/src/main/java/com/ionicframework/fyle595781/MainActivity.java
  android/app/src/main/java/com/ionicframework/fyle595781/utils/RootCheck.java
Labels: size/M

#2967 feat: Migrate getAllActive -> spenderPlatformV1ApiService
  src/app/core/mock-data/platform/v1/platform-project.data.ts
  src/app/core/services/projects.service.spec.ts
  src/app/core/services/projects.service.ts
  src/app/core/test-data/projects.spec.data.ts
Labels: size/M

#2971 test: fix flaky test around expense card
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
Labels: size/M

#2960 fix: prevent findByTxnId() api call from add edit expense form in add mode
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#2954 feat: Migrate getByParamsUnformatted -> spenderPlatformV1ApiService
  src/app/core/mock-data/platform/v1/platform-project.data.ts
  src/app/core/mock-data/platform/v1/platform-projects-params.data.ts
  src/app/core/models/platform/v1/platform-project-params.model.ts
  src/app/core/services/projects.service.spec.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/recently-used-items.service.spec.ts
  src/app/core/services/recently-used-items.service.ts
  src/app/core/test-data/projects.spec.data.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
Labels: size/M

#2981 feat: changing order of stats to expenses->reports
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.scss
Labels: size/M

#2980 fix: Improved test cases ProjectsService
  src/app/core/services/projects.service.spec.ts
Labels: size/S

#2928 fix: Fix tests for tasks page stats changes [2]
  src/app/core/mock-data/report-stats.data.ts
  src/app/core/mock-data/task.data.ts
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/core/test-data/tasks.service.spec.data.ts
Labels: size/L

#2964 fix: Fix create report PR tests [6]
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/report.service.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
Labels: size/S

#2953 feat: Move Create report to platform [5]
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/option.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/app/shared/components/create-new-report/create-new-report.component.html
  src/app/shared/components/create-new-report/create-new-report.component.scss
  src/app/shared/components/create-new-report/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report/create-new-report.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#2961 fix: Fix tests for tasks and my expenses page [4]
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/option.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/app/shared/components/create-new-report/create-new-report.component.html
  src/app/shared/components/create-new-report/create-new-report.component.scss
  src/app/shared/components/create-new-report/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report/create-new-report.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#2947 test: fixing eslint issues for resolveTo
  src/app/auth/new-password/popup/popup.component.spec.ts
  src/app/auth/request-invitation/request-invitation.page.spec.ts
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/core/services/app-version.service.spec.ts
  src/app/core/services/auth.service.spec.ts
  src/app/core/services/config.service.spec.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/currency.service.spec.ts
  src/app/core/services/custom-inputs.service.spec.ts
  src/app/core/services/google-auth.service.spec.ts
  src/app/core/services/launch-darkly.service.spec.ts
  src/app/core/services/loader.service.spec.ts
  src/app/core/services/login-info.service.spec.ts
  src/app/core/services/org-user.service.spec.ts
  src/app/core/services/refiner.service.spec.ts
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/storage.service.spec.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/token.service.spec.ts
  src/app/deep-link-redirection/deep-link-redirection.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.spec.ts
Labels: size/L

#2983 fix: fix stats call for orgs where user is not an approver
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/core/test-data/tasks.service.spec.data.ts
Labels: size/M

#2974 feat: use generateUrlsBulk() in merge expenses
  src/app/core/mock-data/generate-urls-bulk-response.data.ts
  src/app/core/mock-data/receipt-info.data.ts
  src/app/core/models/receipt-info.model.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
Labels: size/M

#2921 feat: Move stats call in tasks to platform [1]
  src/app/core/mock-data/report-stats.data.ts
  src/app/core/mock-data/task.data.ts
  src/app/core/models/platform/v1/platform-stats-request-param.model.ts
  src/app/core/models/platform/v1/report-stats-response.model.ts
  src/app/core/models/report-stats.model.ts
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/core/test-data/tasks.service.spec.data.ts
  src/app/fyle/dashboard/stats/stats.component.ts
Labels: size/L

#2952 feat: Move tasks, My Expenses, add expenses to report popup and create report to platform [3]
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/option.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/models/platform/v1/reports-query-params.model.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-3.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.spec.ts
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/app/shared/components/create-new-report/create-new-report.component.html
  src/app/shared/components/create-new-report/create-new-report.component.scss
  src/app/shared/components/create-new-report/create-new-report.component.spec.ts
  src/app/shared/components/create-new-report/create-new-report.component.ts
  src/app/shared/shared.module.ts
Labels: size/XL

#2966 feat: lauchDarkly flag added for deprecating manual flag feature
  src/app/core/services/launch-darkly.service.ts
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.html
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.ts
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.html
  src/app/fyle/potential-duplicates/potential-duplicates.page.ts
  src/app/fyle/team-reports/team-reports.page.html
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.html
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/reports-card/reports-card.component.html
  src/app/shared/components/reports-card/reports-card.component.ts
Labels: size/M

#2989 fix: Revert "feat: lauchDarkly flag added for deprecating manual flag feature (#2966)"
  src/app/core/services/launch-darkly.service.ts
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.html
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.ts
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-create-report/my-create-report.page.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/potential-duplicates/potential-duplicates.page.html
  src/app/fyle/potential-duplicates/potential-duplicates.page.ts
  src/app/fyle/team-reports/team-reports.page.html
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.html
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/reports-card/reports-card.component.html
  src/app/shared/components/reports-card/reports-card.component.ts
Labels: size/M

#2987 fix: sentry issue fix for add-edit-expense
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#2990 fix: fix mixpanel event for opt-in task click
  src/app/core/services/tracking.service.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/dashboard/dashboard.service.ts
  src/app/fyle/dashboard/stats/stats.component.spec.ts
  src/app/fyle/dashboard/stats/stats.component.ts
Labels: size/M

#2988 fix: revert back approver stats to public
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
Labels: size/M

#2975 feat: replace downloadUrl() with generateUrls() in view mileage page
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
Labels: size/M

#2956 feat: Add approver API changes to View Expense, Mileage, per diem [7]
  src/app/core/mock-data/platform-report.data.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/M

#2970 feat: Replace public files api with platform in expense card lite component
  src/app/core/models/matched-expense.model.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.ts
Labels: size/M

#2994 feat: use attach_receipt instead of public post api in expense card v2
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
Labels: size/S

#2995 feat: use attach_receipt instead of public post api in expense card
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/S

#2996 feat: use attach_receipt instead of public post api in expense card
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/XS

#2993 feat: View Expense, Mileage, per diem changes
  src/app/core/mock-data/platform-report.data.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
Labels: size/M

#2965 feat: replace download_url with generate_urls/bulk api call in add edit expense page
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/M

#2984 fix: Remove /api/auth/access_token call happening on reset password
  src/app/auth/new-password/new-password.page.spec.ts
  src/app/auth/new-password/new-password.page.ts
Labels: size/XS

#2985 fix: issue while merging submitted expense tx_id instead of split_gro…
  src/app/fyle/merge-expense/merge-expense-3.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XS

#2982 fix: added return types for update mobile number component
  src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.ts
Labels: size/XS

#2998 feat: use platform expense file_ids instead of public file objects in add edit expense page
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#3000 fix: Revert platform projects
  src/app/core/mock-data/platform/v1/platform-project.data.ts
  src/app/core/mock-data/platform/v1/platform-projects-params.data.ts
  src/app/core/models/platform/platform-project.model.ts
  src/app/core/models/platform/v1/platform-project-params.model.ts
  src/app/core/models/v2/project-v2.model.ts
  src/app/core/services/projects.service.spec.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/recently-used-items.service.spec.ts
  src/app/core/services/recently-used-items.service.ts
  src/app/core/test-data/projects.spec.data.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
Labels: size/L

#3002 feat: use platform expense files key instead of findByTxnId() in split expense page
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/S

#2969 feat: fix eslint issues
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
Labels: size/S

#3005 feat: replace files post api with platform attach receipt to expense api endpoint
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XS

#3006 feat: replace files post api with platform attach receipt to expense api endpoint
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#3009 fix: for merge expenses attachments issue
  src/app/core/mock-data/file-object.data.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
Labels: size/S

#2951 test: updated view expense page unit test to reflect files api migration
  src/app/core/mock-data/platform-file.data.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
Labels: size/S

#3011 fix: Fixing 400 error in POST /platform/v1/spender/expenses/stats
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/S

#3015 feat: Update mobile app readme for code coverage
  README.md
Labels: size/XS

#3008 feat: replace files post call with attach_files/bulk in transaction service
  src/app/core/cache-buster/expense-cache-buster.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
Labels: size/M

#2968 test: Add tests for View report flow [2]
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/models/platform/v1/report.model.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.spec.ts
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
Labels: size/XL

#2963 feat: add report platform API to View Report pages - spender and approver [1]
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/models/platform/v1/level.model.ts
  src/app/core/models/platform/v1/report.model.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.spec.ts
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
Labels: size/XL

#2920 feat: migrate to platform files api in view expense page
  src/app/core/mock-data/platform-file.data.ts
  src/app/core/mock-data/platform/v1/attach-receipt-payload.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/platform/v1/expenses-response.data.ts
  src/app/core/services/platform/v1/approver/file.service.spec.ts
  src/app/core/services/platform/v1/approver/file.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/file.service.spec.ts
  src/app/core/services/platform/v1/spender/file.service.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
Labels: size/M

#3019 feat: use platform files api in txn outbox service
  src/app/core/services/platform/v1/spender/file.service.ts
  src/app/core/services/transactions-outbox.service.ts
Labels: size/M

#3014 feat: hide team reports for non primary orgs
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/M

#3022 fix: Fyle 86cv9y0a4 lint errors resolved
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/reports-card/reports-card.component.ts
Labels: size/M

#3026 fix: return txn directly from transaction service when no files attached
  src/app/core/services/transaction.service.ts
Labels: size/XS

#3028 fix: fix test for permission service
  src/app/core/mock-data/api-params.data.ts
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/get-tasks-query-params.data.ts
  src/app/core/mock-data/my-reports-filters.data.ts
  src/app/core/mock-data/option.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/mock-data/report-actions.data.ts
  src/app/core/mock-data/report-permissions.data.ts
  src/app/core/mock-data/team-reports-filters.data.ts
  src/app/core/models/extended_status.model.ts
  src/app/core/models/get-tasks.query-params.model.ts
  src/app/core/models/platform/v1/comment.model.ts
  src/app/core/models/platform/v1/extended-comment.model.ts
  src/app/core/models/platform/v1/report.model.ts
  src/app/core/models/platform/v1/reports-query-params.model.ts
  src/app/core/models/report-api-params.model.ts
  src/app/core/models/report-permissions.model.ts
  src/app/core/services/permissions.service.spec.ts
  src/app/core/services/permissions.service.ts
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/report.service.spec.ts
  src/app/core/services/report.service.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports-2.page.spec.ts
  src/app/fyle/team-reports/team-reports-3.page.spec.ts
  src/app/fyle/team-reports/team-reports-4.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.html
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
  src/app/shared/components/reports-card/reports-card.component.html
  src/app/shared/components/reports-card/reports-card.component.spec.ts
  src/app/shared/components/reports-card/reports-card.component.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/XL

#3029 feat: delete attachment using platform api
  src/app/core/mock-data/receipt-info.data.ts
  src/app/core/services/platform/v1/spender/file.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.spec.ts
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.ts
Labels: size/M

#3013 fix: add ldFlag for manual flag feature
  src/app/core/services/launch-darkly.service.spec.ts
  src/app/core/services/launch-darkly.service.ts
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.html
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/reports-card/reports-card.component.html
  src/app/shared/components/reports-card/reports-card.component.spec.ts
  src/app/shared/components/reports-card/reports-card.component.ts
Labels: size/L

#3027 feat: Timezone fix final final
  package.json
  src/app/app.component.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/services/date.service.spec.ts
  src/app/core/services/date.service.ts
  src/app/core/services/launch-darkly.service.ts
  src/app/core/services/platform/v1/shared/date.service.spec.ts
  src/app/core/services/platform/v1/shared/date.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.spec.ts
Labels: size/L

#2978 fix: Deprecate Physical Bills on models and dummy data
  src/app/core/mock-data/api-reports.data.ts
  src/app/core/mock-data/data-transform.data.ts
  src/app/core/mock-data/dependent-field-expenses.data.ts
  src/app/core/mock-data/expense-v2.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/expenses-info.data.ts
  src/app/core/mock-data/file-txn.data.ts
  src/app/core/mock-data/option.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/public-policy-expense.data.ts
  src/app/core/mock-data/report-options.data.ts
  src/app/core/mock-data/report-unflattened.data.ts
  src/app/core/mock-data/report-v1.data.ts
  src/app/core/mock-data/report.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-expense.data.ts
  src/app/core/mock-data/undo-merge.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/mock-data/unformatted-transaction.data.ts
  src/app/core/models/date-parameters.model.ts
  src/app/core/models/expense.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/platform/v1/report.model.ts
  src/app/core/models/public-policy-expense.model.ts
  src/app/core/models/report-unflattened.model.ts
  src/app/core/models/report-v1.model.ts
  src/app/core/models/report.model.ts
  src/app/core/models/unformatted-transaction.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/date.service.spec.ts
  src/app/core/services/date.service.ts
  src/app/core/services/transaction.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/tasks.service.spec.data.ts
Labels: size/L

#3030 feat: Adding nickname to edit expense form
  src/app/core/models/matchedCCCTransaction.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3033 feat: Adding nickname to view expense
  src/app/core/models/platform/v1/expense.model.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.ts
Labels: size/XS

#3031 fix: Added a failsafe
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/services/date.service.spec.ts
  src/app/core/services/launch-darkly.service.spec.ts
  src/app/core/services/launch-darkly.service.ts
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.spec.ts
  src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.spec.ts
Labels: size/M

#3040 fix: Added new changes
  src/app/core/services/date.service.spec.ts
  src/app/core/services/platform/v1/shared/date.service.spec.ts
Labels: size/M
