Repository fylein/fyle-mobile-app, pull requests merged in 2025-02, with the labels that each got.

#3461 fix: Decimal value removal for $0
  src/app/shared/pipes/exact-currency.pipe.spec.ts
  src/app/shared/pipes/exact-currency.pipe.ts
  src/app/shared/pipes/humanize-currency.pipe.ts
Labels: size/XS

#3451 fix: Long text two lines + truncate
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/reports-card/reports-card.component.html
  src/app/shared/components/reports-card/reports-card.component.scss
Labels: size/XS

#3462 fix: Sentence case changes
  src/app/core/mock-data/sidemenu-item.data.ts
  src/app/core/mock-data/sidemenu.data.ts
  src/app/core/mock-data/task-cta.data.ts
  src/app/core/mock-data/task.data.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/S

#3467 fix: Newreports enabled cleanup + payment_processing text fix
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/shared/components/summary-tile/summary-tile.component.scss
  src/app/shared/pipes/expense-state.pipe.spec.ts
  src/app/shared/pipes/expense-state.pipe.ts
  src/app/shared/pipes/report-state.pipe.spec.ts
  src/app/shared/pipes/report-state.pipe.ts
  src/theme/colors.scss
Labels: size/M

#3469 fix: Text change from Upload from Gallery to Upload files
  src/app/fyle/add-edit-advance-request/camera-options-popup/camera-options-popup.component.html
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.html
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.spec.ts
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.ts
Labels: size/XS

#3468 fix: downlaod artifact to v4
  .github/workflows/appflow-master.yml
  .github/workflows/appflow-release-branch.yml
  .github/workflows/create-release-branch.yml
  .github/workflows/lint.yml
  .github/workflows/manual-appflow-1.yml
  .github/workflows/manual-appflow-with-inputs.yml
  .github/workflows/unit-tests.yml
Labels: size/M

#3464 chore: remove unused variables and scripts
  README.md
  build_prod.sh
  build_staging.sh
  hooks/prebuild.js
  hooks/utils/prod-environment.js
  src/app/core/services/router-auth.service.ts
  src/environments/environment.ts
Labels: size/S

#3458 fix: Make the default value of mileage locations to {}
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts
  src/app/shared/components/route-selector/route-selector.component.ts
Labels: size/XS

#3471 fix: newreports removal err fix
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.html
  src/app/shared/components/reports-card/reports-card.component.html
Labels: size/XS

#3407 fix: new data should be fetched when a txn is matched, or new expense is created
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/S

#3474 feat: fix issue with opt in skip in case where cards are enrolled
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
Labels: size/S

#3475 fix: hide back button for already enrolled cards on opt in step
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
Labels: size/XS

#3476 fix: fix card type other from going into enroll method
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
Labels: size/XS

#3472 fix: fix card number filter issues
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XS

#3477 fix: Add additional trackers for onboarding
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
Labels: size/S

#3480 fix: fix back CTA in case cards are both skipped and enrolled in OptIn step
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
Labels: size/XS

#3484 fix: hide approver sidemenu item for only approver role onboarding
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/XS

#3486 fix: name changes for Updated on -> Updated date
  src/app/core/mock-data/filter-pills.data.ts
  src/app/core/mock-data/selected-filters.data.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/shared/components/fy-filters/fy-filters.component.spec.ts
Labels: size/S

#3459 fix: send only name and value in check_policies and expenses calls
  src/app/core/mock-data/platform-policy-expense.data.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/policy.service.ts
Labels: size/S

#3478 fix: manual-appflow-with-inputs fix for ios build upload
  .github/workflows/manual-appflow-with-inputs.yml
Labels: size/XS

#3487 fix: name change for Approved on -> Approved date
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.html
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
  src/app/fyle/my-view-advance/my-view-advance.page.html
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.html
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
Labels: size/XS

#3488 fix: date heading name changes for Issued on, Submitted on, Resubmitted on
  src/app/fyle/my-view-advance/my-view-advance.page.html
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.html
Labels: size/XS

#3483 fix: add validation error message for tax amount field when it is greater …
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#3489 fix: change 'reported' -> 'submitted' in css
  src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
Labels: size/XS

#3481 fix: search breaks after creating expense from personal card expense
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/S

#3453 feat: new flow of add-edit expense page
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/L

#3460 fix: update the ui for the new split_expense_page
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.scss
  src/theme/colors.scss
Labels: size/L

#3491 chore: update read me and clean up
  README.md
  src/app/core/models/report-state-map.model.ts
  src/app/shared/format-datepicker/format-datepicker.ts
Labels: size/M

#3495 fix: remove personal identifiable infor from sentry and smarlook
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/services/smartlook.service.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/XS

#3494 feat: show complete transactions instead of total in card details (keep consistency with web-app)
  src/app/core/mock-data/platform-corporate-card-detail.data.ts
  src/app/core/services/tracking.service.ts
  src/app/shared/components/corporate-card/corporate-card.component.scss
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
  src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
  src/app/shared/components/spent-cards/card-detail/card-detail.component.spec.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
Labels: size/M

#3492 chore: upgrade smartlook to v2
  .github/workflows/appflow-master.yml
  .github/workflows/appflow-release-branch.yml
  .github/workflows/internal-release.yml
  .github/workflows/manual-appflow-1.yml
  .github/workflows/manual-appflow-with-inputs.yml
  package-lock.json
  package.json
  src/app/core/services/smartlook.service.ts
Labels: size/M

#3473 feat: Available stat addition for virtual cards UI in settings/My cards
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/shared/components/fy-popover/fy-popover.component.html
  src/app/shared/components/fy-popover/fy-popover.component.scss
  src/app/shared/components/fy-popover/fy-popover.component.ts
  src/app/shared/components/virtual-card/virtual-card.component.html
  src/app/shared/components/virtual-card/virtual-card.component.ts
Labels: size/M

#3496 feat: remove passing of email to refiner
  src/app/core/models/identify-user-payload.model.ts
  src/app/core/models/refiner_properties.model.ts
  src/app/core/services/refiner.service.ts
Labels: size/S

#3497 feat: remove passing of pii to MP
  src/app/app.component.ts
  src/app/auth/new-password/new-password.page.spec.ts
  src/app/auth/new-password/new-password.page.ts
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/auth/verify/verify.page.spec.ts
  src/app/core/mock-data/corporate-card-trackers.data.ts
  src/app/core/mock-data/track-expense-properties.data.ts
  src/app/core/models/add-attachment-properties.model.ts
  src/app/core/models/app-launch-time-properties.model.ts
  src/app/core/models/capture-single-receipt-time-properties.model.ts
  src/app/core/models/card-enrolled-properties.model.ts
  src/app/core/models/card-enrollment-errors-properties.model.ts
  src/app/core/models/card-unenrolled-properties.model.ts
  src/app/core/models/comment-history-action-properties.model.ts
  src/app/core/models/corporate-card-expense-properties.model.ts
  src/app/core/models/create-report-properties.model.ts
  src/app/core/models/enrolling-non-rtf-card-properties.model.ts
  src/app/core/models/event-track-properties.model.ts
  src/app/core/models/expense-click-properties.model.ts
  src/app/core/models/expense-properties.model.ts
  src/app/core/models/filter-pill-clicked-properties.model.ts
  src/app/core/models/footer-button-click-properties.model.ts
  src/app/core/models/identify-properties.model.ts
  src/app/core/models/on-setting-toggle-properties.model.ts
  src/app/core/models/policy-correction-properties.model.ts
  src/app/core/models/report-name-change-properties.model.ts
  src/app/core/models/splitting-expense-properties.model.ts
  src/app/core/models/switch-Oorg-properties.model.ts
  src/app/core/models/switch-org-launch-time-properties.model.ts
  src/app/core/models/task-filter-clear-all-properties.model.ts
  src/app/core/models/task-page-open-properties.model.ts
  src/app/core/models/task-properties.model.ts
  src/app/core/models/tracking-properties.model.ts
  src/app/core/models/view-report-info-properties.model.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/post-verification/setup-account/setup-account.page.spec.ts
  src/app/post-verification/setup-account/setup-account.page.ts
Labels: size/M

#3499 fix: minor sentry fix for merge expense page.
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XS

#3503 chore: use sentence case (auth, fyle, post-verification templates)
  src/app/auth/app-version/app-version.page.html
  src/app/auth/pending-verification/pending-verification.page.html
  src/app/auth/request-invitation/request-invitation.page.html
  src/app/auth/switch-org/active-org-card/active-org-card.component.html
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-advance-request/camera-options-popup/camera-options-popup.component.html
  src/app/fyle/add-edit-advance-request/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.html
  src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/dashboard/tasks/auto-submission-info-card/auto-submission-info-card.component.html
  src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.html
  src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.spec.ts
  src/app/fyle/help/help.page.html
  src/app/fyle/help/support-dialog/support-dialog.page.html
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.html
  src/app/fyle/manage-corporate-cards/card-added/card-added.component.html
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.html
  src/app/fyle/merge-expense/card-transaction-preview/card-transaction-preview.component.html
  src/app/fyle/merge-expense/card-transaction-preview/card-transaction-preview.component.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.html
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-expenses/add-expense-popover/add-expense-popover.component.html
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/select-currency/select-currency.component.html
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
  src/app/fyle/my-view-advance/my-view-advance.page.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.spec.ts
  src/app/fyle/my-view-report/edit-report-name-popover/edit-report-name-popover.component.html
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/share-report/share-report.component.html
  src/app/fyle/notifications/notifications.page.html
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.html
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.html
  src/app/fyle/personal-cards/date-range-modal/date-range-modal.component.html
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/potential-duplicates/potential-duplicates.page.html
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/team-advance/team-advance.page.html
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-team-advance-request/advance-actions/advance-actions.component.html
  src/app/fyle/view-team-advance-request/advance-actions/advance-actions.component.spec.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
  src/app/fyle/view-team-report/share-report/share-report.component.html
  src/app/fyle/view-team-report/share-report/share-report.component.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/post-verification/setup-account-preferences/setup-account-preferences.page.html
  src/app/post-verification/setup-account/select-currency/select-currency.component.html
  src/app/post-verification/setup-account/setup-account.page.html
Labels: size/M

#3505 chore: use sentence case (shared components)
  src/app/shared/components/add-card/add-card.component.html
  src/app/shared/components/bank-account-cards/bank-account-card/delete-button/delete-button-component.html
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.html
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.spec.ts
  src/app/shared/components/capture-receipt/crop-receipt/crop-receipt.component.html
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.html
  src/app/shared/components/corporate-card/corporate-card.component.html
  src/app/shared/components/create-new-report-v2/create-new-report.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card/expenses-card.component.html
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.html
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.spec.ts
  src/app/shared/components/fy-approver/add-approvers-popover/add-approvers-popover.component.html
  src/app/shared/components/fy-approver/add-approvers-popover/add-approvers-popover.component.spec.ts
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.html
  src/app/shared/components/fy-approver/fy-approver.component.html
  src/app/shared/components/fy-approver/fy-approver.component.spec.ts
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
  src/app/shared/components/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.html
  src/app/shared/components/fy-filters/fy-filters.component.html
  src/app/shared/components/fy-opt-in/fy-opt-in.component.html
  src/app/shared/components/fy-policy-violation/fy-policy-violation.component.html
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.html
  src/app/shared/components/fy-select-vendor/fy-select-modal/fy-select-vendor-modal.component.html
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.html
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.html
  src/app/shared/components/mobile-number-card/mobile-number-card.component.html
  src/app/shared/components/popup-alert/popup-alert.component.html
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.html
  src/app/shared/components/review-footer/review-footer.component.html
  src/app/shared/components/review-footer/review-footer.component.spec.ts
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.html
  src/app/shared/components/route-selector/route-selector.component.html
  src/app/shared/components/send-email/send-email.component.html
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.html
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.spec.ts
  src/app/shared/components/transaction-status/transaction-status.component.html
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.html
Labels: size/M

#3510 fix: unit tests for migration of /v2/corporate_card_transactions
  src/app/core/mock-data/corporate-card-expense.data.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/fyle/merge-expense/card-transaction-preview/card-transaction-preview.component.spec.ts
  src/app/fyle/merge-expense/merge-expense-3.page.spec.ts
Labels: size/M

#3512 fix: Name changes for Card -> Card ending in...
  src/app/core/mock-data/filter-pills.data.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/selected-filters.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-expenses/my-expenses.service.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.html
  src/app/fyle/view-expense/view-expense.page.html
Labels: size/S

#3501 feat: replace email with user_id as distinct Id in MP
  src/app/auth/new-password/new-password.page.spec.ts
  src/app/auth/new-password/new-password.page.ts
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/app/auth/verify/verify.page.spec.ts
  src/app/auth/verify/verify.page.ts
  src/app/core/services/tracking.service.ts
Labels: size/M

#3507 fix: icon align add expense to report
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.scss
Labels: size/XS

#3432 fix: File size validation increase
  src/app/core/constants.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.spec.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/expenses-card/expenses-card.component.ts
Labels: size/M

#3511 fix: small font size issue
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.scss
  src/app/shared/components/create-new-report-v2/create-new-report.component.scss
Labels: size/XS

#3508 fix: silently fail patch expense error when in capture receipt flow withou…
  src/app/core/services/tracking.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
Labels: size/M

#3463 feat: add new review-split-expense template
  src/app/shared/components/review-split-expense/review-split-expense.component.html
  src/app/shared/components/review-split-expense/review-split-expense.component.scss
  src/app/shared/components/review-split-expense/review-split-expense.component.spec.ts
  src/app/shared/components/review-split-expense/review-split-expense.component.ts
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/M

#3500 fix: MixPanel events cleanup to prevent PII data.
  src/app/core/services/tracking.service.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XS

#3506 fix: Add smartlook-hide class to hide elements showing PII info from smart…
  src/app/auth/switch-org/active-org-card/active-org-card.component.html
  src/app/auth/switch-org/org-card/org-card.component.html
  src/app/fyle/delegated-accounts/delegated-accounts.page.html
  src/app/fyle/help/support-dialog/support-dialog.page.html
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.html
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/shared/components/card-number/card-number.component.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.html
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.html
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.html
Labels: size/M

#3509 feat: Migrate /v2/corporate_card_transactions to platform
  src/app/core/mock-data/corporate-card-expense.data.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/fyle/merge-expense/card-transaction-preview/card-transaction-preview.component.html
  src/app/fyle/merge-expense/card-transaction-preview/card-transaction-preview.component.spec.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
  src/app/fyle/merge-expense/merge-expense-3.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/M

#3516 fix: font-size and line-height issue
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.scss
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.scss
  src/app/fyle/my-view-advance/my-view-advance.page.scss
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.scss
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.scss
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.scss
  src/app/shared/components/expense-card-lite/expense-card-lite.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/expenses-card/expenses-card.component.scss
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.scss
  src/app/shared/components/reports-card/reports-card.component.scss
Labels: size/S

#3517 fix: view expense page broken design
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.scss
Labels: size/XS

#3519 fix: Set user id also to sentry
  src/app/auth/switch-org/switch-org.page.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/XS

#3515 feat: add new review-split-expense-modal flow inside split expense page
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/M

#3520 fix: Add auto navigation back to the previous page if the expense does not…
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#3528 fix: remove admin condition to show nps on save expense
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3531 fix: validation increased to 11mb
  src/app/core/constants.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
Labels: size/S

#3532 fix: 0.00 decimal fix
  src/app/shared/pipes/fy-currency.pipe.ts
Labels: size/XS

#3525 feat: add popover modal to show for disabled field
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.scss
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.html
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.scss
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.spec.ts
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.ts
  src/app/shared/shared.module.ts
Labels: size/M

#3523 feat: add category-costcenter mapping in split expense
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.scss
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.html
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.scss
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.spec.ts
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.ts
  src/app/shared/components/fy-select/fy-select.component.ts
  src/app/shared/shared.module.ts
Labels: size/M

#3527 fix: QA fixes for virtual cards
  src/app/shared/components/fy-popover/fy-popover.component.html
  src/app/shared/components/virtual-card/virtual-card.component.html
  src/app/shared/components/virtual-card/virtual-card.component.scss
Labels: size/XS

#3539 fix: UI issues in angular migration
  src/app/shared/components/comments-history/audit-history/audit-history.component.scss
  src/global.scss
Labels: size/XS

#3526 fix: review expense flow filter out deleted expenses
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#3541 feat: Send cluster domain in refiner nps identify user
  src/app/core/models/identify-user-payload.model.ts
  src/app/core/services/refiner.service.spec.ts
  src/app/core/services/refiner.service.ts
Labels: size/XS

#3524 fix: remove additional API call in review expense flow, filter out deleted expenses in review flow
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
Labels: size/M

#3522 fix: Set default value as null when creating expense, mileage without spe…
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#3535 fix: mobile number option similar to current web-app in settings
  src/app/shared/components/mobile-number-card/mobile-number-card.component.html
Labels: size/XS

#3543 feat: bring back lint on github checks, eslint on commit
  .github/workflows/lint.yml
  README.md
  package.json
Labels: size/XS

#3521 chore: remove the outdated tips part in help page
  src/app/fyle/help/help.page.html
  src/app/fyle/help/help.page.scss
  src/app/fyle/help/help.page.spec.ts
  src/app/fyle/help/help.page.ts
  src/app/fyle/help/support-dialog/support-dialog.page.html
  src/app/fyle/help/support-dialog/support-dialog.page.scss
Labels: size/M

#3546 feat: Upgrade ng2-pdf-viewer
  .github/workflows/lint.yml
  .github/workflows/unit-tests.yml
  package-lock.json
  package.json
Labels: size/L

#3537 chore: move extendQueryParamsForTextSearch method to a helper service and remove from api-v2.service
  src/app/core/services/api-v2.service.spec.ts
  src/app/core/services/api-v2.service.ts
  src/app/core/services/extend-query-params.service.spec.ts
  src/app/core/services/extend-query-params.service.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
Labels: size/M

#3493 fix: font size for stats badge
  src/app/fyle/dashboard/stat-badge/stat-badge.component.html
  src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
  src/app/fyle/dashboard/stat-badge/stat-badge.component.ts
Labels: size/M

#3553 fix: Revert "feat: Upgrade ng2-pdf-viewer"
  package-lock.json
  package.json
Labels: size/L

#3538 feat: Adding Unapproved team reports stat on dashboard
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/dashboard/dashboard.service.ts
  src/app/fyle/dashboard/stat-badge/report-states.enum.ts
  src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
  src/app/fyle/dashboard/stat-badge/stat-badge.component.spec.ts
  src/app/fyle/dashboard/stat-badge/stat-badge.component.ts
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.spec.ts
  src/app/fyle/dashboard/stats/stats.component.ts
Labels: size/M

#3542 fix: Poilcy violation logic
  src/app/core/models/filtered-missing-fields-violations.model.ts
  src/app/core/models/filtered-split-policy-violations.model.ts
  src/app/core/models/policy-violation.model.ts
  src/app/core/models/splitting-expense-properties.model.ts
  src/app/core/models/transformed-split-expense-missing-fields.model.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.scss
Labels: size/M

#3555 fix: amount error msg and autocoded msg alignment
  src/app/fyle/add-edit-expense/add-edit-expense.page.scss
Labels: size/XS

#3557 fix: Split expense unit test 2
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
Labels: size/M

#3547 fix: edge case of cost center id to add inside txnFields
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/XS

#3552 feat: Fyle try angular 16
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/guards/auth.guard.spec.ts
  src/app/core/guards/auth.guard.ts
  src/app/core/guards/beta-page-feature-flag.guard.spec.ts
  src/app/core/guards/beta-page-feature-flag.guard.ts
  src/app/core/guards/onboarding.guard.ts
  src/app/core/guards/opt-in.guard.ts
  src/app/core/guards/verified-org-auth.guard.spec.ts
  src/app/core/guards/verified-org-auth.guard.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/main.ts
Labels: size/XL

#3550 feat: remove unwanted packages, move some from dependencies to dev dependenciesm, angular 16
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  e2e/tsconfig.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/guards/auth.guard.spec.ts
  src/app/core/guards/auth.guard.ts
  src/app/core/guards/beta-page-feature-flag.guard.spec.ts
  src/app/core/guards/beta-page-feature-flag.guard.ts
  src/app/core/guards/onboarding.guard.ts
  src/app/core/guards/opt-in.guard.ts
  src/app/core/guards/verified-org-auth.guard.spec.ts
  src/app/core/guards/verified-org-auth.guard.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/main.ts
Labels: size/XL

#3556 test: Add test for approver dialog
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.spec.ts
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.ts
Labels: size/M

#3549 feat: Add approver dialog in my view report
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.spec.ts
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.ts
Labels: size/L
