Repository fylein/fyle-mobile-app, pull requests merged in 2025-09, with the labels that each got.

#3912 fix: Fyle advances use filepicker input
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.setup.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.html
  src/app/shared/components/capture-receipt/capture-receipt.component.scss
Labels: size/L

#3910 fix: migrate check_verification_code to platform
  src/app/core/services/mobile-number-verification.service.spec.ts
  src/app/core/services/mobile-number-verification.service.ts
Labels: size/S

#3911 fix: migrate update org user api to platform
  src/app/core/services/org-user.service.spec.ts
  src/app/core/services/org-user.service.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/S

#3918 fix: remove unwanted input to location modal component
  src/app/shared/components/fy-location/fy-location.component.spec.ts
  src/app/shared/components/fy-location/fy-location.component.ts
Labels: size/XS

#3914 feat: clean up txn objects
  src/app/core/mock-data/ccc-api-response.data.ts
  src/app/core/mock-data/expense-filters.data.ts
  src/app/core/mock-data/expense-v2.data.ts
  src/app/core/mock-data/file-txn.data.ts
  src/app/core/mock-data/public-policy-expense.data.ts
  src/app/core/mock-data/split-expense-form.data.ts
  src/app/core/mock-data/split-expense.data.ts
  src/app/core/mock-data/transaction.data.ts
  src/app/core/mock-data/transformed-expense.data.ts
  src/app/core/mock-data/unflattened-expense.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/public-policy-expense.model.ts
  src/app/core/models/split-expense.model.ts
  src/app/core/models/unformatted-transaction.model.ts
  src/app/core/models/v1/transaction.model.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/policy.service.spec.ts
  src/app/core/services/policy.service.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.spec.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/XL

#3938 fix: conditions for opt-out status
  src/app/core/mock-data/advance-platform.data.ts
  src/app/core/mock-data/extended-advance.data.ts
  src/app/core/mock-data/platform/v1/advance-request-platform.data.ts
  src/app/core/models/platform/platform-employee.model.ts
  src/app/shared/components/fy-alert-info/fy-alert-info.component.html
  src/app/shared/components/fy-alert-info/fy-alert-info.component.ts
  src/app/shared/components/profile-opt-in-card/profile-opt-in-card.component.html
  src/assets/i18n/en.json
Labels: size/S

#3937 Fyle module upgrades for OTP input and NgxMaskDirective, fix errors
  karma.conf.js
  package-lock.json
  package.json
  src/app/core/services/mobile-number-verification.service.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.spec.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
  src/main.ts
Labels: size/M

#3936 Fix remaining unit tests after standalone migration
  karma.conf.js
  package-lock.json
  package.json
  src/app/app.component.spec.ts
  src/app/auth/pending-verification/pending-verification.page.spec.ts
  src/app/auth/reset-password/reset-password.page.spec.ts
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/core/services/mobile-number-verification.service.ts
  src/app/fyle/add-edit-advance-request/camera-options-popup/camera-options-popup.component.spec.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.spec.ts
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.ts
  src/app/fyle/my-advances/my-advances.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/team-advance/team-advance.page.spec.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports-2.page.spec.ts
  src/app/fyle/team-reports/team-reports-3.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/capture-receipt/crop-receipt/crop-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/crop-receipt/crop-receipt.component.ts
  src/app/shared/components/footer/footer.component.spec.ts
  src/app/shared/components/fy-opt-in/fy-opt-in.component.ts
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/virtual-card/virtual-card.component.spec.ts
  src/main.ts
Labels: size/L

#3961 fix: modify appflow build script to remove sourcemaps
  build_appflow.sh
Labels: size/XS

#3966 fix: audit trail timestamp font size
  src/app/shared/components/comments-history/audit-history/audit-history.component.scss
Labels: size/XS
