Repository fylein/fyle-mobile-app, pull requests merged in 2025-05, with the labels that each got.

#3671 chore: Remove expense aggregation service, references and spec file
  src/app/core/services/expense-aggregation.service.spec.ts
  src/app/core/services/expense-aggregation.service.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/router-auth.service.ts
Labels: size/M

#3672 feat: Migrated recently used api to platform
  src/app/core/mock-data/platform/v1/platform-project-args.data.ts
  src/app/core/mock-data/recently-used.data.ts
  src/app/core/models/v1/recently_used.model.ts
  src/app/core/services/recently-used-items.service.spec.ts
  src/app/core/services/recently-used-items.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.html
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts
  src/app/shared/components/route-selector/route-selector.component.spec.ts
  src/app/shared/components/route-selector/route-selector.component.ts
Labels: size/L

#3675 feat: add shared action for jscpd
  .github/workflows/jscpd-duplication-check.yml
Labels: size/S

#3676 feat: added shared eol action
  .github/workflows/eol-outdated-js-scan.yml
Labels: size/M

#3677 fix: Replace SPENDER role by FYLER in refiner service
  src/app/core/services/refiner.service.ts
Labels: size/XS

#3674 feat: Migrated the transaction delete api to platform
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/M

#3680 fix: JSCPD issue fix on coderabbit comment
  .github/workflows/jscpd-duplication-check.yml
Labels: size/XS

#3681 test: fix the tests for expense comment service post method
  src/app/core/services/platform/v1/approver/expense-comment.service.spec.ts
  src/app/core/services/platform/v1/spender/expense-comment.service.spec.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.spec.ts
Labels: size/L

#3679 feat: Migrated the post expense comment API
  src/app/core/services/platform/v1/approver/expense-comment.service.spec.ts
  src/app/core/services/platform/v1/approver/expense-comment.service.ts
  src/app/core/services/platform/v1/spender/expense-comment.service.spec.ts
  src/app/core/services/platform/v1/spender/expense-comment.service.ts
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/shared/components/comments-history/comments-history.component.html
  src/app/shared/components/comments-history/comments-history.component.scss
  src/app/shared/components/comments-history/comments-history.component.spec.ts
  src/app/shared/components/comments-history/comments-history.component.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.spec.ts
  src/app/shared/shared.module.ts
Labels: size/L

#3682 feat: track the time taken for scanning receipts in prod
  src/app/core/services/tracking.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XS

#3683 fix: show secondary apporver info msg inside team view
  src/app/fyle/view-team-report/view-team-report.module.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/M

#3685 fix: swallow error for location permission request denial
  src/app/core/services/location.service.ts
Labels: size/XS

#3686 fix: minor content change for approver info msg
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/S

#3684 fix: View all reports for all approvers
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/M

#3688 fix: hide the info msg when report is already approved
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/S

#3689 feat: receipt scan time tracker instafyle
  src/app/core/services/tracking.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/S

#3691 fix: correct total amount to show inside view-report
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
Labels: size/XS
