Repository fylein/fyle-mobile-app, pull requests merged in 2025-08, with the labels that each got.

#3839 update navigation colors
  resources/splash.png
  src/app/fyle/add-edit-advance-request/fy-currency/fy-currency.component.scss
  src/app/fyle/add-edit-expense/add-edit-expense.page.scss
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.scss
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.scss
  src/app/fyle/merge-expense/category-dependent-fields-form/category-dependent-fields-form.component.scss
  src/app/fyle/merge-expense/custom-inputs-fields-form/custom-inputs-fields-form.component.scss
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.scss
  src/app/fyle/merge-expense/merge-expense.page.scss
  src/app/fyle/my-create-report/my-create-report.page.scss
  src/app/fyle/split-expense/split-expense.page.scss
  src/app/shared/components/create-new-report-v2/create-new-report.component.scss
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.scss
  src/app/shared/components/fy-currency/fy-currency.component.scss
  src/app/shared/components/fy-location/fy-location.component.scss
  src/app/shared/components/fy-multiselect/fy-multiselect.component.scss
  src/app/shared/components/fy-select-disabled/fy-select-disabled.component.scss
  src/app/shared/components/fy-select-project/fy-select-project.component.scss
  src/app/shared/components/fy-select-vendor/fy-select-vendor.component.scss
  src/app/shared/components/fy-select/fy-select.component.scss
  src/app/shared/components/fy-userlist/fy-userlist.component.scss
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.scss
  src/app/shared/components/route-selector/route-selector.component.scss
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.scss
  src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.scss
  src/app/shared/components/sidemenu/sidemenu.component.scss
  src/app/shared/components/virtual-select/virtual-select.component.scss
  src/assets/svg/active-org-currency.svg
  src/assets/svg/fyle-logo-dark.svg
  src/assets/svg/fyle-logo-light.svg
  src/assets/svg/info-circle-gradient.svg
  src/assets/svg/list-plus.svg
  src/theme/colors.scss
Labels: size/M

#3823 feat: User workflow improvement for review expense and add expense to report
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/M

#3843 feat: Added the pending gas charge info on view/edit expense and expense list view pages
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/shared/expenses.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/pending-gas-charge-info-modal/pending-gas-charge-info-modal.component.html
  src/app/shared/components/pending-gas-charge-info/pending-gas-charge-info.component.html
  src/app/shared/components/pending-gas-charge-info/pending-gas-charge-info.component.scss
  src/app/shared/components/pending-gas-charge-info/pending-gas-charge-info.component.spec.ts
  src/app/shared/components/pending-gas-charge-info/pending-gas-charge-info.component.ts
  src/app/shared/icon/icon.module.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/en.json
  src/assets/svg/question-square-fill.svg
Labels: size/XL

#3833 feat: Splash screen addition and dashboard loader removed
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/core/guards/onboarding.guard.ts
  src/app/core/guards/verified-org-auth.guard.spec.ts
  src/app/core/guards/verified-org-auth.guard.ts
  src/app/fyle/dashboard/dashboard.service.ts
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.spec.ts
  src/app/fyle/dashboard/stats/stats.component.ts
  src/assets/images/splash.png
Labels: size/L

#3855 fix: Added fix for custom field not showing under certain circumstances
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3857 feat: Sage rebrand empty states
  src/app/auth/app-version/app-version.page.html
  src/app/auth/switch-org/switch-org.page.html
  src/app/fyle/dashboard/tasks/tasks.component.html
  src/app/fyle/my-advances/my-advances.page.html
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/personal-cards/personal-cards.page.scss
  src/app/fyle/team-advance/team-advance.page.html
  src/app/fyle/team-reports/team-reports.page.html
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/post-verification/invited-user/invited-user.page.html
  src/app/shared/components/comments-history/view-comment/view-comment.component.html
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.html
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.html
  src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.html
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.html
  src/assets/images/contact-support/fy-extension.gif
  src/assets/images/contact-support/ibibo-demo.gif
  src/assets/images/contact-support/mileage-settings.png
  src/assets/images/zero-states/advances.png
  src/assets/images/zero-states/cards.png
  src/assets/images/zero-states/invoice.png
  src/assets/images/zero-states/new-comments.png
  src/assets/images/zero-states/new-expenses.png
  src/assets/images/zero-states/notifications.png
  src/assets/images/zero-states/offline.svg
  src/assets/images/zero-states/reports.png
  src/assets/images/zero-states/search.png
  src/assets/images/zero-states/tasks.png
  src/assets/svg/offline.svg
  src/assets/svg/zero-states/advances.svg
  src/assets/svg/zero-states/cards.svg
  src/assets/svg/zero-states/chat.svg
  src/assets/svg/zero-states/expenses.svg
  src/assets/svg/zero-states/notifications.svg
  src/assets/svg/zero-states/reports.svg
  src/assets/svg/zero-states/search.svg
  src/assets/svg/zero-states/tasks.svg
  src/global.scss
Labels: size/L

#3860 fix: Approver stat loading state visibility fix
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.ts
Labels: size/XS

#3863 fix: minor fix for pending-gas-charge tag
  src/app/shared/components/pending-gas-charge-info/pending-gas-charge-info.component.scss
Labels: size/XS

#3861 Fyle sage fixes 2
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.scss
  src/app/fyle/my-profile/my-profile.page.scss
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.scss
  src/app/shared/components/corporate-card/corporate-card.component.scss
  src/app/shared/components/dashboard-email-opt-in/dashboard-email-opt-in.component.scss
  src/app/shared/components/dashboard-opt-in/dashboard-opt-in.component.scss
  src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.scss
  src/assets/images/card.png
  src/assets/styles/_fy_driver_tour.scss
  src/assets/svg/stars-filled.svg
  src/global.scss
  src/theme/colors.scss
Labels: size/M

#3862 feat: Walkthrough for status pill and minor fix
  src/app/core/services/walkthrough.service.spec.ts
  src/app/core/services/walkthrough.service.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/expenses-card/expenses-card.component.html
  src/app/shared/components/expenses-card/expenses-card.component.scss
  src/assets/i18n/en.json
Labels: size/L

#3864 fix: Walkthrough destruction handled for button click during walkthrough
  src/app/fyle/dashboard/dashboard.page.ts
Labels: size/XS

#3866 feat: Checkbox styles in fyle sage
  src/global.scss
  src/theme/colors.scss
Labels: size/S

#3865 fix: minor style fixes for sage rebranding
  src/app/fyle/add-edit-expense/add-edit-expense.page.scss
  src/app/fyle/my-profile/employee-details-card/employee-details-card.component.scss
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
  src/app/fyle/split-expense/split-expense.page.scss
  src/app/fyle/view-expense/view-expense.page.scss
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/shared/components/comments-history/view-comment/view-comment.component.scss
  src/app/shared/components/fy-input-popover/fy-input-popover.component.html
  src/app/shared/components/fy-input-popover/fy-input-popover.component.scss
  src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.scss
  src/global.scss
  src/theme/colors.scss
Labels: size/M

#3869 feat: sage checkbox styling
  src/global.scss
Labels: size/XS

#3871 fix: fix border radius for my reports empty cta
  karma.conf.js
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/my-reports/my-reports.page.scss
Labels: size/XS

#3874 fix: fyle test error
  karma.conf.js
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
Labels: size/XS

#3814 feat: add id in custom_fields with api payload
  src/app/core/mock-data/custom-inputs-field.data.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/merge-expense/custom-inputs-fields-form/custom-inputs-fields-form.component.spec.ts
  src/app/fyle/merge-expense/custom-inputs-fields-form/custom-inputs-fields-form.component.ts
Labels: size/XS

#3879 fix: fix the background color token name
  src/app/shared/components/pending-gas-charge-info-modal/pending-gas-charge-info-modal.component.scss
  src/theme/colors.scss
Labels: size/XS

#3880 fix: fix distance calculation in mileage form
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts
Labels: size/S

#3881 fix: remove timeout in my expenses polling
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XS

#3886 fix: minor fix to remove unwanted keys added by cursor
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  tsconfig.json
  tsconfig.spec.json
Labels: size/XS

#3887 fix: round of the distance in commute details
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.spec.ts
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.ts
Labels: size/XS

#3888 fix: Personal card/cash showing when not allowed
  src/app/core/services/accounts.service.spec.ts
  src/app/core/services/accounts.service.ts
Labels: size/XS

#3890 fix: layout issue in the expense form
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.scss
Labels: size/M

#3892 fix: set muted to true
  src/app/auth/sign-in/sign-in.page.html
Labels: size/XS

#3891 fix: change from Add to report to add to expense report
  src/app/core/mock-data/dashboard-task.data.ts
  src/app/core/mock-data/task.data.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.spec.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.spec.ts
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.spec.ts
  src/assets/i18n/en.json
Labels: size/L

#3895 fix: cache issue on delete report and fix report title empty issue
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-create-report/my-create-report.page.ts
Labels: size/S

#3893 fix: fix more minor issues in mobile app
  src/app/core/mock-data/sidemenu.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/my-create-report/my-create-report.page.scss
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.scss
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/my-view-report/share-report/share-report.component.html
  src/app/fyle/my-view-report/share-report/share-report.component.scss
  src/app/fyle/my-view-report/share-report/share-report.component.spec.ts
  src/app/fyle/my-view-report/share-report/share-report.component.ts
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/shared/components/create-new-report-v2/create-new-report.component.scss
  src/app/shared/components/fy-delete-dialog/fy-delete-dialog.component.html
  src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.scss
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/assets/i18n/en.json
  src/assets/svg/fy-switch.svg
Labels: size/M

#3897 feat: open stats instead of draft stats
  src/app/core/mock-data/report-stats.data.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/dashboard/dashboard.service.ts
  src/app/fyle/dashboard/stat-badge/report-states.enum.ts
  src/app/fyle/dashboard/stat-badge/stat-badge.component.scss
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.spec.ts
  src/app/fyle/dashboard/stats/stats.component.ts
  src/assets/i18n/en.json
Labels: size/M

#3898 fix: Fyle eslint fixes
  eslint.config.mjs
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/models/platform-account.model.ts
  src/app/core/models/public-policy-expense.model.ts
  src/app/core/models/transaction-status.model.ts
  src/app/core/services/accounts.service.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/auth.service.ts
  src/app/core/services/clipboard.service.ts
  src/app/core/services/custom-fields.service.ts
  src/app/core/services/date.service.ts
  src/app/core/services/filters-helper.service.spec.ts
  src/app/core/services/fresh-chat.service.ts
  src/app/core/services/jwt-helper.service.spec.ts
  src/app/core/services/jwt-helper.service.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/refiner.service.ts
  src/app/core/services/transaction.service.ts
  src/app/core/services/transactions-outbox.service.ts
  src/app/core/services/utility.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/fyle/add-edit-advance-request/camera-options-popup/camera-options-popup.component.spec.ts
  src/app/fyle/add-edit-advance-request/fy-currency/fy-currency-choose-currency/fy-currency-choose-currency.component.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.spec.ts
  src/app/fyle/dashboard/stats/stats.component.ts
  src/app/fyle/delegated-accounts/delegated-accounts.page.spec.ts
  src/app/fyle/fyle-routing.module.ts
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.ts
  src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
  src/app/shared/components/capture-receipt/crop-receipt/crop-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/fy-approver/fy-approver.component.spec.ts
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
  src/app/shared/components/virtual-select/virtual-select.component.ts
  src/app/shared/pipes/date-with-timezone.pipe.ts
Labels: size/M

#3905 fix: Files fixes
  src/app/app.module.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.setup.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
Labels: size/M
