Repository fylein/fyle-mobile-app, pull requests merged in 2025-06, with the labels that each got.

#3697 fix: Fix invite flow to set password when user is marked active but password not set
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
Labels: size/M

#3703 fix: revert view report approver info msg implementation
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/L

#3704 fix: QA fix for save reorientation receipt
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.html
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.scss
Labels: size/S

#3690 feat: rotate and save receipt on edit expense.
  src/app/core/enums/rotation-direction.enum.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.html
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.scss
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.ts
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.html
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.scss
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.ts
  src/assets/svg/bin-dark.svg
Labels: size/L

#3705 fix: show info msg inside view-team-reports-page
  src/app/fyle/view-team-report/view-team-report.module.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-expansion-info-msg/fy-expansion-info-msg.component.html
  src/app/shared/components/fy-expansion-info-msg/fy-expansion-info-msg.component.scss
  src/app/shared/components/fy-expansion-info-msg/fy-expansion-info-msg.component.spec.ts
  src/app/shared/components/fy-expansion-info-msg/fy-expansion-info-msg.component.ts
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/L

#3712 feat: add service tracker for rotation and save
  src/app/core/services/tracking.service.ts
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.ts
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.spec.ts
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.ts
Labels: size/S

#3693 feat: Migrated the merge expenses API
  src/app/core/mock-data/generated-form-properties.data.ts
  src/app/core/mock-data/merge-expense-form-data.data.ts
  src/app/core/mock-data/merge-expenses-payload.data.ts
  src/app/core/models/generated-form-properties.model.ts
  src/app/core/models/merge-expenses-payload.model.ts
  src/app/core/services/merge-expenses.service.spec.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/services/platform/v1/spender/expenses.service.spec.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/merge-expense/merge-expense-2.page.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.setup.spec.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/L

#3713 feat: add Gitleaks secrets scan workflow
  .github/workflows/secrets-scan.yaml
Labels: size/S

#3701 feat: Fyle account migration mileage perdiem expenses fix
  src/app/core/mock-data/account-option.data.ts
  src/app/core/mock-data/data-transform.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/services/accounts.service.spec.ts
  src/app/core/services/payment-modes.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
Labels: size/XL

#3717 fix: fixed the duplicate custom fields in merge payload
  src/app/core/mock-data/generated-form-properties.data.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/XS

#3718 feat: i18n setup and script changes for mobile app
  .gitignore
  src/scripts/i18n/i18n_extraction.py
  src/scripts/i18n/inline_and_diff.py
  src/scripts/i18n/list_source_files.py
  src/scripts/i18n/write_updated_files.py
Labels: size/L

#3721 feat: create notificationsBetaPage skeleton
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.html
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.scss
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.spec.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.ts
  src/app/fyle/notifications/notifications-routing.module.ts
  src/app/fyle/notifications/notifications.module.ts
Labels: size/M

#3716 fix: currency specific rounding off inside split expense
  src/app/core/mock-data/fallback-currency-data.ts
  src/app/core/models/currency-config.model.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/M

#3722 chore: remove security scan workflow
  .github/workflows/security-scan.yml
Labels: size/S

#3731 feat: implement notifications beta page with email preferences and de…
  src/app/core/mock-data/notification-events.data.ts
  src/app/core/models/notification-config.model.ts
  src/app/core/models/notification-event-item.model.ts
  src/app/core/models/notification-events.enum.ts
  src/app/core/services/platform/v1/approver/employee-settings.service.ts
  src/app/fyle/notifications/email-notifications/email-notifications.component.html
  src/app/fyle/notifications/email-notifications/email-notifications.component.scss
  src/app/fyle/notifications/email-notifications/email-notifications.component.spec.ts
  src/app/fyle/notifications/email-notifications/email-notifications.component.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.html
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.scss
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.service.spec.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.service.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.spec.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.ts
  src/app/fyle/notifications/notifications.module.ts
  src/global.scss
Labels: size/XL

#3734 fix: rounding off split expense amount for foreign currency
  src/app/core/services/split-expense.service.spec.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/M

#3730 chore: remove eol action
  .github/workflows/eol-outdated-js-scan.yml
Labels: size/S

#3695 feat: Accounts API migration
  src/app/core/enums/account-type.enum.ts
  src/app/core/mock-data/account-option.data.ts
  src/app/core/mock-data/data-transform.data.ts
  src/app/core/mock-data/per-diem-form-value.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/account-detail.model.ts
  src/app/core/models/allowed-payment-modes.enum.ts
  src/app/core/models/extended-account.model.ts
  src/app/core/models/flattened-account.model.ts
  src/app/core/models/platform-account.model.ts
  src/app/core/services/accounts.service.spec.ts
  src/app/core/services/accounts.service.ts
  src/app/core/services/payment-modes.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/shared/components/expenses-card/expenses-card.component.spec.ts
Labels: size/XL

#3733 chore: add CODEOWNERS entry for package-lock.json or requirements.txt
  .github/CODEOWNERS
Labels: size/XS

#3736 fix: fixed the personal cards
  src/app/core/mock-data/employee-settings.data.ts
  src/app/core/models/employee-settings.model.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/XS

#3738 fix: minor validation change
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#3743 fix: transformed the user payment mode of personal account to personal_cash_account
  src/app/core/enums/account-type.enum.ts
  src/app/core/mock-data/employee-settings.data.ts
  src/app/core/models/employee-settings.model.ts
  src/app/core/services/per-diem.service.ts
  src/app/core/services/platform/v1/approver/employee-settings.service.spec.ts
  src/app/core/services/platform/v1/approver/employee-settings.service.ts
  src/app/core/services/platform/v1/spender/employee-settings.service.spec.ts
  src/app/core/services/platform/v1/spender/employee-settings.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.ts
Labels: size/L

#3740 feat: migrated advance request approvals api to platform
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
Labels: size/M

#3744 fix: Reimbursable bug fix for payment modes
  src/app/fyle/add-edit-advance-request/camera-options-popup/camera-options-popup.component.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/L
