Repository fylein/fyle-mobile-app, pull requests merged in 2025-01, with the labels that each got.

#3392 fix: Revert "fix: Task for add Corporate Card" and QA fixes
  android/.idea/runConfigurations.xml
  android/app/src/main/ic_launcher_new_splash-playstore.png
  android/app/src/main/res/drawable/ic_launcher_new_splash_background.xml
  android/app/src/main/res/drawable/ic_launcher_new_splash_foreground.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_new_splash.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_new_splash_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_new_splash_round.webp
  src/app/app.component.ts
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/sign-in/sign-in.page.scss
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/app/core/mock-data/task-cta.data.ts
  src/app/core/models/task-event.enum.ts
  src/app/core/models/task-icon.enum.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks-1.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/assets/images/video-default-background.png
Labels: size/L

#3394 fix: Fyle fix issues around tasks and qa changes
  android/.idea/runConfigurations.xml
  android/app/src/main/ic_launcher_new_splash-playstore.png
  android/app/src/main/res/drawable/ic_launcher_new_splash_background.xml
  android/app/src/main/res/drawable/ic_launcher_new_splash_foreground.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_new_splash.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_new_splash_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_new_splash_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_new_splash.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_new_splash_round.webp
  src/app/app.component.ts
  src/app/auth/sign-in/sign-in-page-state.enum.ts
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/sign-in/sign-in.page.scss
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/app/core/mock-data/task-cta.data.ts
  src/app/core/models/task-event.enum.ts
  src/app/core/models/task-icon.enum.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/dashboard/tasks/tasks-1.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.scss
  src/app/fyle/dashboard/tasks/tasks.component.setup.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
  src/assets/images/video-default-background.png
Labels: size/L

#3402 fix: delete public PersonalCardTxn model and corresponding ldFlag
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/personal_card_txn.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
Labels: size/L

#3401 fix: remove use of old PersonalCardTxn model
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/personal_card_txn.model.ts
  src/app/core/models/platform/platform-personal-card-txn.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.html
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.spec.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.ts
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.html
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.spec.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.ts
Labels: size/XL

#3400 fix: transform personal card public queryParams to platform
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/personal_card_txn.model.ts
  src/app/core/models/platform/platform-personal-card-filter-params.model.ts
  src/app/core/models/platform/platform-personal-card-query-params.model.ts
  src/app/core/models/platform/platform-personal-card-txn.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.html
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.spec.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.ts
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.html
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.spec.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.ts
Labels: size/XL

#3399 fix: remove model PersonalCardTxnExpenseSuggestion
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-card-txn-expense-suggestions.data.ts
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/personal-card-txn-expense-suggestion.model.ts
  src/app/core/models/personal_card_txn.model.ts
  src/app/core/models/platform/platform-personal-card-filter-params.model.ts
  src/app/core/models/platform/platform-personal-card-query-params.model.ts
  src/app/core/models/platform/platform-personal-card-txn.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.html
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.spec.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.ts
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.html
  src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.html
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.spec.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.ts
Labels: size/XL

#3398 fix: delete personal_card.model.ts and places where it was used
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-card-txn-expense-suggestions.data.ts
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/mock-data/personal-cards.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/personal-card-txn-expense-suggestion.model.ts
  src/app/core/models/personal_card.model.ts
  src/app/core/models/personal_card_txn.model.ts
  src/app/core/models/platform/platform-personal-card-filter-params.model.ts
  src/app/core/models/platform/platform-personal-card-query-params.model.ts
  src/app/core/models/platform/platform-personal-card-txn.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.html
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.spec.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.ts
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.spec.ts
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.html
  src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.html
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.spec.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.ts
Labels: size/XL

#3397 fix: Remove old personal card model - 1
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-card-txn-expense-suggestions.data.ts
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/mock-data/personal-cards.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/personal-card-txn-expense-suggestion.model.ts
  src/app/core/models/personal_card.model.ts
  src/app/core/models/personal_card_txn.model.ts
  src/app/core/models/platform/platform-personal-card-filter-params.model.ts
  src/app/core/models/platform/platform-personal-card-query-params.model.ts
  src/app/core/models/platform/platform-personal-card-txn.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.html
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.spec.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.ts
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.html
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.spec.ts
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.spec.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.html
  src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.html
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.spec.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.ts
Labels: size/XL

#3403 fix: Remove old personal card model - 1 (#3397)
  src/app/core/mock-data/get-tasks-query-params-with-filters.data.ts
  src/app/core/mock-data/personal-card-txn-expense-suggestions.data.ts
  src/app/core/mock-data/personal-card-txns.data.ts
  src/app/core/mock-data/personal-cards.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/personal-card-txn-expense-suggestion.model.ts
  src/app/core/models/personal_card.model.ts
  src/app/core/models/personal_card_txn.model.ts
  src/app/core/models/platform/platform-personal-card-filter-params.model.ts
  src/app/core/models/platform/platform-personal-card-query-params.model.ts
  src/app/core/models/platform/platform-personal-card-txn.model.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.spec.ts
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.html
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.spec.ts
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.ts
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/personal-cards/personal-cards.page.spec.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.html
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.spec.ts
  src/app/shared/components/bank-account-cards/bank-account-card/bank-account-card.component.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.spec.ts
  src/app/shared/components/bank-account-cards/bank-account-cards.component.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.html
  src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
  src/app/shared/components/expense-card-lite/expense-card-lite.component.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.html
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.spec.ts
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.ts
Labels: size/XL

#3395 fix: Display exact amount DQA fixes
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.scss
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.html
  src/app/fyle/my-advances/my-advances-card/my-advances-card.component.scss
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-create-report/my-create-report.page.scss
  src/app/fyle/my-create-report/my-create-report.page.spec.ts
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.scss
  src/app/fyle/my-view-advance/my-view-advance.page.scss
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.scss
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/personal-cards-matched-expenses/personal-cards-matched-expenses.page.scss
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.html
  src/app/fyle/team-advance/team-adv-card/team-adv-card.component.scss
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.scss
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/shared/components/create-new-report-v2/create-new-report.component.html
  src/app/shared/components/create-new-report-v2/create-new-report.component.scss
  src/app/shared/components/expense-card-lite/expense-card-lite.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/expenses-card/expenses-card.component.scss
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.html
  src/app/shared/components/personal-card-transaction/personal-card-transaction.component.scss
  src/app/shared/components/reports-card/reports-card.component.html
  src/app/shared/components/reports-card/reports-card.component.scss
  src/app/shared/icon/icon.module.ts
  src/assets/svg/info-circle-gradient.svg
  src/assets/svg/list-new.svg
  src/global.scss
Labels: size/M

#3396 fix: Minor Design QA fix to add modal transition
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/shared/components/cc-expense-merchant-info-modal/cc-expense-merchant-info-modal.component.html
  src/app/shared/components/cc-expense-merchant-info-modal/cc-expense-merchant-info-modal.component.scss
  src/app/shared/components/cc-expense-merchant-info-modal/cc-expense-merchant-info-modal.component.spec.ts
  src/app/shared/components/cc-expense-merchant-info-modal/cc-expense-merchant-info-modal.component.ts
  src/app/shared/components/cc-expense-merchant-info-popover/cc-expense-merchant-info-popover.component.ts
  src/app/shared/shared.module.ts
  src/global.scss
Labels: size/M

#3389 feat: Implementation for connect cards part 2
  src/app/core/models/popover-cards-list.model.ts
  src/app/fyle/spender-onboarding/models/onboarding-step.enum.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/shared/components/popup-alert/popup-alert.component.html
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/app/shared/components/popup-alert/popup-alert.component.ts
  src/assets/svg/check.svg
Labels: size/L

#3390 feat: Add UI and controller for Opt in step
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.module.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
Labels: size/XL

#3391 feat: Connect Card validation fixes
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.module.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
Labels: size/XL

#3393 feat: Update redirections to Spender Onboarding page from other pages
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/switch-org/switch-org.page.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/assets/images/onboarding-completion.gif
Labels: size/L

#3404 fix: Fix issues with sign in page redirection and video view
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/app/auth/verify/verify.page.spec.ts
  src/app/auth/verify/verify.page.ts
  src/app/fyle/dashboard/tasks/tasks-2.component.spec.ts
  src/app/fyle/dashboard/tasks/tasks.component.ts
Labels: size/M

#3408 fix: fix forgot password page email status and email placeholder content
  src/app/auth/reset-password/reset-password.page.ts
  src/app/auth/sign-in/sign-in.page.html
Labels: size/XS

#3409 fix: Add condition to hide validation error for unmatching passwords when required condition is present
  src/app/auth/new-password/new-password.page.html
Labels: size/XS

#3363 fix:draft report zero state improvements
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/assets/images/zero-states/invoice.png
Labels: size/M

#3406 test: test for opt in and connect card
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
Labels: size/L

#3412 test: Fix tests related to newer imports
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/post-verification/invited-user/invited-user.page.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/L

#3411 test: Add more coverage for connect card validators
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/post-verification/invited-user/invited-user.page.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/L

#3410 test: Add tests for Connnect Card - 1
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/post-verification/invited-user/invited-user.page.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/L

#3416 fix: reduce icon size in both side
  src/app/shared/components/footer/footer.component.scss
Labels: size/XS

#3419 chore: Cleanup & Fixes from Display Exact Amount
  src/app/fyle/my-advances/my-advances.page.html
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/team-advance/team-advance.page.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/fy-loading-screen/fy-loading-screen.component.html
  src/app/shared/components/fy-loading-screen/fy-loading-screen.component.scss
  src/app/shared/components/fy-loading-screen/fy-loading-screen.component.spec.ts
  src/app/shared/components/fy-loading-screen/fy-loading-screen.component.ts
Labels: size/M

#3421 fix: redact S3 URLs in tests
  src/app/core/mock-data/file-object.data.ts
  src/app/core/services/file.service.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.spec.ts
Labels: size/XS

#3414 fix: Fix vuln issues using npm audit fix
  package-lock.json
Labels: size/XL

#3420 fix: Sentry issue loader issue for submit report page
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/M

#3422 fix: Track error for edit and check policy
  src/app/core/services/tracking.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/S

#3425 fix: Add remaining QA fixes
  src/app/app-routing.module.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/shared/components/popup-alert/popup-alert.component.scss
Labels: size/M

#3423 fix: QA fixes for spender onboarding part one
  src/app/app-routing.module.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/assets/images/onboarding-completion.gif
  src/assets/images/onboarding-success.gif
Labels: size/M

#3424 fix: add coverage for countdown and other tests for connect cards
  src/app/core/mock-data/modal-controller.data.ts
  src/app/fyle/spender-onboarding/models/card-properties.model.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
Labels: size/L

#3417 test: fix failing tests across the app
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/auth/sign-in/sign-in.page.scss
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/services/spender-onboarding.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/spender-onboarding/models/card-properties.model.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/post-verification/invited-user/invited-user.page.spec.ts
  src/app/post-verification/invited-user/invited-user.page.ts
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/assets/images/onboarding-completion.gif
  src/assets/images/onboarding-success.gif
Labels: size/XL

#3428 feat: Trackers for onboarding flow
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
Labels: size/M

#3426 fix: Add more trackers to mileage flow
  src/app/core/services/tracking.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/XS

#3429 chore: clean up workflows
  .github/workflows/lint.yml
  .github/workflows/main.yml
  .github/workflows/stats.yml
  .github/workflows/unit-tests.yml
Labels: size/S

#3431 fix: skip filling unspecified category in the expense form during edit
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.spec.ts
Labels: size/XS

#3433 fix: Preference header hide fix
  src/app/fyle/my-profile/my-profile.page.html
Labels: size/S

#3434 fix: sentry fix
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
Labels: size/XS

#3430 fix: Restrict redirection to spender onboarding for an org which is not allowed to access it
  src/app/auth/switch-org/switch-org.page.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/post-verification/invited-user/invited-user.page.ts
Labels: size/XS

#3435 fix: Add back error handling for Google Sign in
  src/app/auth/sign-in/sign-in.page.ts
Labels: size/XS

#3436 fix: API repeated call for report partially approve, fix search errors in my expenses page
  src/app/core/services/api-v2.service.spec.ts
  src/app/core/services/api-v2.service.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/fyle/personal-cards/personal-cards.page.ts
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/M

#3438 fix: Uses guard instead of redirection to reach onboarding page when opening the mobile app
  src/app/app-routing.module.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/guards/onboarding.guard.ts
  src/app/core/services/spender-onboarding.service.ts
  src/app/fyle/fyle-routing.module.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/post-verification/invited-user/invited-user.page.ts
Labels: size/M

#3440 fix: Fix verify email flow bug for duplicate access token calls
  src/app/auth/verify/verify.page.spec.ts
  src/app/auth/verify/verify.page.ts
Labels: size/XS

#3439 fix: Add web app equivalent flow for partially enrolled cards
  src/app/app-routing.module.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/shared/components/popup-alert/popup-alert.component.html
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/M

#3441 test: add remaining fixes tests for newer logic in spender onboarding
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/sign-in/sign-in.page.scss
  src/app/auth/sign-in/sign-in.page.ts
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/core/guards/onboarding.guard.spec.ts
  src/app/core/guards/onboarding.guard.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/services/spender-onboarding.service.spec.ts
  src/app/core/services/spender-onboarding.service.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/post-verification/invited-user/invited-user.page.spec.ts
  src/app/post-verification/invited-user/invited-user.page.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
Labels: size/L

#3444 feat: Spender onboarding changes [full feature branch - already approved changes]
  src/app/app.component.ts
  src/app/auth/sign-in/sign-in.page.html
  src/app/auth/sign-in/sign-in.page.scss
  src/app/auth/sign-in/sign-in.page.ts
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/guards/onboarding.guard.spec.ts
  src/app/core/guards/onboarding.guard.ts
  src/app/core/mock-data/modal-controller.data.ts
  src/app/core/mock-data/onboarding-status.data.ts
  src/app/core/models/onboarding-state.enum.ts
  src/app/core/models/onboarding-status.model.ts
  src/app/core/models/onboarding-step-status.model.ts
  src/app/core/models/onboarding-welcome-step-status.model.ts
  src/app/core/models/popover-cards-list.model.ts
  src/app/core/services/spender-onboarding.service.spec.ts
  src/app/core/services/spender-onboarding.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/fyle-routing.module.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/spender-onboarding/models/card-properties.model.ts
  src/app/fyle/spender-onboarding/models/onboarding-step.enum.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding-routing.module.ts
  src/app/fyle/spender-onboarding/spender-onboarding.module.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/post-verification/invited-user/invited-user.page.spec.ts
  src/app/post-verification/invited-user/invited-user.page.ts
  src/app/shared/components/popup-alert/popup-alert.component.html
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/app/shared/components/popup-alert/popup-alert.component.ts
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
  src/assets/images/onboarding-success.gif
  src/assets/svg/check.svg
  src/assets/svg/progress-bar.svg
Labels: size/XL

#3442 fix: Sentence case Changes
  src/app/core/mock-data/action-sheet-options.data.ts
  src/app/core/mock-data/dashboard-task.data.ts
  src/app/core/mock-data/task.data.ts
  src/app/core/services/tasks.service.ts
  src/app/fyle/add-edit-advance-request/camera-options-popup/camera-options-popup.component.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.spec.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/my-expenses/add-expense-popover/add-expense-popover.component.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-view-advance/my-view-advance.page.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.spec.ts
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.ts
  src/app/shared/components/fy-select/fy-select.component.spec.ts
  src/app/shared/components/fy-select/fy-select.component.ts
  src/app/shared/components/virtual-select/virtual-select.component.spec.ts
  src/app/shared/components/virtual-select/virtual-select.component.ts
Labels: size/M

#3447 fix: change back to default(minor fix)
  src/app/fyle/add-edit-advance-request/camera-options-popup/camera-options-popup.component.html
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.html
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.spec.ts
  src/app/shared/components/capture-receipt/add-more-popup/add-more-popup.component.ts
Labels: size/XS

#3449 fix: adding limit of 200 while fetching dependent field values
  src/app/core/services/dependent-fields.service.ts
  src/app/core/test-data/dependent-fields.service.spec.data.ts
Labels: size/XS

#3445 fix: fix edge case for already verified mobile
  src/app/auth/new-password/new-password.page.html
  src/app/auth/new-password/new-password.page.scss
  src/app/auth/new-password/new-password.page.ts
  src/app/core/guards/onboarding.guard.spec.ts
  src/app/core/guards/onboarding.guard.ts
  src/app/core/services/spender-onboarding.service.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.scss
  src/app/fyle/spender-onboarding/spender-onboarding.page.html
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/post-verification/invited-user/invited-user.page.html
  src/app/post-verification/invited-user/invited-user.page.scss
  src/app/post-verification/invited-user/invited-user.page.ts
  src/app/shared/components/popup-alert/popup-alert.component.scss
Labels: size/L

#3452 fix: fix onboarding test for error popover
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.ts
  src/global.scss
Labels: size/S

#3450 fix: limit select custom field items to 200
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
  src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
  src/app/shared/components/fy-select/fy-select.component.spec.ts
  src/app/shared/components/fy-select/fy-select.component.ts
Labels: size/M

#3454 fix: Add more trackers for sign in and other fixes
  src/app/auth/new-password/new-password.page.spec.ts
  src/app/auth/new-password/new-password.page.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/app/auth/verify/verify.page.spec.ts
  src/app/auth/verify/verify.page.ts
  src/app/fyle/spender-onboarding/spender-onboarding-opt-in-step/spender-onboarding-opt-in-step.component.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.spec.ts
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
  src/app/post-verification/invited-user/invited-user.page.spec.ts
  src/app/post-verification/invited-user/invited-user.page.ts
Labels: size/S

#3456 fix: subscribe to onboarding completion when there is nothing to do in onboarding
  src/app/fyle/spender-onboarding/spender-onboarding.page.ts
Labels: size/XS
