Repository fylein/fyle-mobile-app, pull requests merged in 2025-04, with the labels that each got.

#3644 fix: Fix new vulnerabilities in vite
  package-lock.json
  package.json
Labels: size/XS

#3645 fix: Update vite again
  package-lock.json
  package.json
Labels: size/XS

#3647 fix: initialise timezone on home page after login
  src/app/app.module.ts
  src/app/core/services/config.service.spec.ts
  src/app/core/services/config.service.ts
  src/app/core/services/timezone.service.spec.ts
  src/app/core/services/timezone.service.ts
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
Labels: size/M

#3648 fix: sentry issue of undefined pipe
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3646 fix: Sentry array join error
  src/app/core/services/custom-inputs.service.ts
Labels: size/XS

#3650 feat: add user-greetings on dashboard
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.ts
Labels: size/S

#3651 fix: Fix bottom padding for advances lv
  src/app/fyle/team-advance/team-advance.page.html
  src/app/fyle/team-advance/team-advance.page.scss
Labels: size/XS

#3589 feat: upgrade to capacitor v7
  android/.gitignore
  android/.idea/compiler.xml
  android/.idea/misc.xml
  android/app/capacitor.build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/capacitor.config.json
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/variables.gradle
  capacitor.config.ts
  ios/App/App/capacitor.config.json
  ios/App/Podfile.lock
  package-lock.json
  package.json
  src/app/app.component.ts
Labels: size/XL

#3653 fix: Add approval filter to restrict secondary approvers from seeing unapproved reports
  src/app/core/mock-data/api-params.data.ts
  src/app/core/models/get-tasks-query-params-with-filters.model.ts
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
Labels: size/M

#3655 build: Bump vite
  package-lock.json
  package.json
Labels: size/XS

#3652 fix: QA fixes for approval tooltip and team reports lv
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/team-reports/team-reports-1.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.html
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.spec.ts
Labels: size/M

#3657 fix: fix params for team reports filtering
  src/app/fyle/team-reports/team-reports.page.ts
Labels: size/XS

#3656 chore:remove LD flag for timezone conversion
  src/app/core/services/timezone.service.ts
Labels: size/XS

#3660 fix: remove ld flag for approval workflows
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/S

#3659 chore: sentence case fixes
  src/app/core/mock-data/modal-controller.data.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/merge-expense/category-dependent-fields-form/category-dependent-fields-form.component.html
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/merge-expense/merge-expense.page.html
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
  src/app/fyle/my-view-advance/my-view-advance.page.html
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.html
  src/app/shared/components/fy-approver/add-approvers-popover/add-approvers-popover.component.html
  src/app/shared/components/fy-select-commute-details/fy-select-commute-details.component.html
  src/app/shared/components/fy-select/fy-select.component.spec.ts
  src/app/shared/components/fy-select/fy-select.component.ts
  src/app/shared/components/fy-view-attachment/fy-view-attachment.component.html
  src/app/shared/components/route-selector/route-selector.component.html
  src/app/shared/components/virtual-select/virtual-select.component.ts
  src/global.scss
Labels: size/M

#3661 fix: margin issue of project field inside expense form
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.scss
Labels: size/XS

#3658 fix: Show generic loader when upload heic images takes more than 300ms.
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.spec.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.ts
Labels: size/M

#3663 fix: fix the show date for first comment added in reports
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/pipes/date-with-timezone.pipe.ts
Labels: size/S

#3631 feat: Added the services and migrated the get method
  src/app/core/mock-data/expense-comment.data.ts
  src/app/core/models/expense-comment.model.ts
  src/app/core/models/policy-violation-comment.model.ts
  src/app/core/services/platform/v1/approver/expense-comment.service.spec.ts
  src/app/core/services/platform/v1/approver/expense-comment.service.ts
  src/app/core/services/platform/v1/shared/date.service.ts
  src/app/core/services/platform/v1/spender/expense-comment.service.spec.ts
  src/app/core/services/platform/v1/spender/expense-comment.service.ts
  src/app/core/services/status.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-3.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-4.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-2.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-3.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-4.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-5.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.setup.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-3.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-4.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-5.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.setup.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/view-expense/view-expense.page.spec.ts
  src/app/fyle/view-expense/view-expense.page.ts
  src/app/fyle/view-mileage/view-mileage.page.spec.ts
  src/app/fyle/view-mileage/view-mileage.page.ts
  src/app/fyle/view-per-diem/view-per-diem.page.spec.ts
  src/app/fyle/view-per-diem/view-per-diem.page.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
Labels: size/L

#3662 chore: move employee methods to employees service
  src/app/core/mock-data/expenses-info.data.ts
  src/app/core/models/expenses-info.model.ts
  src/app/core/services/merge-expenses.service.ts
  src/app/core/services/org-user.service.spec.ts
  src/app/core/services/org-user.service.ts
  src/app/core/services/platform/v1/spender/employees.service.spec.ts
  src/app/core/services/platform/v1/spender/employees.service.ts
  src/app/fyle/delegated-accounts/delegated-accounts.page.spec.ts
  src/app/fyle/help/help.page.spec.ts
  src/app/fyle/help/help.page.ts
  src/app/fyle/merge-expense/merge-expense.page.ts
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.spec.ts
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.ts
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.spec.ts
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
Labels: size/M

#3665 fix: fixed the user id for expense comments API
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
Labels: size/XS

#3666 fix: fixed the user id in findLatestExpenseComments
  src/app/core/services/platform/v1/spender/expense-comment.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/XS

#3609 chore: Add Security Scan Workflow
  .github/workflows/security-scan.yml
Labels: size/S

#3649 refactor: Migrate org API endpoints from v2 to platform
  src/app/core/mock-data/org.data.ts
  src/app/core/models/org.model.ts
  src/app/core/services/org.service.spec.ts
  src/app/core/services/org.service.ts
Labels: size/M

#3664 feat: setting is_admin true for refiner for roles other than SPENDER and APPROVER
  src/app/core/services/refiner.service.ts
Labels: size/XS

#3668 fix: loader service showLoader method
  src/app/core/guards/onboarding.guard.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.spec.ts
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/XS

#3667 fix: Updated the creator_id in expense to user_id
  src/app/core/services/transaction.service.ts
Labels: size/XS

#3669 fix: Fyle filter out remove web dev errors from sentry staging
  src/main.ts
Labels: size/S
