Repository fylein/fyle-mobile-app, pull requests merged in 2025-03, with the labels that each got.

#3545 feat: Add popover for approvers in View team report page
  src/app/core/mock-data/personal-card-txn-expense-suggestions.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/models/platform/approval-state.enum.ts
  src/app/core/models/platform/report-approvals.model.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.html
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.scss
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.spec.ts
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.ts
  src/app/shared/shared.module.ts
  src/assets/svg/line-default.svg
Labels: size/L

#3536 fix: navigation logic between review split expense modal and add-edit…
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/L

#3564 fix: add-edit expense and split service test cases
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/XS

#3513 fix: update category project mapping, split form with updated ui
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/split-config.data.ts
  src/app/core/mock-data/split-expense.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/filtered-missing-fields-violations.model.ts
  src/app/core/models/filtered-split-policy-violations.model.ts
  src/app/core/models/policy-violation.model.ts
  src/app/core/models/split-config.model.ts
  src/app/core/models/splitting-expense-properties.model.ts
  src/app/core/models/transformed-split-expense-missing-fields.model.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.scss
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.html
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.scss
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.spec.ts
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.ts
  src/app/shared/components/fy-select/fy-select.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.scss
  src/app/shared/shared.module.ts
Labels: size/XL

#3565 feat: add org settings to reports page
  src/app/core/models/org-settings.model.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/S

#3568 fix: set native config to staging for ios build in manual workflow and app…
  .github/workflows/appflow-release-branch.yml
  .github/workflows/manual-appflow-1.yml
Labels: size/XS

#3569 fix: currency amount spacing issue in cc stats
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
Labels: size/S

#3562 feat: Migrate /v2/spender_employees to platform
  src/app/core/mock-data/employee.data.ts
  src/app/core/models/employee-params.model.ts
  src/app/core/models/spender/employee.model.ts
  src/app/core/services/org-user.service.spec.ts
  src/app/core/services/org-user.service.ts
  src/app/core/test-data/org-user.service.spec.data.ts
  src/app/fyle/delegated-accounts/delegated-accounts.page.spec.ts
  src/app/fyle/help/help.page.spec.ts
  src/app/fyle/help/help.page.ts
  src/app/fyle/help/support-dialog/support-dialog.page.html
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.html
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.spec.ts
  src/app/shared/components/fy-approver/add-approvers-popover/approver-dialog/approver-dialog.component.ts
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.html
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.spec.ts
  src/app/shared/components/fy-userlist/fy-userlist-modal/fy-userlist-modal.component.ts
Labels: size/L

#3574 chore: remove getAssignedCards from my-expenses.page.spec, unused imports and typo fixes
  src/app/auth/pending-verification/pending-verification.page.spec.ts
  src/app/auth/sign-in/sign-in.page.spec.ts
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/core/interceptors/httpInterceptor.spec.ts
  src/app/core/mock-data/access-token-data.data.ts
  src/app/core/mock-data/auth-reponse.data.ts
  src/app/core/mock-data/auth-response.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/services/auth.service.spec.ts
  src/app/core/services/google-auth.service.spec.ts
  src/app/core/services/router-auth.service.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-2.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
Labels: size/M

#3572 fix: mandatory field reset after disable
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.scss
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/global.scss
Labels: size/L

#3566 test: feat split expense
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.scss
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/global.scss
Labels: size/L

#3571 feat: Ionic v7 upgrade
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/personal-cards/personal-cards.page.scss
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/global.scss
Labels: size/M

#3567 feat: Capacitor v5 upgrade, ionic v7 upgrade
  .github/workflows/appflow-release-branch.yml
  .github/workflows/manual-appflow-1.yml
  android/.gitignore
  android/.idea/compiler.xml
  android/.idea/misc.xml
  android/app/build.gradle
  android/app/capacitor.build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/capacitor.config.json
  android/app/src/main/assets/capacitor.plugins.json
  android/build.gradle
  android/capacitor.settings.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/variables.gradle
  capacitor.config.ts
  ios/.gitignore
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-83.5x83.5@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/App/App/Info.plist
  ios/App/App/config.xml
  ios/App/Podfile
  ios/App/Podfile.lock
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/mock-data/extended-device-info.data.ts
  src/app/core/models/extended-device-info.model.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/personal-cards/personal-cards.page.scss
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/global.scss
Labels: size/M

#3582 fix: split exp design fixes
  src/app/fyle/split-expense/split-expense.page.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.scss
  src/global.scss
Labels: size/S

#3576 fix: design fix for split exp page
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.scss
  src/global.scss
Labels: size/M

#3575 fix: add-edit expense page category validation error
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.scss
  src/global.scss
Labels: size/M

#3583 fix: set minimum IOS version to v 14
  ios/App/Podfile
  ios/App/Podfile.lock
Labels: size/XS

#3580 fix: sentence casing across all templates
  src/app/auth/new-password/popup/popup.component.html
  src/app/auth/request-invitation/request-invitation.page.html
  src/app/auth/sign-in/sign-in.page.html
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-expense/camera-options-popup/camera-options-popup.component.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/delegated-accounts/delegated-accounts.page.html
  src/app/fyle/help/support-dialog/support-dialog.page.html
  src/app/fyle/manage-corporate-cards/add-corporate-card/add-corporate-card.component.html
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-profile/preference-setting/preference-setting.component.html
  src/app/fyle/personal-cards-matched-expenses/expense-preview/expense-preview.component.html
  src/app/fyle/personal-cards/date-range-modal/date-range-modal.component.html
  src/app/fyle/spender-onboarding/spender-onboarding-connect-card-step/spender-onboarding-connect-card-step.component.html
  src/app/fyle/view-expense/view-expense.page.html
  src/app/fyle/view-mileage/view-mileage.page.html
  src/app/fyle/view-per-diem/view-per-diem.page.html
  src/app/fyle/view-team-report/share-report/share-report.component.html
  src/app/post-verification/invited-user/invited-user.page.html
  src/app/post-verification/setup-account-preferences/setup-account-preferences.page.html
  src/app/post-verification/setup-account/setup-account.page.html
  src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.html
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.html
  src/app/shared/components/create-new-report-v2/create-new-report.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.html
  src/app/shared/components/fy-popup/fy-popup.component.html
  src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.html
  src/app/shared/components/fy-view-report-info/fy-view-report-info.component.html
  src/app/shared/components/route-selector/route-selector.component.html
  src/app/shared/components/send-email/send-email.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.html
  src/app/shared/components/transaction-status-info-popover/transaction-status-info-popover.component.spec.ts
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.html
  src/index.html
Labels: size/M

#3586 fix: unit test for migration of /v2/expenses_and_ccce/stats
  src/app/core/mock-data/card-aggregate-stats.data.ts
  src/app/core/mock-data/ccc-expense.details.data.ts
  src/app/core/mock-data/platform-corporate-card-detail.data.ts
  src/app/core/mock-data/stats-response.data.ts
  src/app/core/mock-data/unique-cards-stats..data.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
Labels: size/L

#3588 fix: set minimum IOS target in xcode
  ios/App/App.xcodeproj/project.pbxproj
Labels: size/XS

#3587 fix: split expense final patches
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/projects.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.scss
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/M

#3585 fix: update missing fields modal
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/projects.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.scss
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/popup-alert/popup-alert.component.html
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/app/shared/components/popup-alert/popup-alert.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
Labels: size/L

#3590 fix: Fix EOL/Outdated JS dependencies
  .gitignore
  package-lock.json
  package.json
Labels: size/XL

#3490 feat: new split expense flow across all dimensions
  src/app/core/mock-data/filtered-missing-fields-violations.data.ts
  src/app/core/mock-data/filtered-split-policy-violations.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/mock-data/policy-violation.data.ts
  src/app/core/mock-data/split-config.data.ts
  src/app/core/mock-data/split-expense.data.ts
  src/app/core/mock-data/transformed-split-expense-missing-fields.data.ts
  src/app/core/models/filtered-missing-fields-violations.model.ts
  src/app/core/models/filtered-split-policy-violations.model.ts
  src/app/core/models/policy-violation.model.ts
  src/app/core/models/split-config.model.ts
  src/app/core/models/splitting-expense-properties.model.ts
  src/app/core/models/transformed-split-expense-missing-fields.model.ts
  src/app/core/services/platform/v1/spender/expenses.service.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/split-expense.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-2.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
  src/app/fyle/split-expense/split-expense.page.html
  src/app/fyle/split-expense/split-expense.page.scss
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.html
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.scss
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.spec.ts
  src/app/shared/components/fy-msg-popover/fy-msg-popover.component.ts
  src/app/shared/components/fy-select-project/fy-select-project.component.ts
  src/app/shared/components/fy-select/fy-select.component.ts
  src/app/shared/components/popup-alert/popup-alert.component.html
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/app/shared/components/popup-alert/popup-alert.component.ts
  src/app/shared/components/review-split-expense/review-split-expense.component.html
  src/app/shared/components/review-split-expense/review-split-expense.component.scss
  src/app/shared/components/review-split-expense/review-split-expense.component.spec.ts
  src/app/shared/components/review-split-expense/review-split-expense.component.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.scss
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.spec.ts
  src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
  src/app/shared/shared.module.ts
  src/global.scss
  src/theme/colors.scss
Labels: size/XL

#3591 fix: placing eslint unsafe member access to required lines
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3592 fix: sentence case issues across titles
  src/app/core/mock-data/modal-controller.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/team-reports/team-reports.page.html
  src/app/fyle/team-reports/team-reports.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
Labels: size/S

#3594 fix: using absolute tax and expense amount for greater amount comparison
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3595 fix: cost center visibility updatation on category change inside add-edit exp page
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/XS

#3570 fix: Making bottom navbar static for all pages
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/core/services/footer.service.spec.ts
  src/app/core/services/footer.service.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/L

#3548 feat: Walkthrough implementation for mobile app
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/core/mock-data/feature-config.data.ts
  src/app/core/services/footer.service.spec.ts
  src/app/core/services/footer.service.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/walkthrough.service.spec.ts
  src/app/core/services/walkthrough.service.ts
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.scss
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/shared/components/footer/footer.component.html
  src/app/shared/components/footer/footer.component.scss
  src/assets/styles/_fy_driver_tour.scss
  src/global.scss
  src/theme/colors.scss
Labels: size/XL

#3530 feat: new navbar with Expenses and Reports tab added
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/core/mock-data/feature-config.data.ts
  src/app/core/services/footer.service.spec.ts
  src/app/core/services/footer.service.ts
  src/app/core/services/tracking.service.ts
  src/app/core/services/walkthrough.service.spec.ts
  src/app/core/services/walkthrough.service.ts
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/dashboard/stats/stats.component.html
  src/app/fyle/dashboard/stats/stats.component.scss
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/shared/components/footer/footer-state.enum.ts
  src/app/shared/components/footer/footer.component.html
  src/app/shared/components/footer/footer.component.scss
  src/app/shared/components/footer/footer.component.spec.ts
  src/app/shared/components/footer/footer.component.ts
  src/app/shared/icon/icon.module.ts
  src/assets/styles/_fy_driver_tour.scss
  src/assets/svg/folder-fill.svg
  src/assets/svg/list-fill.svg
  src/global.scss
  src/theme/colors.scss
Labels: size/XL

#3584 feat: Migrate /v2/expenses_and_ccce/stats to platform
  src/app/core/mock-data/card-aggregate-stats.data.ts
  src/app/core/mock-data/ccc-expense.details.data.ts
  src/app/core/mock-data/platform-corporate-card-detail.data.ts
  src/app/core/mock-data/stats-response.data.ts
  src/app/core/mock-data/unique-cards-stats..data.ts
  src/app/core/models/card-aggregate-stats.model.ts
  src/app/core/models/card-state-data.model.ts
  src/app/core/models/card-transaction-stat.model.ts
  src/app/core/models/ccc-expense-details.model.ts
  src/app/core/models/platform-corporate-card-detail.model.ts
  src/app/core/services/corporate-credit-card-expense.service.spec.ts
  src/app/core/services/corporate-credit-card-expense.service.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.ts
  src/app/fyle/dashboard/dashboard.service.spec.ts
  src/app/fyle/dashboard/dashboard.service.ts
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/shared/components/spent-cards/card-detail/card-detail.component.html
Labels: size/L

#3597 fix: Fyle capacitor v5 revert
  .github/workflows/appflow-release-branch.yml
  .github/workflows/manual-appflow-1.yml
  android/.gitignore
  android/.idea/compiler.xml
  android/.idea/misc.xml
  android/app/build.gradle
  android/app/capacitor.build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/capacitor.config.json
  android/app/src/main/assets/capacitor.plugins.json
  android/build.gradle
  android/capacitor.settings.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/variables.gradle
  capacitor.config.ts
  ios/.gitignore
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-83.5x83.5@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/App/App/Info.plist
  ios/App/App/config.xml
  ios/App/Podfile
  ios/App/Podfile.lock
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/mock-data/extended-device-info.data.ts
  src/app/core/models/extended-device-info.model.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/personal-cards/personal-cards.page.scss
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/global.scss
Labels: size/M

#3598 fix: fix native config (set to staging)
  .github/workflows/appflow-release-branch.yml
  .github/workflows/manual-appflow-1.yml
Labels: size/XS

#3599 fix: Fix prod buld crash and bring back cap v5 and ionic v7
  android/.gitignore
  android/.idea/compiler.xml
  android/.idea/misc.xml
  android/app/build.gradle
  android/app/capacitor.build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/capacitor.config.json
  android/app/src/main/assets/capacitor.plugins.json
  android/build.gradle
  android/capacitor.settings.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/variables.gradle
  capacitor.config.ts
  ios/.gitignore
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-83.5x83.5@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/App/App/Info.plist
  ios/App/App/config.xml
  ios/App/Podfile
  ios/App/Podfile.lock
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/auth/switch-org/switch-org.page.spec.ts
  src/app/auth/switch-org/switch-org.page.ts
  src/app/core/mock-data/extended-device-info.data.ts
  src/app/core/models/extended-device-info.model.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/personal-cards/personal-cards.page.scss
  src/app/shared/components/popup-alert/popup-alert.component.scss
  src/global.scss
Labels: size/M

#3602 fix: fix babel issues
  .gitignore
  package-lock.json
  package.json
Labels: size/XL

#3604 fix: bring back package-lock.json
  .gitignore
  package-lock.json
Labels: size/XL

#3581 feat: Ionic v8
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/Podfile
  ios/App/Podfile.lock
  package-lock.json
  package.json
  src/app/fyle/personal-cards/personal-cards.page.html
Labels: size/L

#3601 fix: Walkthrough navigation fix for different routes
  src/app/core/services/walkthrough.service.ts
  src/app/fyle/dashboard/dashboard.page.ts
Labels: size/S

#3606 fix: modification for sentry grouping -> replace transaction_id with <expense_id>
  src/main.ts
Labels: size/XS

#3607 fix: show correct msg for disabled category
  src/app/fyle/split-expense/split-expense.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.ts
Labels: size/M

#3605 fix: walkthrough overlay click logic
  src/app/core/services/walkthrough.service.ts
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
Labels: size/M

#3610 fix: walkthrough quit for opt in dialog box
  src/app/fyle/dashboard/dashboard.page.ts
Labels: size/S

#3603 fix: fixed the timezone to user settings preferences
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/models/extended_status.model.ts
  src/app/core/models/platform/v1/comment.model.ts
  src/app/core/models/platform/v1/extended-comment.model.ts
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/status.service.spec.ts
  src/app/core/services/status.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.html
  src/app/shared/pipes/date-timezone.pipe.spec.ts
  src/app/shared/pipes/date-timezone.pipe.ts
  src/app/shared/shared.module.ts
Labels: size/M

#3612 fix: sentry issue for dashboard service
  src/app/fyle/dashboard/dashboard.service.ts
Labels: size/XS

#3593 fix: readme -> change to npm ci
  README.md
Labels: size/XS

#3600 fix: expense unselected delete issue
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/S

#3618 fix: bug on segment change in view my report and manage corporate card…
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.spec.ts
  src/app/fyle/manage-corporate-cards/manage-corporate-cards.page.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
Labels: size/S

#3621 fix: unit tests for approver advance_requests api migration
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/fyle/team-advance/team-advance.page.spec.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
Labels: size/L

#3613 feat: migrate Approver /v2/advance_requests to platform
  src/app/core/mock-data/extended-advance-request.data.ts
  src/app/core/mock-data/platform/v1/advance-request-platform.data.ts
  src/app/core/models/extended_advance_request.model.ts
  src/app/core/models/platform/advance-request-platform.model.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/fyle/team-advance/team-advance.page.spec.ts
  src/app/fyle/team-advance/team-advance.page.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
Labels: size/L

#3619 fix: remove partially approved reports from add to report dialog
  src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
Labels: size/XS

#3622 feat: Redirect to password expire page on 406 error
  src/app/auth/reset-password/reset-password.page.html
  src/app/auth/reset-password/reset-password.page.scss
  src/app/auth/reset-password/reset-password.page.spec.ts
  src/app/auth/reset-password/reset-password.page.ts
  src/app/auth/sign-in/sign-in.page.ts
  src/app/auth/verify/verify.page.ts
  src/theme/colors.scss
Labels: size/M

#3623 feat: make billable optional for mileage and per-diem exp
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.scss
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/S

#3616 fix: make billable field optional inside merge expense
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.html
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
  src/app/fyle/merge-expense/merge-expense.page.html
  src/app/fyle/merge-expense/merge-expense.page.ts
Labels: size/M

#3615 fix: make billable field optional for add-edit expense
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem-1.page.spec.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.scss
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
Labels: size/M

#3620 feat: API integration for View Report
  src/app/core/mock-data/personal-card-txn-expense-suggestions.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/models/platform/report-approvals.model.ts
  src/app/fyle/my-view-report/my-view-report.page.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-approver/add-approvers-popover/add-approvers-popover.component.html
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.spec.ts
  src/app/shared/components/fy-approver/show-all-approvers-popover/show-all-approvers-popover.component.ts
Labels: size/M

#3629 fix: Revert fixed the timezone to user settings preferences
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/models/extended_status.model.ts
  src/app/core/models/platform/v1/comment.model.ts
  src/app/core/models/platform/v1/extended-comment.model.ts
  src/app/core/services/platform/v1/approver/reports.service.spec.ts
  src/app/core/services/platform/v1/approver/reports.service.ts
  src/app/core/services/platform/v1/spender/reports.service.spec.ts
  src/app/core/services/platform/v1/spender/reports.service.ts
  src/app/core/services/status.service.spec.ts
  src/app/core/services/status.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.html
  src/app/shared/pipes/date-timezone.pipe.spec.ts
  src/app/shared/pipes/date-timezone.pipe.ts
  src/app/shared/shared.module.ts
Labels: size/M

#3626 fix: filter behaviour in Team advance requests
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/fyle/team-advance/team-advance.page.spec.ts
  src/app/fyle/team-advance/team-advance.page.ts
Labels: size/M

#3630 fix: Fyle fix edge to edge
  android/.gitignore
  android/app/src/main/assets/capacitor.config.json
  capacitor.config.ts
  package.json
  src/app/app.component.ts
Labels: size/S

#3625 fix: Add sentry fixes - part 1
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
  src/app/shared/components/create-new-report-v2/create-new-report.component.ts
  src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.html
Labels: size/S

#3632 fix: sidenav and page titles inconsistency
  src/app/core/mock-data/sidemenu-item.data.ts
  src/app/core/mock-data/sidemenu.data.ts
  src/app/fyle/my-advances/my-advances.page.html
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/team-advance/team-advance.page.html
  src/app/fyle/team-reports/team-reports.page.html
  src/app/shared/components/sidemenu/sidemenu.component.spec.ts
  src/app/shared/components/sidemenu/sidemenu.component.ts
Labels: size/S

#3635 fix: Add a tracker for opening of potential duplicate dialog in case any undefined ids are present
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-expense/add-edit-expense.setup.spec.ts
Labels: size/S

#3634 fix: fix approver order and org settings flag
  src/app/core/models/org-settings.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.ts
Labels: size/S

#3633 chore: Deprecate api-v2 service, spec, and related references
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/services/api-v2.service.spec.ts
  src/app/core/services/api-v2.service.ts
  src/app/core/services/personal-cards.service.spec.ts
  src/app/core/services/personal-cards.service.ts
  src/app/core/services/projects.service.spec.ts
  src/app/core/services/projects.service.ts
  src/app/core/services/router-auth.service.spec.ts
  src/app/core/services/router-auth.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/fyle/team-reports/team-reports-2.page.spec.ts
  src/app/fyle/team-reports/team-reports-3.page.spec.ts
  src/app/fyle/team-reports/team-reports-4.page.spec.ts
  src/app/fyle/team-reports/team-reports.page.setup.spec.ts
Labels: size/L

#3637 fix: fix token issue for mobile app
  src/app/core/services/auth.service.spec.ts
  src/app/core/services/auth.service.ts
Labels: size/XS

#3627 chore: Change zero state illustrations
  src/app/auth/switch-org/switch-org.page.html
  src/app/fyle/dashboard/tasks/tasks.component.html
  src/app/fyle/my-advances/my-advances.page.html
  src/app/fyle/my-create-report/my-create-report.page.html
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.scss
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
  src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.spec.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/my-view-report/my-view-report.page.scss
  src/app/fyle/personal-cards/personal-cards.page.html
  src/app/fyle/personal-cards/personal-cards.page.scss
  src/app/fyle/team-advance/team-advance.page.html
  src/app/fyle/team-reports/team-reports.page.html
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/shared/components/comments-history/view-comment/view-comment.component.html
  src/app/shared/components/comments-history/view-comment/view-comment.component.scss
  src/app/shared/components/dependent-fields/dependent-field/dependent-field-modal/dependent-field-modal.component.html
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.html
  src/app/shared/components/fy-add-to-report/fy-add-to-report-modal/fy-add-to-report-modal.component.spec.ts
  src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.html
  src/app/shared/components/fy-zero-state/fy-zero-state.component.scss
  src/app/shared/components/virtual-select/virtual-select-modal/virtual-select-modal.component.html
  src/assets/images/zero-states/advances.png
  src/assets/images/zero-states/cards.png
  src/assets/images/zero-states/new-comments.png
  src/assets/images/zero-states/new-expenses.png
  src/assets/images/zero-states/reports.png
  src/assets/images/zero-states/search.png
  src/assets/images/zero-states/tasks.png
Labels: size/M

#3640 fix: Added the timezone fix for audit trails
  src/app/app.module.ts
  src/app/constants.ts
  src/app/core/services/config.service.spec.ts
  src/app/core/services/config.service.ts
  src/app/fyle/my-view-report/my-view-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.html
  src/app/shared/components/comments-history/audit-history/audit-history.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.html
  src/app/shared/pipes/date-with-timezone.pipe.spec.ts
  src/app/shared/pipes/date-with-timezone.pipe.ts
  src/app/shared/shared.module.ts
Labels: size/M

#3639 feat: Add action for EOL and outdated JS
  .github/workflows/eol-outdated-js-scan.yml
  suppression.xml
Labels: size/M

#3638 fix: fix eslint errors in AuthService
  src/app/core/services/auth.service.ts
Labels: size/XS

#3641 feat: removed unused IP_FIND_KEY env variable
  README.md
  hooks/utils/prod-environment.js
  src/environments/environment.ts
Labels: size/XS

#3642 chore: remove unused zero state illustrations
  src/app/shared/icon/icon.module.ts
  src/assets/images/zero-states/comments.svg
  src/assets/images/zero-states/completed-tasks.png
  src/assets/images/zero-states/expenses.png
  src/assets/images/zero-states/search-not-found.svg
Labels: size/M

#3643 test: Fyle 86cyba3hz tests
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.spec.ts
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
Labels: size/L

#3617 fix: Mileage location permission, settings fixes.
  src/app/core/services/location.service.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.html
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.spec.ts
  src/app/shared/components/fy-location/fy-location-modal/fy-location-modal.component.ts
Labels: size/L
