Repository fylein/fyle-mobile-app, pull requests merged in 2025-07, with the labels that each got.

#3746 fix: the notifications page with updated employee settings
  src/app/fyle/notifications/email-notifications/email-notifications.component.spec.ts
  src/app/fyle/notifications/email-notifications/email-notifications.component.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.service.spec.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.service.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.spec.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.ts
Labels: size/L

#3747 fix: email-notification-header
  src/app/fyle/notifications/email-notifications/email-notifications.component.html
  src/app/fyle/notifications/email-notifications/email-notifications.component.scss
  src/app/fyle/notifications/email-notifications/email-notifications.component.spec.ts
  src/app/fyle/notifications/email-notifications/email-notifications.component.ts
Labels: size/M

#3751 fix: migrate unlink card expense to platform
  src/app/core/mock-data/undo-merge.data.ts
  src/app/core/models/platform/unlink-card-transaction-response.model.ts
  src/app/core/models/undo-merge.model.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
Labels: size/M

#3753 feat: use custom eslint rule from fyle-eslint-plugin
  .eslintrc.json
  package-lock.json
  package.json
Labels: size/M

#3754 fix: qa fixes for notifications-beta page
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.html
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.scss
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.spec.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.ts
  src/app/fyle/notifications/notifications-routing.module.ts
  src/app/fyle/notifications/notifications.module.ts
  src/app/fyle/notifications/notifications.page.html
  src/app/fyle/notifications/notifications.page.scss
  src/app/fyle/notifications/notifications.page.spec.ts
  src/app/fyle/notifications/notifications.page.ts
  src/assets/images/zero-states/notifications.png
  src/global.scss
Labels: size/XL

#3748 feat: GET and POST statuses, POST /submit , POST /pull_back, POST /add_approver for advance request
  src/app/core/mock-data/advance-request-file.data.ts
  src/app/core/mock-data/platform-report.data.ts
  src/app/core/mock-data/platform/v1/advance-request-platform.data.ts
  src/app/core/models/advance-request-file.model.ts
  src/app/core/models/platform/advance-request-platform.model.ts
  src/app/core/models/platform/v1/comment.model.ts
  src/app/core/services/advance-request.service.spec.ts
  src/app/core/services/advance-request.service.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-1.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.spec.ts
  src/app/shared/components/comments-history/view-comment/view-comment.component.ts
Labels: size/XL

#3755 feat: Cleanup for accounts API migration
  src/app/core/enums/account-type.enum.ts
  src/app/core/mock-data/data-transform.data.ts
  src/app/core/mock-data/dependent-field-expenses.data.ts
  src/app/core/mock-data/expense-v2.data.ts
  src/app/core/mock-data/expense.data.ts
  src/app/core/mock-data/extended-account.data.ts
  src/app/core/mock-data/org-payment-mode-settings.data.ts
  src/app/core/mock-data/org-settings.data.ts
  src/app/core/mock-data/unflattened-txn.data.ts
  src/app/core/models/account-option.model.ts
  src/app/core/models/allowed-payment-modes.enum.ts
  src/app/core/models/extended-account.model.ts
  src/app/core/models/mileage-form-value.model.ts
  src/app/core/models/per-diem-form-value.model.ts
  src/app/core/services/accounts.service.spec.ts
  src/app/core/services/accounts.service.ts
  src/app/core/services/payment-modes.service.spec.ts
  src/app/core/services/payment-modes.service.ts
  src/app/core/services/platform/v1/approver/employee-settings.service.spec.ts
  src/app/core/services/platform/v1/approver/employee-settings.service.ts
  src/app/core/services/platform/v1/spender/employee-settings.service.spec.ts
  src/app/core/services/platform/v1/spender/employee-settings.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/test-data/accounts.service.spec.data.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-5.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense-6.spec.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-expense/add-edit-expense.page.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage-1.spec.ts
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/delegated-accounts/delegated-accounts.page.html
  src/app/fyle/delegated-accounts/delegated-accounts.page.spec.ts
  src/app/fyle/delegated-accounts/delegated-accounts.page.ts
  src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.spec.ts
  src/app/fyle/merge-expense/merge-expense-2.page.spec.ts
  src/app/fyle/split-expense/split-expense.page.spec.ts
Labels: size/XL

#3765 fix: issue with observable subscription | refiner service
  src/app/core/services/refiner.service.ts
Labels: size/M

#3764 fix: add loader service, and 2 email events to notifications page
  src/app/core/mock-data/notification-events.data.ts
  src/app/core/models/notification-events.enum.ts
  src/app/core/services/launch-darkly.service.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.service.spec.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.service.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.spec.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.ts
Labels: size/L

#3768 fix: set isNotificationsDisabled false by default
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.ts
Labels: size/XS

#3770 fix: remove ExtendedReports and report_approvals
  src/app/core/mock-data/api-reports.data.ts
  src/app/core/mock-data/report.data.ts
  src/app/core/models/report.model.ts
  src/app/core/services/tasks.service.spec.ts
  src/app/core/test-data/tasks.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense-1.spec.ts
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.spec.ts
  src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
Labels: size/XL

#3769 fix errors
  src/app/shared/components/toast-message/toast-message.component.ts
  src/theme/variables.scss
  tsconfig.json
Labels: size/XS

#3771 chore: remove unused pages and components
  src/app/auth/new-password/new-password.module.ts
  src/app/auth/new-password/popup/popup.component.html
  src/app/auth/new-password/popup/popup.component.scss
  src/app/auth/new-password/popup/popup.component.spec.ts
  src/app/auth/new-password/popup/popup.component.ts
  src/app/fyle/dashboard/card-stats/card-stats.component.spec.ts
  src/app/fyle/my-profile/my-profile.module.ts
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/preference-setting/event-data.model.ts
  src/app/fyle/my-profile/preference-setting/preference-setting.component.html
  src/app/fyle/my-profile/preference-setting/preference-setting.component.spec.ts
  src/app/fyle/my-profile/preference-setting/preference-setting.component.ts
  src/app/fyle/my-profile/select-currency/select-currency.component.html
  src/app/fyle/my-profile/select-currency/select-currency.component.scss
  src/app/fyle/my-profile/select-currency/select-currency.component.spec.ts
  src/app/fyle/my-profile/select-currency/select-currency.component.ts
  src/app/post-verification/post-verification-routing.module.ts
  src/app/post-verification/setup-account-preferences/setup-account-preferences-routing.module.ts
  src/app/post-verification/setup-account-preferences/setup-account-preferences.module.ts
  src/app/post-verification/setup-account-preferences/setup-account-preferences.page.html
  src/app/post-verification/setup-account-preferences/setup-account-preferences.page.scss
  src/app/post-verification/setup-account-preferences/setup-account-preferences.page.spec.ts
  src/app/post-verification/setup-account-preferences/setup-account-preferences.page.ts
  src/app/post-verification/setup-account/select-currency/select-currency.component.html
  src/app/post-verification/setup-account/select-currency/select-currency.component.scss
  src/app/post-verification/setup-account/select-currency/select-currency.component.spec.ts
  src/app/post-verification/setup-account/select-currency/select-currency.component.ts
  src/app/post-verification/setup-account/setup-account-routing.module.ts
  src/app/post-verification/setup-account/setup-account.module.ts
  src/app/post-verification/setup-account/setup-account.page.html
  src/app/post-verification/setup-account/setup-account.page.scss
  src/app/post-verification/setup-account/setup-account.page.spec.ts
  src/app/post-verification/setup-account/setup-account.page.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.spec.ts
  src/app/shared/components/view-dependent-fields/view-dependent-fields.component.ts
Labels: size/XL

#3775 fix: Adding i18n support for my-expense and my-reports pages
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/assets/i18n/en.json
Labels: size/L

#3773 feat: Dashboard add expense cta enhanced and zero state ctas added
  src/app/app.component.spec.ts
  src/app/core/services/walkthrough.service.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.scss
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-reports/my-reports.page.scss
  src/app/fyle/my-reports/my-reports.page.spec.ts
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/shared/icon/icon.module.ts
  src/app/transloco-http-loader.spec.ts
  src/assets/i18n/en.json
  src/assets/styles/_fy_driver_tour.scss
  src/assets/svg/plus.svg
Labels: size/XL

#3783 feat: Dashboard pending tasks notification
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/core/services/tracking.service.ts
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.scss
  src/app/fyle/dashboard/dashboard.page.ts
  src/assets/i18n/en.json
Labels: size/M

#3790 feat: Background scanning of receipt for save later
  src/app/core/models/receipt-preview-data.model.ts
  src/app/core/services/tracking.service.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.spec.ts
  src/app/shared/components/capture-receipt/capture-receipt.component.ts
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.html
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.ts
  src/assets/i18n/en.json
Labels: size/M

#3778 feat: Improve my expense page list view expense card
  src/app/core/mock-data/expense-field.data.ts
  src/app/core/services/expense-fields.service.spec.ts
  src/app/core/services/expense-fields.service.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.scss
  src/app/shared/components/expenses-card-v2/expenses-card.component.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.ts
  src/app/shared/components/route-visualizer/route-visualizer.component.spec.ts
  src/assets/i18n/en.json
Labels: size/L

#3795 feat: added Cursor rules for i18n
  .cursor/rules/atomics-i18n-key-pattern.mdc
  .cursor/rules/component-i18n-key-naming.mdc
Labels: size/M

#3796 chore: Adding trackers for new changes
  src/app/core/services/tracking.service.ts
  src/app/fyle/my-expenses/my-expenses.page.html
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-reports/my-reports.page.html
  src/app/fyle/my-reports/my-reports.page.ts
  src/app/shared/components/dashboard-email-opt-in/dashboard-email-opt-in.component.ts
  src/app/shared/components/dashboard-email-opt-in/dashboard-email-opt-in.spec.ts
Labels: size/M

#3800 fix: add the location key to ios-info.js
  hooks/utils/ios-info.js
Labels: size/XS

#3797 fix: QA fixes for the mobile nps changes
  src/app/fyle/dashboard/dashboard.page.html
  src/app/fyle/dashboard/dashboard.page.spec.ts
  src/app/fyle/dashboard/dashboard.page.ts
  src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.html
  src/assets/i18n/en.json
Labels: size/L

#3809 fix: Create report cta visibility fix
  src/app/fyle/my-reports/my-reports.page.html
Labels: size/XS

#3794 feat: Critical policy violation test fixes
  src/app/core/mock-data/expense-filters.data.ts
  src/app/core/mock-data/filter-options.data.ts
  src/app/core/mock-data/personal-card-txn-expense-suggestions.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-expenses/my-expenses.service.spec.ts
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.spec.ts
  src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.spec.ts
  src/assets/i18n/en.json
  src/theme/colors.scss
Labels: size/M

#3822 fix: Switch to latest build system
  .github/workflows/appflow-master.yml
  .github/workflows/appflow-release-branch.yml
  .github/workflows/internal-release.yml
  .github/workflows/manual-appflow-1.yml
  .github/workflows/manual-appflow-with-inputs.yml
  src/global.scss
Labels: size/XS

#3825 fix: Console error for audit histoy
  src/app/core/services/transactions-outbox.service.spec.ts
  src/app/shared/components/comments-history/audit-history/audit-history.component.ts
Labels: size/XS

#3793 feat: Critical policy violation behavioural change
  src/app/core/enums/filter-state.enum.ts
  src/app/core/mock-data/expense-filters.data.ts
  src/app/core/mock-data/filter-options.data.ts
  src/app/core/mock-data/personal-card-txn-expense-suggestions.data.ts
  src/app/core/mock-data/platform/v1/expense.data.ts
  src/app/core/models/expense-state.enum.ts
  src/app/core/models/org-settings.model.ts
  src/app/core/models/platform/v1/expense.model.ts
  src/app/core/models/policy-detail.model.ts
  src/app/core/services/org-settings.service.ts
  src/app/core/services/platform/v1/shared/expenses.service.spec.ts
  src/app/core/services/platform/v1/shared/expenses.service.ts
  src/app/core/services/status.service.spec.ts
  src/app/core/services/status.service.ts
  src/app/core/services/transaction.service.spec.ts
  src/app/core/services/transaction.service.ts
  src/app/core/test-data/org-settings.service.spec.data.ts
  src/app/core/test-data/status.service.spec.data.ts
  src/app/fyle/add-edit-expense/add-edit-expense.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
  src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
  src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
  src/app/fyle/my-expenses/my-expenses.page.spec.ts
  src/app/fyle/my-expenses/my-expenses.page.ts
  src/app/fyle/my-expenses/my-expenses.service.spec.ts
  src/app/fyle/my-expenses/my-expenses.service.ts
  src/app/fyle/view-expense/view-expense.page.html
  src/app/shared/components/expenses-card-v2/expenses-card.component.html
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.scss
  src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.spec.ts
  src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.html
  src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.scss
  src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.spec.ts
  src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.ts
  src/app/shared/components/policy-violation-rule/policy-violation-rule.component.html
  src/app/shared/components/policy-violation-rule/policy-violation-rule.component.scss
  src/app/shared/pipes/expense-state.pipe.ts
  src/assets/i18n/en.json
  src/theme/colors.scss
Labels: size/L

#3806 feat: Skeleton Loading support part 2
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-1.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request-2.page.spec.ts
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.scss
  src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
  src/app/fyle/my-profile/my-profile.page.html
  src/app/fyle/my-profile/my-profile.page.scss
  src/app/fyle/my-profile/my-profile.page.spec.ts
  src/app/fyle/my-profile/my-profile.page.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.scss
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.spec.ts
  src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
  src/app/fyle/my-view-advance/my-view-advance.page.html
  src/app/fyle/my-view-advance/my-view-advance.page.scss
  src/app/fyle/my-view-advance/my-view-advance.page.spec.ts
  src/app/fyle/my-view-advance/my-view-advance.page.ts
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.html
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.scss
  src/app/fyle/notifications/notifications-beta/notifications-beta.page.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.scss
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
  src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
  src/app/fyle/view-team-report/view-team-report.page.html
  src/app/fyle/view-team-report/view-team-report.page.scss
  src/app/fyle/view-team-report/view-team-report.page.spec.ts
  src/app/fyle/view-team-report/view-team-report.page.ts
  src/app/shared/components/fy-location/fy-location.component.ts
Labels: size/XL
